### ISSUE TITLE
A boolean false breaks querybuilder update

### ISSUE THREAD

**Issue by that-guy-iain** [doctrine/orm#11487]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.19.5

#### Summary

When you use false boolean value in the set of the querybuilder it doesn't work as expected.

```
$queryBuilder = $this->entityRepository->createQueryBuilder('t');
$queryBuilder->update(TaxType::class, 't')->set('t.default', false);
$queryBuilder->getQuery()->execute();
```
#### Current behavior

It causes the following error message

`Warning: Attempt to read property &quot;type&quot; on null in vendor/doctrine/orm/src/Query/Parser.php line 2928`

but it works if you put in `'false'`

#### How to reproduce

Create an entity with a boolean value and then try to set it using the query builder with a boolean `false`.

#### Expected behavior

For it to know that false is a boolean value and value for the boolean value or to return an Syntax error instead of trying to access full.

**Comment by greg0ire** [comment]
Fixed, thanks!
