### ISSUE TITLE
@ManyToMany relation matching criteria ignores isNull(column)

### ISSUE THREAD

**Issue by RusAlex** [doctrine/orm#5587]
I have an entity class where ManyMany relation described.

Then Im trying to do something like 

``` php
public function getActiveRel()
{
   $criteria = Criteria::create()
   ->where(Criteria::expr()->isNull('column'));

   return $this->rel->matching($criteria);
}
```

IsNull condition is ignored in SqlValueVisitor.php
https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Persisters/SqlValueVisitor.php#L57

And no any IS NULL in final SQL statement.

**Comment by RusAlex** [comment]
But documentation says , that isNull(x) must work:

http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/working-with-associations.html#filtering-collections

**Comment by waltertamboer** [comment]
I can confirm that this is happening. I'm also experiencing this issue.

**Comment by oprokidnev** [comment]
Still happening in 2k19. 
In my case managed to solve by multiple collection transformation.
```php
        $this->collection->matching(
            \Doctrine\Common\Collections\Criteria::create()
        )->matching(
            \Doctrine\Common\Collections\Criteria::create()->where(
                \Doctrine\Common\Collections\Criteria::expr()->isNull('deletedAt')
            )
        )
```
Problem is with 
`\Doctrine\ORM\Persisters\Collection\ManyToManyPersister::expandCriteriaParameters`

It uses `SqlValueVisitor` that does not understand Comparison::EQ expression with null values.

**Comment by ThomasLabstep** [comment]
Still an issue.

ManyToMany + isNull Criteria is 100% not working.

Thx for the pointer to SqlValueVisitor.

I guess we need a little PR to add the use case to support isNull?

**Comment by astronati** [comment]
@beberlei news about this issue? @MatTheCat

**Comment by MatTheCat** [comment]
Well #10587 is open so maintainers will look at it when they’ll got time.
