### ISSUE TITLE
setMaxResults results different count with array and object hidration

### ISSUE THREAD

**Issue by mastir** [doctrine/orm#5766]
found strange bug in setMaxResults. thats part of my paginator code

```
$first = $count * ($page - 1);
$query
    ->setFirstResult($first)
    ->setMaxResults($count);
// debug($query->getSql()); LIMIT $count OFFSET = $first, all cool
if($as_array){
     $result = $query->getArrayResult();
} else {
     $result = $query->getResult();
}
```

lets say`$count=2; as_array=false;`
i've got only 1 item per page.

```
$page=1 | $result =[ id:1 ]
$page=2 | $result = [ id:2 ]
```

but if i use `$as_array=true` i've got it right

```
$page=1 | $result = [ id:1, id:2 ]
$page=2 | $result = [ id:3, id:4 ]
```

i cant update to latest master version now. This bug found on 
https://github.com/doctrine/doctrine2/commit/7f16e5bc512fab570b4ccf1bebf5412d53d1b0a0 (Jan 4)
i will return to this issue next weak to find out more, with latest version

**Comment by mastir** [comment]
This problem is related to oneToMany relations. "SELECT a FROM account LEFT JOIN a.profile p LEFT JOIN p.contacts" in this case limit counts contacts, not orders.

**Comment by ZaneCEO** [comment]
This is the expected behavior. It's discussed at length here: https://stackoverflow.com/a/50203939/1204976

I recommend this issue to be closed.
