### ISSUE TITLE
Simple query generates invalid SQL

### ISSUE THREAD

**Issue by martixy** [doctrine/orm#6122]
```PHP
$qbb->select('r')
    ->from('AppBundle:ProductArchive', 'r')
    ->where("r.created >= :date")
    ->setParameter('date', new \DateTime('-1 day'));
$query = $qbb->getQuery();
dump($query->getSQL());
```
Should be quite straightforward, no?
Guess not.

Generated SQL:
```SQL
SELECT d0_.id AS id_0, d0_.created AS created_1, d0_.updated AS updated_2, d0_.raw_name AS raw_name_3, d0_.buy_price AS buy_price_4, d0_.buy_price_currency AS buy_price_currency_5 FROM dp_products_archive d1_ WHERE d1_.created >= ?
```
...`with params ["2016-11-07 03:24:19"]`

Notice how it named the table vs which table it tries to reference.
It works if I manually enumerate all the fields, but then it doesn't yield an object, but an array instead.
Might this have something to do with the fact that this entity is the child of another entity?

Perhaps of note is also that this is the only table in that database that is on TokuDB instead of InnoDB, but what relevance that could possibly have, I couldn't begin to guess.

ORM version = 2.5.5-DEV

Not sure what further information might be useful, but I can reliably replicate the behaviour, so supplying it shouldn't be a problem.

**Comment by Ocramius** [comment]
Can you also show the mapping/entity please?

**Comment by pashukhin** [comment]
Same problem. I did investigation about it, and I can say that's not depends on mappings. It happens because code at https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Persisters/Collection/ManyToManyPersister.php#L259 and below generates incorrect sql expression. In fact, it skips any logical operators and changes all comparisions to equalities.

**Comment by Ocramius** [comment]
@pashukhin can you write a test against https://github.com/doctrine/doctrine2/tree/d3f6c5ec70aac4b029a4b61ecf1e2ba61a1a4a6d/tests/Doctrine/Tests/ORM/Functional/Ticket ? (see that dir for examples)

**Comment by pashukhin** [comment]
Ok, I'll try to do it today
