### ISSUE TITLE
Default values for JoinColumn->referencedColumnName

### ISSUE THREAD

**Issue by tobias-trozowski** [doctrine/orm#6184]
Hi guys,

not sure if this is an technical issue or just outdated documentation...

In http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/annotations-reference.html#annref-joincolumn the documentation says
> If it is not specified the attributes name and referencedColumnName are inferred from the table and primary key names.

So a annotation like this seems totally valid to me:
```php
class Entity {
/**
 * @ORM\ManyToOne(targetEntity="Foo\Bar\Entity\Customer", fetch="LAZY")
 * @ORM\JoinColumn(name="created_by", nullable=true)
 * @var \Foo\Bar\Entity\Customer
 */
protected $createdBy;
}
```
At this point i would expect doctrine to figure out which is the primary key of the Customer entity is and resolve everything correctly.
But, sadly it doesn't.
When validating the mapping via command line i got the following error:
```
The referenced column name 'id' has to be a primary key column on the target entity class 'Foo\Bar\Entity\Customer'.
```

In Annotation Mapping documentation (http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/association-mapping.html#mapping-defaults) the behaviour is described completely different than in the first document but exactly the way it really works.

> The referencedColumnName always defaults to “id”, just as in one-to-one or many-to-one mappings.

So, is the first document outdated or is it a bug and the second document is outdated?

**Comment by Ocramius** [comment]
This is either to be fixed in the docs or in the mapping drivers.

Will surely not be inferred from the DB though.

**Comment by tobias-trozowski** [comment]
@Ocramius any hint where to start from to fix this issue?

**Comment by Ocramius** [comment]
@tobias-trozowski writing a test first - see https://github.com/doctrine/doctrine2/tree/7bb02d0dbdc337f98fa94078985baa713c24bb65/tests/Doctrine/Tests/ORM/Functional/Ticket for examples.

**Comment by MatTheCat** [comment]
Just hit this one. From a DX point of view column names should be mapped automatically; don't know if it's possible though.
