### ISSUE TITLE
Use ORMInvalidArgumentException::entityNotManaged($entity) in UnitOfWork::computeSingleEntityChangeSet()

### ISSUE THREAD

**Issue by Aerendir** [doctrine/orm#6315]
At [line 475](https://github.com/doctrine/doctrine2/blob/v2.5.6/lib/Doctrine/ORM/UnitOfWork.php#L475) is thrown a generic `\InvalidArgumentException()`.

As Doctrine provides a dedicated `ORMInvalidArgumentException::entityNotManaged($entity)` is better to use this so the exception can be caught.

Currently I need to catch the exception at that line, but only if it comes from Doctrine and I can't as the generic PHP exception is used.

**Comment by Ocramius** [comment]
@Aerendir dye ti BC concerns, it needs to still extend `InvalidArgumentException` though.
