### ISSUE TITLE
Embeddable  with notify change tracking policy do not update

### ISSUE THREAD

**Issue by YaoOcelotl** [doctrine/orm#6380]
Changes to embedded objects are not detected when using notify change tracking policy.

**Comment by Ocramius** [comment]
That's because changes happen at entity level, not at embeddable level.

**Comment by YaoOcelotl** [comment]
¿ Is it posible to use embedded objects and notify change tracking policy simultaneously?

**Comment by Ocramius** [comment]
@YaoOcelotl yes, by adding the policy to each entity that uses the embeddable object

**Comment by YaoOcelotl** [comment]
¿ Then how do we register the the changes in the embedded object in the parent entity ?

**Comment by Ocramius** [comment]
You'd have to do that when calling the API on the entity, not on the embeddable. No way around it, or else just use the implicit tracking strategy.

**Comment by YaoOcelotl** [comment]
The following calls do not work: 
`$listener->propertyChanged($entity, $embeddedPath, $oldEmbeddedClone, $newEmbeddedClone);`
`$listener->propertyChanged($entity, "{$embeddedPath}.{$property}", $oldValue, $newValue);`

**Comment by beberlei** [comment]
I am not sure change tracking policy makes sense, as its too fiddly and there aren't actually performance gains over using deferred explicit. As such I am closing the issue as further research is mood.
