### ISSUE TITLE
Exception in `IdentifierFlattener::flattenIdentifier` - column name used instead of field name in identifier extraction

### ISSUE THREAD

**Issue by tobiasstadler** [doctrine/orm#6393]
Consider the following two entities:
```
class A
{
    /**
     * @Id 
     **/
    private $id;

    private $something;

    /**
     * @Version
     */
    private $version;
};

class B
{
	/**
	 * @Id
	 * @ManyToOne(targetEntity="A")
	 * @JoinColumn(name="aid", referencedColumnName="id)
	 */
	private $A
	
	private $something;
	
	/**
	 * @Version
	 */
	private $version
}
````

I get an Exception in IdentifierFlattener::flattenIdentifier called from BasicEntityPersister::fetchVersionValue because. BasicEntityPersister::fetchVersionValue calls IdentifierFlattener::flattenIdentifier with the identifier field name, but IdentifierFlattener::flattenIdentifier  expects the identifier column names.

**Comment by Ocramius** [comment]
That should probably be changed to field names everywhere...
