### ISSUE TITLE
Wrong insert SQL command order

### ISSUE THREAD

**Issue by Arkemlar** [doctrine/orm#6409]
The schema has following structure:
User `<--Join Inheritance--` Store `<--OneToMany/ManyToOne--` Stock ` --ManyToOne/undirectional-->` Address.
Right insert order is: User, Store, Address, Stock
But doctrine tries to insert objects in this order: Address, Stock, etc. In Stock insertion SQL command fails because `store_id` is NOT NULL field.
It seems like it doesn't take into account that Stock's `store_id` field  has NOT NULL flag so Store should be created before Stock.

**Comment by Ocramius** [comment]
A test case is needed here.

**Comment by beberlei** [comment]
Maybe related to #8349 and all its previous issues. Closing due to lack of details.
