### ISSUE TITLE
persist reordered associations changes wrong entity

### ISSUE THREAD

**Issue by PlamenVasilev** [doctrine/orm#6415]
I have OneToMany relation User -> Group

The User is OneToMany `mappedBy="", cascade={"persist", "remove","merge"}`
The Group is ManyToOne `inversedBy=""`

I have the following association when I gen my entity

```
$user['group'][0] = array(id=>1, name => 'group1' );
$user['group'][1] = array(id=>3, name => 'group3' );
```

When I submit a form trough Symfony (I use collection type) and I send the related entities in reversed order;

```
$user['group'][0] = array(id=>3, name => 'group3 - edit' );
$user['group'][1] = array(id=>1, name => 'group1' );
```

The form is handling the request correctly and build the entity as it should, but when I try to persist the User entity the group with ID 1 is changed with the name of group with ID 3
`update group set name = 'group3 - edit' where id = 1`

This is because doctrine loops trough the new entity where the first entity has name changed. then from the old entity gets the first association in the list which is with ID 1 and updates the name with the name of ID 3.

I have tried to put `indexBy` but it is not working
How can this be fixed ?
How I can tell doctrine to match the entities by ID instead of array index ?

**Comment by lcobucci** [comment]
@PlamenVasilev persist ordering has been refactored on `2.6.x-dev` can you check if everything works with that development version?

**Comment by PlamenVasilev** [comment]
I have checked this issue with the latest dev-master of doctrine ORM/DBAL and the issue still exists

**Comment by beberlei** [comment]
This is a bug in Symfony Form then. It changes the values on the wrong entities. How it comes to the mapping based on the request is configurable in Symfony Forms and a difficult issue on their end.
