### ISSUE TITLE
oneToMany orphanRemoval without cascade remove

### ISSUE THREAD

**Issue by poolerMF** [doctrine/orm#6431]
ClassMetadataInfo.php -> function _validateAndCompleteOneToManyMapping

if I set orphanRemoval= true and remove is not in cascade, then doctrine will automatically set remove into cascade

I think those are two different functions (orphanRemoval and cascade delete) and they should not be affected together ... what do you think ? or am I wrong ?

**Comment by szymach** [comment]
This makes sense, since if you remove a parent, all children become orphans by default and should be removed with `orphanRemoval: true`. I would say there is an overlap with these two options, but certainly it works as it is suppose to.

**Comment by beberlei** [comment]
In case of `OneToMany` the assumption is that the entity is the *only owner*, meaning that these entities become orphans. Its not a Many To Many association, assuming that any entity might have "many" relations.

**Comment by poolerMF** [comment]
@brabeji I think you forgot about nullable=true in ManyToOne
now it's not possible to use orphanRemoval=true and cascadeDelete=false

it's 3 years old issue and I think nobody want to change something, so rather you close issue
can someone else look at this issue ?

**Comment by brabeji** [comment]
@poolerMF Looks like you've tagged an incorrect person ✌️
