### ISSUE TITLE
Multiple DiscriminatorColumn with SINGLE_TABLE

### ISSUE THREAD

**Issue by Seb33300** [doctrine/orm#6447]
I would like to use a discriminator map on multiple fields of my entity but it seems to not be possible.

So I tried to make a discriminator map on multiple levels with Entity inheritance:

```php
/**
 * Task
 *
 * @ORM\Entity
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({
 *     "type1" = "Type1",
 *     "type1" = "Type2"
 * })
 */
class Task
{
    // ...
}

/**
 * TaskType1
 *
 * @ORM\Entity
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="subtype", type="string")
 * @ORM\DiscriminatorMap({
 *     "subtype1" = "TaskType1Subtype1"
 * })
 */
class TaskType1 extends Task
{
    // ...
}

/**
 * Type1Subtype1
 *
 * @ORM\Entity
 */
class TaskType1Subtype1 extends TaskType1
{
    // ...
}
```

When creating a query to get `TaskType1Subtype1` entities, this will result in:
```sql
SELECT ... FROM Task WHERE subtype IN ('type1', 'subtype1')
```
instead of
```sql
SELECT ... FROM Task WHERE type IN ('type1') AND subtype IN ('subtype1')
```

**Comment by Ocramius** [comment]
Mixed inheritance is not supported, and only one discriminator column will ever be considered with the current codebase (that's hardcoded).

What is the use-case?

**Comment by Seb33300** [comment]
I have a task table with `type` and `subtype` columns.
Depending on their 2 columns, I need to load a different entity.

Depending on his type and subtype, the task will have different columns (stored in a json column).
I have made something custom to automatically map the data from the json column to the entity properties.

**Comment by Ocramius** [comment]
Yeah, that will not work. What you can do (depending on how advanced your RDBMS is) is creating a read-write view with the discriminator column being a concatenation of the discriminators.

**Comment by Seb33300** [comment]
But doctrine will try to INSERT in the concatenation column which will result in an error.

**Comment by Ocramius** [comment]
That's typically hijacked with rw views by replacing the insert value and splitting it over two columns, much like with table partitioning strategies.

**Comment by Seb33300** [comment]
I am not sure to be able to do that on the database side.

Any chance to do that by adding a listener on the doctrine INSERT to manually split the discriminator field and remove it from the query?

(I am using doctrine with Symfony)

**Comment by Ocramius** [comment]
No, that's not going to be possible

**Comment by lcobucci** [comment]
Closing as `Won't fix` as per @Ocramius comments.
