### ISSUE TITLE
Persisting entities with OneToOne and OneToMany/ManyToOne relationship between them.

### ISSUE THREAD

**Issue by Frikkle** [doctrine/orm#6499]
Last week I encountered an issue in one of our projects where we had two entities, call them A and B having a unidirectional OneToOne A->B (with the join column not nullable) and a OneToMany(A->B)/ManyToOne(B->A) bidirectional relationship between them.

The problem lies in the order of persisting them; when first persisting A, then B, a constraint violation is thrown: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: a.b_id, indicating that the join column isn't allowed to be NULL, even though it should have been set.

I reworked my code to a minimal example:

**Entity A**
```php
/**
 * Class A
 * @ORM\Entity()
 */
class A
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(name="id", type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\B", mappedBy="a", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $bs;

    /**
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\B", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $b;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return B[]|ArrayCollection
     */
    public function getBs()
    {
        return $this->bs;
    }

    /**
     * @param B $b
     */
    public function addB(B $b)
    {
        if ($this->bs->contains($b)) return;

        $this->bs->add($b);

        // Update owning side
        $b->setA($this);
    }

    /**
     * @param B $b
     */
    public function removeB(B $b)
    {
        if (!$this->bs->contains($b)) return;

        $this->bs->removeElement($b);

        // Not updating owning side due to orphan removal
    }

    /**
     * @return B
     */
    public function getB()
    {
        return $this->b;
    }

    /**
     * @param B $b
     */
    public function setB(B $b)
    {
        $this->b = $b;
    }
}
```

**Entity B**
```php
/**
 * Class B
 * @ORM\Entity()
 */
class B
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(name="id", type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\A", inversedBy="bs", cascade={"persist"})
     */
    private $a;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return A
     */
    public function getA()
    {
        return $this->a;
    }

    /**
     * @param A $a
     */
    public function setA(A $a)
    {
        $this->a = $a;
    }
}
```

**My persist code**
```php
$a = new A();
$entityManager->persist($a);

$b = new B();
$a->setB($b);
$entityManager->persist($b);

$entityManager->flush();
```

The code above throws the constraint violation error. At first I thought it might be related to circular cascade persists. But if I remove all cascade annotation and the orphanRemoval clauses as well, it still throws the ConstraintViolationException.  

**What does work?**  
It does however seem to work when I revert the persist order, like this:
```php
$a = new A();
$b = new B();
$a->setB($b);

$entityManager->persist($b);
$entityManager->persist($a);

$entityManager->flush();
```

And, it also works when wrapping the whole operation in a transaction. But somehow I have the feeling that it should work.

**Possibly related issues**
When looking through the issue list I came across #4090 which seems to be a similar issue. Maybe this helps to shine light on that as well?

**Our environment**
We're working in Symfony 2.8 LTS using the `doctrine/doctrine-bundle` version `1.6.4` and `doctrine/orm` version `2.5.5`. After upgradring both of them to the latest version, the problem persisted.

**Comment by lcobucci** [comment]
@triasinformatica-gabe could you check if this issue happens on `master`? Commit order has been fixed after a major refactoring and probably solves this issue.

**Comment by triasinformatica-gabe** [comment]
@lcobucci I will check this later today and get back to you with the findings. Thansk for the reply.

**Comment by lcobucci** [comment]
@triasinformatica-gabe awesome! Please keep in mind that dependencies versions for `v2.6` (`master`) have been bumped up (PHP and packages).

**Comment by triasinformatica-gabe** [comment]
@lcobucci I've just tested the minimal example against `^2.6`/`master` and the issue still occurs.

In order to help pinpoint the issue I've created a repository with the minimal example (Symfony 2.8.*, DoctrineBundle, Doctrine and PHPUnit). I added the example entities A and B mentioned above as well as two simple PHPUnit tests indicating the problematic scenario.

Setting it up would be a matter of running the following commands, given you have a database connection set-up:
```bash
> composer install
> php app/console doctrine:schema:update --force
> phpunit -c app/
```
If there's anything else I can do to contribute to this, please let me know.

**Comment by lcobucci** [comment]
@triasinformatica-gabe what would really helps us is a PR with that failing test. Could you please send it?

You can find examples on https://github.com/doctrine/doctrine2/tree/388afb46d0cb3ed0c51332e8df0de9e942c2690b/tests/Doctrine/Tests/ORM/Functional/Ticket

**Comment by triasinformatica-gabe** [comment]
@lcobucci Sure, I'll look into it for you.

**Comment by triasinformatica-gabe** [comment]
@lcobucci I created PR #6533 as per your request. I also found the cause of the issue and provided a fix. It seems like a logic error that resulted from code optimization.

**Comment by Ocramius** [comment]
The patch related to this was reverted, as foreign key integrity issues occur when dealing with deletes.

This needs additional testing and inspection.

**Comment by dompie** [comment]
This is still an issue. Is someone willing to fix it for money?

**Comment by rvanlaak** [comment]
@lcobucci would PR #8703 prove whether the persistence ordering works correctly?
