### ISSUE TITLE
Legacy maintainer should be deprecated

### ISSUE THREAD

**Issue by DaveRandom** [doctrine/orm#6641]
The @Ocramius module is really starting to show it's age, can we please simply wish it a happy birthday and retire it?

**Comment by PeeHaa** [comment]
Inb4 EWONTFIX old-by-design

**Comment by Ocramius** [comment]
I'd say that the old model needs to be kept for BC compliance: newer models tend to introduce regressions too quickly. Maybe slowly transition to newer implementations?
