### ISSUE TITLE
ReadOnly and changeTrackingPolicy could not be set on embeddable

### ISSUE THREAD

**Issue by sserbin** [doctrine/orm#6711]
Pretty much what the subject says.

While I realize this is something that unlikely gets fixed, partially because this is 0.05% case, partially because readOnly is [going to be removed in 3.x](https://github.com/doctrine/doctrine2/pull/5728#issuecomment-226225047), I'd like to get some feedback nevertheless. 

The use case is the date range embeddable (`DateTime start`, `DateTime end`, `DateTimeZone tz`)
Because the `DateTime` objects are not constructed properly(with the proper timezone) upon loading from database, they need to be re-constructed (meaning properties of embeddable get re-set) which, in turn, marks the embeddable as dirty in UoW.

Because there's no way to unmark the object as dirty in UoW (or I didn't find it) and `readOnly`/`changeTrackingPolicy=notify` are not supported by embeddables - there doesn't seem to be a way to workaround this problem. (a custom doctrine type would not suffice as well because it's only 1-1 mapping and doesn't allow to map a single object into multiple table columns, and vice versa)

Is there some other workaround I've overlooked?

Thanks

**Comment by Ocramius** [comment]
Embeddable is not tracked on its own, but as part of its parent entity, so
I don't think anything should be done for the lifecycle of embeddable
objects, as they don't have their own lifecycle at all.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by beberlei** [comment]
@sserbin I believe you can hide this behind the Embeddables state by adding unmapped properties:

```php
class Date
{
    /** @ORM\Column(type="string") */
    private $date;
    /** @ORM\Column(type="string") */
    private $tz;
    /** not mapped **/
    private $datetime;

    public function getDateTime()
    {
        if ($this->datetime === null) {
             $this->datetime = new DateTime($this->date, new DateTimeZone($this->tz));
        }
        return $this->datetime;
    }
}
```
