### ISSUE TITLE
Unique constraint on join table

### ISSUE THREAD

**Issue by greg0ire** [doctrine/orm#6726]
I have a one-to-many with join table unidirectional relationship because I try to avoid bidirectional relationships, and can't seem to find a way to add a unique constraint on my join table: I'm using a composite key to reference the "many" side, and right now I cannot find a way to prevent the insertion of a composite primary key twice.

I tried adding a `unique-constraints` mapping under `join-table`, but it seems to be ignored (deliberate typos makes nothing crash), and [the xsd validation shows this is not supported](https://github.com/doctrine/doctrine2/blob/master/doctrine-mapping.xsd).

**Comment by lcobucci** [comment]
@greg0ire isn't this solved by using the "unique" attribute on the join-column?

**Comment by greg0ire** [comment]
It's a composite key, so there are several join non unique columns, and there should be a unique index on those

**Comment by lcobucci** [comment]
@greg0ire got it, I've missed that detail. It's indeed not supported AFAIK but, since the mapping is being completely refactored on v3 by @guilhermeblanco I think it makes sense to add this as a feature request for that version...

**Comment by OmegaZero** [comment]
Was this added?  And if so how to do you implement the composite unique index on the join table?

Thanks!

**Comment by beberlei** [comment]
This is not supported by ORM Schema functionality, the index should be created outside of Doctrine.
