### ISSUE TITLE
findAll(), findBy() and findOneBy() do not take care about query hints

### ISSUE THREAD

**Issue by steevanb** [doctrine/orm#6751]
Hi :)

When i define default hints, with this code :
`$manager->getConfiguration()->setDefaultQueryHint(QueryHint::MY_HINT, true);`

This methods don't pass it to `EntityPersister::load()` or `EntityPersister::loadAll()`, although `load()` has a parameters for that : `$hints`.

So, magic methods in `EntityRepository` could not be used, when we have default hints :(

**Comment by lcobucci** [comment]
@steevanb could you please send us a failing test case that reproduces that behaviour? It would help us a lot to identify and fix the issue you're describing.

You can find examples on https://github.com/doctrine/doctrine2/tree/388afb46d0cb3ed0c51332e8df0de9e942c2690b/tests/Doctrine/Tests/ORM/Functional/Ticket

**Comment by althaus** [comment]
Issue is related to this PR: https://github.com/doctrine/doctrine2/pull/863

The hints are only injected in the AbstractQuery class, but this isn't used at all by the EntityManager/EntityPersister used by the EntityRepository as it's building its SQL without the Query class. 

It's just calling stuff like `return $persister->load($sortedId, null, null, array(), $lockMode);` where `array()` is the value for $hints.

**Comment by steevanb** [comment]
3 years after, i see bug is already here ;)

I've created this little repository to show you the problem:
https://github.com/steevanb/doctrine-repository-hint-bug

**Comment by beberlei** [comment]
This is expected behavior, because EntityRepository does not use DQL queries internally. I believe this is documented. the hints are not to be used for own things unless you evaluate them in an SQL Walker (See custom sql walker docs).

**Comment by martinlipp** [comment]
@beberlei Are there any technical reasons why `EntityPersister::load()` is not using DQL queries? As far as I can tell, it is a pretty common use case to lazy load nested (ManyToOne) properties with `EntityPersister::load()` (isn't that even an Doctrine internal feature?). Therefore it would be great and more consistent to factor in default hints in those queries too.
I could try to create a pull request, if someone could confirm, that it should be possible to transform BasicEntityPersister queries to DQL.

**Comment by beberlei** [comment]
DQL needs parsing and that has non negligible overhead and caching implications.
