### ISSUE TITLE
[Documentation] Document DQL built-in functions

### ISSUE THREAD

**Issue by OJezu** [doctrine/orm#6782]
As far as I know, there is no list of functions that are built in into DQL in documentation. I think at least there should be link to repo directory with the classes.

I was looking a while for documentation whether ANSI MySQL `POSITION` is available. I've already implemented it as custom function, and only then I looked at code to find it already is there under MySQL `LOCATE` name. Documentation with list of functions, their parameters and return values would be nice, but as I said, the link to repo code would be a start:

https://github.com/doctrine/doctrine2/tree/master/lib/Doctrine/ORM/Query/AST/Functions

**Comment by Majkl578** [comment]
There is already a list of built-in functions under [the EBNF section of the DQL chapter](https://github.com/doctrine/doctrine2/blob/v2.5.13/docs/en/reference/dql-doctrine-query-language.rst#functions-1), but without further description.
Consider sending a PR if you want to speed things up.
