### ISSUE TITLE
[Documentation] 14.7.1. Query Result Formats

### ISSUE THREAD

**Issue by Mynyx** [doctrine/orm#6793]
At "Query#getOneOrNullResult()" the sentence "If the result contains more than one object, an NonUniqueResultException is thrown." is missing.

**Comment by lcobucci** [comment]
@Mynyx could you please send us a PR suggesting a fix?

**Comment by Mynyx** [comment]
@naitsirch Many thanks for the PR.

Could somebody approve it?

**Comment by lcobucci** [comment]
Handled by https://github.com/doctrine/orm/pull/7443
