### ISSUE TITLE
Doctrine very slow select with many left join

### ISSUE THREAD

**Issue by averichev** [doctrine/orm#6836]
Doctrine very long time (126.04 ms) makes a query and returns data if query contains select with many (6) LEFT JOIN and returned many data (more when 1200 rows)

My query:

https://gist.github.com/Neokortex/218463a50f57529d6e0caf9b82fc4aa9

A week ago I did not notice this. Why does this happen?

UPDATE: indexes do not help.

The server is very powerful

Intel (R) Xeon (R) CPU E3-1230 v5 @ 3.40GHz, 8 cores

32 GB Memory

I CRY :(

**Comment by Ocramius** [comment]
Seems like a typical hydration issue. See https://ocramius.github.io/blog/doctrine-orm-optimization-hydration/

**Comment by naitsirch** [comment]
@Ocramius since there is no feedback, this issue may be closed?

**Comment by beberlei** [comment]
Its not clear if the query is slow or the hydration. This is not a joined table inheritance scenario here, but it seems fetch=eager is used on all ManyToOne. However you should set joinColumn to not nullable to get INNER JOINs if that makes a difference.

If its not the query that is slow but hydration, then the solution is not to fetch join so many things.
