### ISSUE TITLE
Lifecycle callbacks on embeddables, possible or not?

### ISSUE THREAD

**Issue by holtkamp** [doctrine/orm#6855]
Encountered behaviour where embeddables seem not to respect lifecycle callbacks, but do "listen" to a given configuration, as also [described here](https://groups.google.com/forum/#!topic/doctrine-user/g2_vurFHEMM).

The [documentation](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/events.html#lifecycle-callbacks) does not mention embeddables, so I suppose it is not supported. If so: might be good to document this more explicitly?

The strange thing: when defining a lifecycle callback that points to a non-existing function: an exception is thrown, so the definition *is* respected.

**Comment by Ocramius** [comment]
Not possible: an embeddable has no lifecycle on its own. The lifecycle is
the one of the entity.

**Comment by holtkamp** [comment]
Wow, < 1 minute response time, raspact!

Should I submit a PR for the documentation on the Entity LifeCycle to explicitly indicated this will not work for embeddables? Or... is that too much ;). Maybe others have the same "use case".

**Comment by Ocramius** [comment]
Sending a PR to the docs would be fab!

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by holtkamp** [comment]
This behaviour is also discussed in https://github.com/doctrine/doctrine2/issues/4568, and can maybe be covered using https://packagist.org/packages/tarifhaus/doctrine-nullable-embeddable
