### ISSUE TITLE
addJoinedEntityResult does not seem to work with oneToMany/manyToOne

### ISSUE THREAD

**Issue by yurtesen** [doctrine/orm#6875]
I am using symfony 3.4.1, with doctrine/orm 2.5.13. I have 2 tables. `store` and `store_product`. 

In `Store` entity I have:

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Store\Product", mappedBy="store")
     * @ORM\JoinColumn(name="store_id")
     */
    private $products;

and in `Store\Product` entity I have composite index with (store_id,product_id). I have:

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Store", inversedBy="products")
     * @ORM\JoinColumn(name="store_id",referencedColumnName="id",nullable=false,onDelete="CASCADE")
     * @ORM\Id()
     * @ORM\GeneratedValue("NONE")
     * @var $store \AppBundle\Entity\Store
     */
    protected $store;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Product", inversedBy="stores")
     * @ORM\JoinColumn(name="product_id",referencedColumnName="id",nullable=false,onDelete="CASCADE")
     * @ORM\Id()
     * @ORM\GeneratedValue("NONE")
     * @var $product \AppBundle\Entity\Product
     */
    protected $product;

Earlier I produced a native query using the [guide][1]. It was only fetching entries from `store` table and it worked perfectly.

Now I am trying to join `store_product` table and it is not going so well. I am using the following query which returns 1 result.

`SELECT st.id, st.name, stp.store_id, stp.product_id stp.price FROM store st LEFT JOIN store_product stp ON st.id = stp.store_id WHERE st.id=1 LIMIT 1;`

returns something like:

     id |    name    | store_id | product_id | price 
    ----+------------+----------+------------+-------
      1 | Store Name |        1 | 1234567890 |   129

I setup the result set mapping as follows:

        $rsm = new ResultSetMapping();
                $rsm->addEntityResult('AppBundle\Entity\Store', 'st');
                $rsm->addFieldResult('st', 'id', 'id');
                $rsm->addFieldResult('st', 'name', 'name');
                $rsm->addJoinedEntityResult('AppBundle\Entity\Store\Product', 'stp',
        'st', 'products');
                $rsm->addFieldResult('stp','store_id', 'store');
                $rsm->addFieldResult('stp','product_id','product');
                $rsm->addFieldResult('stp','price','price');

I am getting error: `Notice: Undefined index: store` Can anybody see the reason of the error?

  [1]: http://docs.doctrine-project.org/en/latest/reference/native-sql.html

**Comment by lcobucci** [comment]
@yurtesen could you please send us a failing test case that reproduces that behaviour? It would help us a lot to identify and fix the issue you're describing.

You can find examples on https://github.com/doctrine/doctrine2/tree/388afb46d0cb3ed0c51332e8df0de9e942c2690b/tests/Doctrine/Tests/ORM/Functional/Ticket

**Comment by yurtesen** [comment]
@lcobucci unfortunately I don't have time to reverse engineer how make new tests from examples. I can barely use doctrine yet. I hope somebody else can create a test case. I can try to come back to this if I have time, time to learn how to create tests, and maybe if somebody makes a documentation about tests.

But if you expect/need people to create test cases. I believe somebody should make documentation about how to create tests with extreme detail so even people who never used doctrine can create a test case.  

Perhaps you probably wouldn't use a package/code if you had to reverse engineer it. For example, if it's developers tell you "here is example code, look at it to learn and use our software" 😄

**Comment by yurtesen** [comment]
I think the problem was that I needed to use `addMetaResult` ... I don't know how I missed that, a better example in documentation could have helped...

This seems to work I think....
```
            $rsm->addFieldResult('stp', 'price', 'price');
            $rsm->addJoinedEntityResult('AppBundle\Entity\Store\Product', 'stp', 'st', 'products');
            $rsm->addMetaResult('stp', 'store_id', 'store_id', true);
            $rsm->addMetaResult('stp', 'product_id', 'product_id', true);
```
