### ISSUE TITLE
[Question] Optimistic Locking behaviour for dirty entities

### ISSUE THREAD

**Issue by tavlima** [doctrine/orm#6980]
I was surprised to see that `Doctrine\ORM\EntityManager::find` is able to find an entity matching the `lockVersion` constraint, even when the changes were not persisted yet.

```
$user_v1 = $em->find(User:class, 1, LockMode::OPTIMISTIC, 1);
$user_v1->setVersion(2);

// I'd expect this next line to throw an OptimisticLockException, given there were no flushes in the between...
$user_v2 = $em->find(User:class, 1, LockMode::OPTIMISTIC, 2);
```

I get that the `find` is optimised to check the identity map first, before hitting the database, but is there a reason do that even when explicitly locking?

Couldn't we check if the identity mapped entity is not dirty and, only in that case, return from there and correctly short-circuit the DB query? I really think the current behaviour can be misleading in some scenarios...

**Comment by beberlei** [comment]
But the entity manager is responsible for the entity and it has it in version 2. I think this behavior is correct.
