### ISSUE TITLE
[Question ] Any native way to achieve this?

### ISSUE THREAD

**Issue by kanonhian** [doctrine/orm#6994]
Very often I have to do this `findBy(array('criteria'=> $someObject) `where $someObject is a prepopulated object. My question is: is there a built in function that given the $someObject id and his entity type fetch him from database and then executes the findBy from above??? Something like this:
```
    public function findByDiscriminator($slave, $idSlave, $discriminator, $discriminatorCriteria)
    {
        $slaveManager = $this->container->get('doctrine')->getRepository("AplicacionBaseBundle:$slave");
        $slaveEntity = $slaveManager->find($idSlave);
        return $this->findAllByCriteria(array($discriminatorCriteria => $slaveEntity), 0, 0, $discriminator);
    }

    public function findAllByCriteria($criteria, $limit = 0, $offset = 0, $repository)
    {
        $total = $limit * $offset;
        $start = $limit * ($offset - 1);
        $spamManager = $this->container->get('doctrine')->getRepository("AplicacionBaseBundle:$repository");
        $spam = $spamManager->findBy($criteria, array(), $total != 0 ? $total : null, $start != 0 ? $start : null);
        return $spam;
    }

```
If, lets say, I need to fetch al groceries whose supplier id is 456  I'd query like this
`DAO->findByDiscriminator('SupplierEntity', 456, 'GroceryEntity', 'supplier')`//assuming there is a field in GroceryEntity named supplier.

**Comment by aoga88** [comment]
@kanonhian  did you get to any solution on this? I'm on the same issue

**Comment by beberlei** [comment]
I am not sure I understand correctly, but its already possible to load by association and pass an object:

```
$user = $userRepository->find($id);
$blogPost = $blogPostRepository->findOneBy(['author' => $user]);
```
