### ISSUE TITLE
[meta] Port DQL Parser to Hoa\Compiler

### ISSUE THREAD

**Issue by Majkl578** [doctrine/orm#7017]
Tracking issue for porting the parser to [Hoa\Compiler](https://github.com/hoaproject/Compiler/).

Related discussions:
- https://github.com/doctrine/doctrine2/issues/6211#issuecomment-291271881
- #5656

Related issues:
- #6278

Related PRs:
- #6709
- #6574
- #6944

**Comment by fesor** [comment]
Is there any short-term plans for this or I, for example, could work on prototype?

**Comment by Majkl578** [comment]
I was already [playing with PP language definiton](https://github.com/Majkl578/doctrine2/blob/dev/query-hoa/lib/Doctrine/ORM/Query/language.pp) and have a WIP Visitor locally, but haven't got much further yet. I don't want to introduce huge refactorings here and there (it may affect anything from the parser itself to the hydration process) at least until Mapping rewrite is a bit more finalized.

**Comment by Ocramius** [comment]
The reason why this is so slow is because our current parser depends on the classmetadata, so it is not just a parser, but also takes decisions based on what class metadata mappings look like. I think we should change that 👍

**Comment by beberlei** [comment]
Hoa is now unmaintained.
