### ISSUE TITLE
Object could not be converted to string after upgrade to 2.6.0

### ISSUE THREAD

**Issue by pepakriz** [doctrine/orm#7025]
Hi,

After upgrade to 2.6.0 I got `Object could not be converted to string after upgrade to 2.6.0`.

Mybe because this PR: https://github.com/doctrine/doctrine2/pull/6141 . Now custom types must implement `__toString` method when they are used as discriminators. Is this behaviour correct?

**Comment by Ocramius** [comment]
@pepakriz discriminators didn't support `object` values before `2.6`

**Comment by pepakriz** [comment]
Maybe not officially, but it works on my code (version 2.5.14) without __toString :)

**Comment by Ocramius** [comment]
In a reproducible way? Can you compare your code to the one in #6141 and see if there are any major differences?

**Comment by lcobucci** [comment]
Closing here due to inactivity, we can reopen once we have a way to reproduce it.
