### ISSUE TITLE
README.md typo?

### ISSUE THREAD

**Issue by Dadibom** [doctrine/orm#7073]
> Doctrine **3** is an object-relational mapper

**Comment by Ocramius** [comment]
@Dadibom consider sending a patch - Doctrine 3 is not yet released, so I expect that the change in the docs will propagate everywhere :)

**Comment by Dadibom** [comment]
Hm, what do you mean by sending a patch?
Ooh, you're working on doctrine 3? How compatible will it be with existing projects?

**Comment by Ocramius** [comment]
@Dadibom a lot changed - we have an [`UPGRADE.md`](https://github.com/doctrine/doctrine2/blob/09266d5361ef9c659c1f665eeefa3d3de0f4e64b/UPGRADE.md#upgrade-to-30) for that

**Comment by Dadibom** [comment]
Great, thanks :)

**Comment by Majkl578** [comment]
Bumping version in readme was my work in #6956, I think it is ok since master is now representing upcoming 3.0. Maybe the default branch here on GitHub could be set to 2.7 for now, but I wouldn't change the version in README.

**Comment by Seb33300** [comment]
What about
> Doctrine is an object-relational mapper...
