### ISSUE TITLE
Rename this repository to doctrine/orm

### ISSUE THREAD

**Issue by greg0ire** [doctrine/orm#7142]
From: https://help.github.com/articles/renaming-a-repository/

> When you rename a repository, all existing information, with the exception of Project Pages URLs, is automatically redirected to the new name

This means things should work just like before, but I think references should be replaced wherever possible (on packagist, for instance).

**Comment by Majkl578** [comment]
How does i.e. Packagist handle this?

**Comment by Ocramius** [comment]
It's transparent there, but @Seldaek told me to edit the package on packagist.org too after the rename, so we avoid redirect hops during downloads (and unforeseen issues there)

**Comment by Majkl578** [comment]
What else, Travis? AppVeyor? Scrutinizer?

**Comment by Ocramius** [comment]
The API calls are redirected too, so it's not a big deal. If we need to re-configure those it's not a big deal.

**Comment by Majkl578** [comment]
The repository has been renamed.
References updated in #7551 and #7552.
Travis and Scrutinizer have been updated too.
