### ISSUE TITLE
[request] option to only use SQL in dumped schema information

### ISSUE THREAD

**Issue by holtkamp** [doctrine/orm#7186]
Currently the dumped information of the [UpdateCommand](https://github.com/doctrine/doctrine2/blob/c4c59df1b4251f5030a08bd1253a0e472e4bdb7e/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/UpdateCommand.php#L87) also includes non-SQL text:

_"The following SQL statements will be executed:"_

Is there a specific reason to do this? We currently store the output in a .sql file, which can then be easily executed, for example when spinning up a Docker instance. But the generated SQL is now "invalid" due to the help text. 

Of course this text can be stripped after generation, but still, it feels awkward.

**Comment by Ocramius** [comment]
Good question, but a few problems arise: 

 1. changing this may break existing hacks. I don't mind that much, but it can really introduce problems
 2. the `dump` command is, as it says, to `dump` information, not to generate an actually usable SQL string. For that, using the diffing tools directly would be more appropriate.

**Comment by holtkamp** [comment]
> changing this may break existing hacks. I don't mind that much, but it can really introduce problems

True, also saw some commented "stripping" functionality in my scripts from the time [when the warnings were printed](https://github.com/doctrine/doctrine2/blob/c4c59df1b4251f5030a08bd1253a0e472e4bdb7e/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/UpdateCommand.php#L116-L119) in the beginning of the output, just re-activated that

 >the dump command is, as it says, to dump information, not to generate an actually usable SQL string. For that, using the diffing tools directly would be more appropriate.

Also true. Maye a dedicated Command is required to write the output to a SQL file...

I kind of triggered when I saw this warning is [not printed when being dumped / forced](https://github.com/doctrine/doctrine2/blob/c4c59df1b4251f5030a08bd1253a0e472e4bdb7e/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/UpdateCommand.php#L110-L112).

For now closing issue and stripping the first three lines from the outputted information.

**Comment by Nek-** [comment]
Both may be modifiy in this way. What do you think @Ocramius ?

**Comment by Ocramius** [comment]
Adding a flag that excludes all output and disables colors implicitly seems fine :+1:
