### ISSUE TITLE
Reference in markdown documentation is not being rendered in HTML

### ISSUE THREAD

**Issue by holtkamp** [doctrine/orm#7231]
In the documentation about [Events](https://github.com/doctrine/doctrine2/blob/master/docs/en/reference/events.rst), the following snippet is used:

```
:ref:`reference-events-implementing-listeners`
```
Not sure how to refer to lines in a .md file, so here is a screenshot:

<img width="710" alt="screen shot 2018-05-19 at 00 03 40" src="https://user-images.githubusercontent.com/776405/40259841-1df3d7d4-5af8-11e8-9da7-5bafe45add3c.png">

It seems that when being rendered on https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/events.html#lifecycle-events (the last block), no hyperlink is rendered..., again a screenshot:

<img width="918" alt="screen shot 2018-05-18 at 23 58 50" src="https://user-images.githubusercontent.com/776405/40259832-0e02602a-5af8-11e8-83f4-78febc86b68d.png">

Maybe I am missing something, but it seems during the compilation / build of the documentation this reference is not detected / respected?

**Comment by jwage** [comment]
There is no rst file named `reference-events-implementing-listeners.rst` in the docs folder that I could find. This might be a case of a file being renamed or removed and a reference wasn't updated.

**Comment by holtkamp** [comment]
So probably this section is referred to? https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/events.html#implementing-event-listeners

**Comment by holtkamp** [comment]
This seems now resolved => close issue. 

![Screenshot 2019-08-06 at 15 53 43](https://user-images.githubusercontent.com/776405/62545686-7a51d580-b862-11e9-81c5-f00d6f28349e.png)
