### ISSUE TITLE
Documentation of Concrete Inheritance

### ISSUE THREAD

**Issue by TerjeBr** [doctrine/orm#7371]
The documentation of Concrete Inheritance when you use one table per class seems to be missing.

I only figured out you could use InheritanceType TABLE_PER_CLASS by looking at the source code.

**Comment by TerjeBr** [comment]
https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Mapping/InheritanceType.php

I also found it mentioned at https://www.doctrine-project.org/api/orm/latest/Doctrine/ORM/Mapping/InheritanceType.html

**Comment by Ocramius** [comment]
Hmm, interesting, I think this is new and only in `master`, not yet
anywhere. I'll ask internally, because I don't remember merging anything
related to this feature...
Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by TerjeBr** [comment]
It seems to be a deprecated feature instead of a new feature. It was in doctrine 1, but the schema tool in doctrine 2 does not support it.

So, if it is not supported, my question becomes: How do you have Base class A and Child class C be two different entities with two separate tables, but C inherits a lot of its fields (and mappings) from A?

**Comment by TerjeBr** [comment]
I tried it out with no InheritanceType annotation in base class A, and the schema tool copied over all the normal table fields, but not the `@ManyToOne` relationships. Why is that?

**Comment by Ocramius** [comment]
That's what JTI does

**Comment by TerjeBr** [comment]
What is JTI?

**Comment by TerjeBr** [comment]
Do you mean CTI?
https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/inheritance-mapping.html#class-table-inheritance

**Comment by Ocramius** [comment]
Joined table inheritance - same group of constants

**Comment by TerjeBr** [comment]
But that joins the tables. I want two independent entities with no table joins.
All the columns that are the same in A and C should exist in both tables.

It is like A is a mapped super class for C, but also A is an entity on its own. Is that not possible?

**Comment by Ocramius** [comment]
Yep, it's called "Joined" table inheritance all over the codebase

**Comment by Ocramius** [comment]
No, that's not currently possible

**Comment by TerjeBr** [comment]
Why is that not possible? Would that be problematic in some ways?

**Comment by Ocramius** [comment]
It's just not implemented 😬

**Comment by TerjeBr** [comment]
Was there a reason you put in the restriction that a Mapped superclass could not also be an Entity?

**Comment by Ocramius** [comment]
Yes: a mapped superclass is alike to a trait in PHP: it's not supposed to
have concrete instances of its exact type at runtime, and it's only
supposed supposed to be abstract.

**Comment by Ocramius** [comment]
Yep, or you can help building the feature for 3.x :-)
Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by TerjeBr** [comment]
If I want this feature for 3.x, what would be the best way then?

Should I change Mapped Superclass to also allow it to be an entity?
Or should I introduce a new InheritanceType or try resurrect the InheritanceType TABLE_PER_CLASS?

**Comment by Ocramius** [comment]
I'd say pursuing the TABLE_PER_CLASS approach would be best - try getting
in touch with @guilhermeblanco first, as he's been pushing these changes
that you are looking at. Heck, it may even be that `master` already
supports some of this stuff.
Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by Pictor13** [comment]
Ping.
In the end was there anything on `master` that would allow this TABLE_PER_CLASS-like inheritance?

**Comment by MichaelKubovic** [comment]
hey @TerjeBr, how did you deal with the issue?

**Comment by TerjeBr** [comment]
I just went on with other things. Sorry.

**Comment by mpdude** [comment]
There is no "concrete table inheritance" implemented, and to my knowledge, nobody is trying to implement it.

I suggest we close this issue.
