### ISSUE TITLE
🥔 Should we keep rebasing 3.0?

### ISSUE THREAD

**Issue by guilhermeblanco** [doctrine/orm#7379]
@doctrine/doctrinecore Feel free to vote.

👍 For "Yes, continue"
👎 For "Stop, let's choose another alternative (ie. merge, cherry-pick)"

**Comment by lcobucci** [comment]
We now have [151 PRs targeting `master`](https://github.com/doctrine/doctrine2/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+base%3Amaster), [30 PRs targeting `2.6`](https://github.com/doctrine/doctrine2/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+base%3A2.6), and [8 PRs targeting `2.7`](https://github.com/doctrine/doctrine2/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+base%3A2.7).

I'm pretty sure most of the 151 are already outdated and need to be rebased, but even thought that's the situation I think we should strive to consider `master` as a stable branch as much as possible.

With the current state of the repo, it's way easier to port a bugfix forward to `master` than keep it rebasing it.

**Comment by SenseException** [comment]
What @Majkl578 says is especially interesting for documentation, that needs to be changed on multiple branches. Currently 2.6 - 3.0, in case changes affects all those versions. We have outdated information in the docs that should get focus like #7374 and #7385.

**Comment by beberlei** [comment]
Internal question for discussion group.
