### ISSUE TITLE
Collections are tricky to work with - can easily explode in your hand

### ISSUE THREAD

**Issue by arnaud-lb** [doctrine/orm#7453]
An ORM becomes useful when we can forget about it most of the time. With a data mapper ORM, this seems to be attainable: We can write a domain model as if it lives entirely in memory. The domain model takes care only of the business logic. Persistence and data loading is done completely outside of the domain model. More importantly, data loading is done lazily and seamlessly.

The extra lazy collections play an important role in this: By being extra lazy, most operations will avoid loading the full collection in memory. Without this, we couldn't use collections safely because this could exceed the available amount of memory.

The problem is that not all operations are extra lazy, and some are extra lazy only if the collection is clean.

For example:

 - first() will always load the full collection in memory
 - matching() will load the full collection in memory if we used add() before

As a result, the domain model can not use all operations on a collection. Also, it must take care of respecting some order (e.g. never using matching() after add()). This is error prone and tricky.

Are there plans to improve this in Doctrine 3 ?

**Comment by Ocramius** [comment]
Not really fixable, unless in-memory and lazy behaviour can be brought to
match each other exactly. This isn't currently possible due to different
persistence cycle when using EXTRA_LAZY and LAZY (queries go directly to
DB, even deletes).

Therefore, if this needs to be improved, we first need a clear and well
discussed specification for it.

I'd also add that we won't improve V3 further, as we're only aiming at
completing pending work on the metadata, while collections may eventually
completely be replaced in future, if we decide to use php-ds instead (v4?).

**Comment by arnaud-lb** [comment]
Thanks. IMHO, having a least-surprise collection in the ORM would help a lot to make a reliable domain model.

Agreed that it's not easily fixable in the current state of things. However, with the right changes, it seems to be fixable.

I would love to see a discussion on this.

I think that an implementation would just need to buffer inserts and deletes in memory (maybe by materialising deletes with a tombstone in the in-memory collection). This would allow to implement all operations without ever loading everything in memory (except for iteration and callback-based operations, obviously). LSM tree based data stores such as LevelDB are doing exactly this, and apparently this allows them to implement operations such as get, put, delete, get first, get last, without needing to merge the level 0 (the in memory buffer) with other levels first.

**Comment by beberlei** [comment]
This is unfortunately the nature of a leaky abstraction such as ORMs. A few of the gotachas are documented at least.

The domain model *is* reliable, what you want is performance reliability, which is not what ORMs primary use case.

We can discuss optimizing individual calls like `Collection::first` further, but a generic ticket such as this is too broad in scope.
