### ISSUE TITLE
Eager fetched relations re-hydrated when already managed in UnitOfWork

### ISSUE THREAD

**Issue by tezhm** [doctrine/orm#7458]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6.2

#### Summary

Loading entities via EntityPersister of UnitOfWork should use manged entity if already cached instead of re-hydrating properties from database.

#### Current behavior

When loading entities via EntityPersister of UnitOfWork, if the entity has a relation which is `fetch="EAGER"` and is loaded multiple times, each consecutive load will fetch the relations instead of using existing cached relation.

#### How to reproduce

See pull request.

#### Expected behavior

Should not re-hydrate the eager fetched relation as already hydrated.

**Comment by tez-m** [comment]
Any feedback on this? Am I making the right assumptions here when I assume that entities fetched via relations are also part of the managed cache?

**Comment by Ocramius** [comment]
@tez-m I'm not sure about this one: I'd say that loaded in-memory objects that are initialised (not proxies, or loaded proxies) should indeed not be refreshed.

I can confirm the bug.

**Comment by tezhm** [comment]
Using queries generated from the EntityManager seem to manage the relation caching instead of directly calling the unit of work. I don't think this is a bug.
