### ISSUE TITLE
Hydratation error when two classes with the same parent class both define the same property with different types.

### ISSUE THREAD

**Issue by m-r-r** [doctrine/orm#7505]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6.3

#### Summary

`SimpleObjectHydrator` produces a type error when two classes with the same parent class both define a property with the same name and different types.

I think this may be related to issue #5989.

#### Current behavior

When two classes inherit from the same parent using `SINGLE_TABLE` inheritance, and both classes define the same property with different types, `SimpleObjectHydrator` produce a type error if one of the properties is of type `simple_array`.

#### How to reproduce

Create an abstract class with two child classes:
```php
use Doctrine\ORM\Annotation as ORM;

/**
 * @ORM\Entity()
 * @ORM\Table(name="test_responses")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({
 *     "array"       = ArrayResponse::class,
 *     "text"        = TextResponse::class,
 * })
 */
abstract class AbstractResponse {
    /**
     * @ORM\Id @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    public $id;
}
```

Create two child classes. Each class defines the same property with different types.
The first class use the type `simple_array` and the second class has a `string` property :
```php
/**
 * @ORM\Entity()
 */
class ArrayResponse extends AbstractResponse {
    /**
     * @ORM\Column(name="value_array", type="simple_array")
     *
     * @var array
     */
    public $value = [];
}

/**
 * @ORM\Entity()
 */
class TextResponse extends AbstractResponse {
    /**
     * @ORM\Column(name="value_string", type="string")
     *
     * @var string|null
     */
    public $value = null;
}
```

Create an instance of the second class and flush the `EntityManager`:
```php
$textResponse = new TextResponse();
$em->persist($textResponse);
$em->flush();
```

Clear the `EntityManager` and fetch the instance:
```php
$em->clear();

/** @var TextResponse $arrayResponse */
$textResponse = $em->getRepository(AbstractResponse::class)
                   ->find($textResponse->id);

var_dump($textResponse->value); // Display an empty array (type error)
```

#### Expected behavior

The value of `$textResponse->value` should be NULL, because the property `$value` of class `TextResponse` has type `string|null`.

**Comment by m-r-r** [comment]
I'm creating a pull request with a failing test case.

**Comment by Ocramius** [comment]
This should be a validation error: these columns *MUST* have different names.

**Comment by m-r-r** [comment]
@Ocramius Thanks for answering so quickly and noticing that: I made an error when writing the issue and the names of the columns are missing in the annotation.

The behavior is the same when the columns have different names, I updated the code in the issue to fix the column names.

**Comment by Ocramius** [comment]
@m-r-r there are two issues then:

 1. two `ReflectionProperty` with different `#getDeclaringClass()` but same `#getName()` lead to incorrect hydration
 2. two `ReflectionProperty` with different `#getDeclaringClass()` but same `#getName()` and mapped with same `@Column(name=)` should lead to the [`SchemaValidator`](https://github.com/doctrine/doctrine2/blob/a5ed7ed89c2265f88246d99f475e325709f8fa0e/lib/Doctrine/ORM/Tools/SchemaValidator.php#L33) rejecting them.

**Comment by m-r-r** [comment]
@Ocramius Ok ! Should I open a second issue for the validation problem ?

**Comment by Ocramius** [comment]
@m-r-r yes please, or maybe just create a failing test case involving the schema validator :+1:

**Comment by beberlei** [comment]
@Ocramius the hydrator code has multiple paths where it has comments mentioning the handling of duplicate field names across the hierachy, so it is actually supported to do this right now.

**Comment by beberlei** [comment]
Fixed
