### ISSUE TITLE
findBy broken for inherited entity property lookups

### ISSUE THREAD

**Issue by themizzi** [doctrine/orm#7512]
### Bug Report

| Q.                 |   A
|------------ | ------
| BC Break     | no
| Version        | 2.6.3

#### Summary

findBy does not work correctly for inherited entities. proof here: https://github.com/themizzi/doctrine-find-by-metadata-bug

#### Current behavior

If EntityB has a OneToMany relationship to EntityA, and EntityC inherits (via join) from EntityA. If there is no cache, calling `$entityBRepo->findBy('entityA' => $newEntityCInstance)` works fine. On a subsequent request after cache has already been generated and metadata is lazy loaded, the request breaks. on sqlite this just fails, on MySQL this potentially loads up an incorrect entity.

#### How to reproduce

Please see link above for an example and reproduction steps.

#### Expected behavior

Find by can find classes by properties with an inheritance structure at all times.

**Comment by Ocramius** [comment]
@themizzi please reproduce this bug in isolation within an integration test, like in https://github.com/doctrine/doctrine2/tree/master/tests/Doctrine/Tests/ORM/Functional/Ticket.

**Comment by themizzi** [comment]
will try to do this weekend. other priorities call for now.

**Comment by themizzi** [comment]
Created regression test. Might have some time to looking into an appropriate fix this weekend.
