### ISSUE TITLE
Doctrine\ORM\EntityRepositoy::count invalid type hint

### ISSUE THREAD

**Issue by crtl** [doctrine/orm#7523]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6.3

#### Summary

`Doctrine\ORM\EntityRepository::count(array $criteria)` should be `Doctrine\ORM\EntityRepository::count($criteria)`, because it calls `Doctrine\ORM\Persister\Entity\EntityPersister::count` which accepts `array|\Doctrine\Common\Collections\Criteria` as argument.

**Comment by Ocramius** [comment]
Changing the signature is not really feasible due to inheritance anymore. If you want to fix it, it should target `3.0`.

**Comment by bednic** [comment]
Due to what inheritance?! The method ::count is on EntityRepository and only there. So fix type signature is not hard thing, just remove array. I did it myself, but it's really annoying doing it on every project. EntityPersister::count() still ins't typed and is annotated accepting array or Criteria. Remove array type doesn't break anything.

**Comment by Tomsgu** [comment]
@bednic If anyone has extended EntityRepository, than it's actually a problem.

**Comment by bednic** [comment]
@Tomsgu It shouldn't be, cause if u have right setup on environment, then warnings are suppresed. And non-matching method type signatures are warning, not error. But OK, this is "privilege" of PHP. So there is another solution, like add new method, ::countByCriteria which will accept Criteria object. Then everybody will be happy. But someone screw this up, so would be nice, if it get fixed. IMHO even in big project this fix is like findAll > replace ... Who actually has multiple Entity-Repositories in project where is overwriting base methods like count.

**Comment by Ocramius** [comment]
> Who actually has multiple Entity-Repositories in project where is overwriting base methods like count.

A lot of folks, which is why this is labeled as such.

Closing as per my initial labeling in https://github.com/doctrine/orm/issues/7523#issuecomment-447312549
