### ISSUE TITLE
defaultQueryHints is not applied doctrine generated queries

### ISSUE THREAD

**Issue by tinntsea** [doctrine/orm#7541]
### Bug Report

I'm using symfony 3, postgres, and doctrine 2.6.2.
I wanted the application to read from master db in some cases to prevent replication lag issue.

So I used setDefaultQueryHints function in order to append /*NO LOAD BALANCE*/ comment as prefix of every select query.
```
$emConfiguration->setDefaultQueryHints(array_merge(
                [
                    Query::HINT_CUSTOM_OUTPUT_WALKER => SqlCommentWalker::class,
                    SqlCommentWalker::POSITION => SqlCommentWalker::POSITION_PREPEND,
                    SqlCommentWalker::COMMENT => SqlCommentWalker::COMMENT_READ_MASTER,
                ],
                $emConfiguration->getDefaultQueryHints()
))
```

The thing is it is not applied to doctrine generated queries

 
```
# Doctrine\ORM\Configuration

    /**
     * Sets array of query hints, which will be applied to every query in application
     *
     * @since 2.5
     *
     * @param array $defaultQueryHints
     */
    public function setDefaultQueryHints(array $defaultQueryHints)
    {
        $this->_attributes['defaultQueryHints'] = $defaultQueryHints;
    }

```

**Comment by Ocramius** [comment]
> it is not applied to doctrine generated queries

Could you please make an example or failing test case?

**Comment by beberlei** [comment]
Doctrine does not use DQL internally, as such the query hints are not applied.
