### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by StasToken** [doctrine/orm#7568]
Сука меня заебало блять кавырятся в вашем говне блять сука
Сделайте нормальный сука дебаг
блять
Вы заебали сука пол дня нахуй приходится ебатся сука что бы блять понять нахуй где блять сука ошибка

Notice: Undefined index: system_key

Вот суты блять скажешь по такой информации где блять ошибка а?
Вот не скажешь? вот и диде нахуй все в месте ебалны!

**Comment by Ocramius** [comment]
Closing, erasing, locking and blocking the author. This is the first and last interaction on these communication level.
