### ISSUE TITLE
Naming options for the orm:convert-mapping and orm:generate-entities commands

### ISSUE THREAD

**Issue by Coop-1** [doctrine/orm#7582]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes?
| BC Break    | yes?

#### Summary

When reverse engineering a database for use with Doctrine, all of the xml and later the entities generated (by the orm:convert-mapping and orm:generate-entities commands respecitvely) do not respect camel case with regards to our table and column names. 

An example column generated in one of the tables' XML files: 
<field name="datenum" type="integer" column="dateNum" nullable="true">
       <options>
         <option name="unsigned"/>
       </options>
     </field>

The "dateNum" column is clearly read just fine, but Doctrine doesn't appear to have any option in the documentation to let name="dateNum" instead of "datenum". The same applies to table names, and then later to .php models. 

For our large database, the thought of writing a script to manually correct all of these issues in the XML so we can move to Doctrine is enough to turn people off of Doctrine, especially if we'd have to be running the convert-mapping command multiple times over a period while we move towards Doctrine entirely.

**Comment by Ocramius** [comment]
Entity generation is deprecated is not going to be improved anymore, sorry.
