### ISSUE TITLE
Proxy tries to call destructor of not loaded entities, including removed entities

### ISSUE THREAD

**Issue by arnaud-lb** [doctrine/orm#7601]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | ?
| Version     | 2.6.3

#### Summary

When an entity defines a destructor, an entity proxy will attempt to call the entity's destructor when it's destroyed.

#### Current behavior

If the proxy never initialised (it never loaded the actual entity), it will apparently try to load the entity during `__destruct`.

If the entity had been `removed()`, we may see some unexpected behaviours or some EntityNotFoundException exceptions.

#### How to reproduce

- Get a reference to an entity that has a destructor
- Remove the entity

I've created a failing test case here: https://github.com/arnaud-lb/doctrine2/commit/db8cfd9d2541a31e03f888920b80cdf2549b9574

#### Expected behavior

Should a proxy destructor attempt to load the entity if it's not already loaded ?

**Comment by Ocramius** [comment]
Yes, it should still call the destructor

**Comment by arnaud-lb** [comment]
I'm genuinely interested in hearing the rationale behind this.

Intuitively, I would have though that since the entity is not constructed yet, calling its destructor is not necessary, especially since this requires to construct it just for this purpose.

This would be sad, because apart from this bug, this also defeats the purpose of a lazy loading proxy: Entities with a destructor will always be loaded when its proxy/reference is destroyed.

**Comment by Ocramius** [comment]
I've detailed this in following pre-existing issues (sorry, different repository, but same reasoning applies):

 * https://github.com/Ocramius/ProxyManager/issues/258
 * https://github.com/Ocramius/ProxyManager/issues/262
 * https://github.com/Ocramius/ProxyManager/issues/373

 > Entities with a destructor will always be loaded when its proxy/reference is destroyed.

Correct.
