### ISSUE TITLE
Update improving-performance.rst to reflect current state of PHP ecosystem

### ISSUE THREAD

**Issue by Majkl578** [doctrine/orm#7619]
This page should be updated to be more up to date with how PHP applications are used in 2019:
- describe OPcache more precisely, with recommended production configuration snippet (e.g. disabled filesystem access);
- drop references to APC;
- recommend static PHP driver for metadata (for 2.x already or wait for 3.0?);
- recommend Redis for other cache types.

Follow-up from https://github.com/doctrine/orm/pull/7610#issuecomment-465361513.

**Comment by lcobucci** [comment]
Being handled by https://github.com/doctrine/orm/pull/7500. As I mentioned there, I don't think we need to drop APCu there.

**Comment by Majkl578** [comment]
APCu is useless, OPcache superior for metadata & query caches in all ways. :)

**Comment by lcobucci** [comment]
I don't disagree but there are people who can't rely on opcache for weird reasons but are just fine with apcu

**Comment by beberlei** [comment]
https://github.com/doctrine/orm/pull/7500 is merged
