### ISSUE TITLE
orm:schema-tool:create more friendly error when it's not able to create database file.

### ISSUE THREAD

**Issue by CViniciusSDias** [doctrine/orm#7620]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

When we try to execute `php vendor/bin/doctrine orm:schema-tool:create` with an SQLite database configured to a path that doesn't exist, an error like this one is shown:

![Error](https://uploaddeimagens.com.br/images/001/913/334/full/erro-doctrine.png)

It would be a lot easier to newcomers to figure out what's happening if the CLI informed that the directory where it's trying to create the database file doesn't exist.

**Comment by Ocramius** [comment]
@CViniciusSDias this is what the underlying SQLite layer is reporting to us: we don't check if the directory/path exists, nor if the file is writable, since that's a detail of Sqlite3 or PDO_Sqlite.

Please report this to https://bugs.php.net/ if you want to have the SQLite exception improved.
