### ISSUE TITLE
Composite Key with DateTime and a ManyToOne, does not work.

### ISSUE THREAD

**Issue by obw** [doctrine/orm#7627]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6.3

#### Summary

Composite Key with DateTime and a ManyToOne, does not work.

#### Current behavior

In UnitOfWork.php line 1507:
                                                                                    
  [ErrorException]                                                                  
  Catchable Fatal Error: Object of class DateTime could not be converted to string  

#### How to reproduce
create two Entities:

```
class Link
{
    /**
     *
     * @var integer
     * @ORM\Column(type="integer",options={"unsigned":true, "comment":"ID"},nullable=false)
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Id
     */
    protected $id;
}

class LinkVal
{
    /**
     *
     * @ORM\Column(type="datetime")
     * @var \DateTime
     * @ORM\Id
     */
    protected $created;

    /**
     *
     * @var \App\Entity\Link
     * @ORM\ManyToOne(targetEntity="App\Entity\Link", fetch="EXTRA_LAZY")
     * @ORM\Id
     */
    protected $link;

     public function __construct()
    {
        $this->created = new \DateTime;
    }
    public function setLink(Link $link)
    {
        $this->link = $link;
    }
}

$link = new Link();
$linkVal = new LinkVal();
$linkVal->setLink($link);
$em->persist($linkVal);
$em->persist($link);
$em->flush(); // and here the error Happens!
```
#### Expected behavior

The Entities should be stored!

#### Work Around
Add a single autoincrement Primary Key and a uniqueIndex for both fields!

**Comment by Ocramius** [comment]
This is expected: fields that will contain an `object` must contain objects that implement `__toString` in order to be stored in the ORM's `UnitOfWork`.

See also https://stackoverflow.com/a/15085566/347063

**Comment by obw** [comment]
True, but what is the use of \DateTime Class then, I could overwrite it, perhaps, but what would happen when there are changes in the API of PHP and so on, this is something I do not like to do...

For my part, I see a Problem like this, to be solved in the Library not in the Project....

So it's Perhaps better to add the resulution from StackOverflow to Doctrine....

regards!
