### ISSUE TITLE
ORDER BY scalar expression

### ISSUE THREAD

**Issue by secit-pl** [doctrine/orm#7628]
|    Q        |   A
|------------ | -----
| Version     | 2.x.x

### Support Question

I'm looking for example DQL query for calling exactly this line:
https://github.com/doctrine/orm/blob/e8eaf8386de1497863cb400fbc4fddda5878db7e/lib/Doctrine/ORM/Query/Parser.php#L1494

I can execute every each case in this switch but cant get into this condition
`case ($this->lexer->peek() && $this->isMathOperator($this->peekBeyondClosingParenthesis())):`

Can someone help me with any working example DQL query?

**Comment by Ocramius** [comment]
Probably something like:

```sql
SELECT
  SOME_COMPLEX_EXPRESSION() AS HIDDEN foo
FROM Bar b
ORDER BY foo ASC
```
