### ISSUE TITLE
Embedded Relations 

### ISSUE THREAD

**Issue by elvispdosreis** [doctrine/orm#7634]
|    Q        |   A
|------------ | -----
| Version     | 2.6

### Support Question

Is it possible to accomplish this type relationship, within an embedded class having a relationship with another table?

```
<?php

/** @Entity */
class User
{
    /** @Embedded(class = "Address") */
    private $address;
}

/** @Embeddable */
class Address
{
    /** @Column(type = "string") */
    private $street;

    /** @Column(type = "string") */
    private $postalCode;

    /** @Column(type = "string") */
    private $city;

    /**
     * @ManyToOne(targetEntity="Country")
     */
    private $country;
}

/** @Entity */
class Country
{
     /** @Column(type = "string") */
    private $code;

    /** @Column(type = "string") */
    private $name;
}
```

**Comment by lashus** [comment]
@elvispdosreis As far as I can tell from the documentation it is not. See: https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/tutorials/embeddables.html and the yellow note :)

**Comment by Ocramius** [comment]
Closing as per @lashus' review.

**Comment by Spomsoree** [comment]
Could this case somehow throw an error or something?
I just tried to group all pictures of an entity inside an embeddable, and wondered why no database field were created.

Doctrine accepted my configuration without a doubt, but did no create mentioned fields.

**Comment by BonBonSlick** [comment]
Would appriciate error or notification. We had a case

```
abstract class AbstractCredentialsVO extends AbstractVO {
    private ?string                                $email;
    private ?User                                  $user;

```
