### ISSUE TITLE
error starting doctrine

### ISSUE THREAD

**Issue by saaditani** [doctrine/orm#7646]
|    Q        |   A
|------------ | -----
| Version     | x.y.z

### Support Question

Dears,

I am setting up jagger from https://jagger.heanet.ie/jaggerdocadmin/installation.html#install-sh-script
however I am at the step that I need to run ./doctrine but the problem is am getting error:
./doctrine

PHP Fatal error:  Uncaught Error: Class 'Doctrine\Common\ClassLoader' not found in /opt/rr3/application/libraries/Doctrine.php:29
Stack trace:
#0 /opt/rr3/application/doctrine.php(30): Doctrine->__construct()
#1 /opt/rr3/application/doctrine(5): include('/opt/rr3/applic...')
#2 {main}
  thrown in /opt/rr3/application/libraries/Doctrine.php on line 29
====================
Is there any fix for the below?

here is my classloader.php:

locate ClassLoader
/opt/rr3/application/vendor/composer/ClassLoader.php
/opt/rr3/application/vendor/symfony/debug/DebugClassLoader.php
/opt/rr3/application/vendor/symfony/debug/Tests/DebugClassLoaderTest.php
/opt/vendor/composer/ClassLoader.php
/opt/vendor/doctrine/common/lib/Doctrine/Common/ClassLoader.php

**Comment by Ocramius** [comment]
This is not related to Doctrine ORM itself, but rather to be reported at the appropriate project under https://github.com/Edugate
