### ISSUE TITLE
The EntityManager is closed.

### ISSUE THREAD

**Issue by zakjakub** [doctrine/orm#7651]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.4.5

#### Summary

Uncaught PHP Exception Doctrine\ORM\ORMException: "The EntityManager is closed." at /vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php line 144

Message doesn't contain any usable info. There is no way to find reason of this error. 

#### Current behavior

Doctrine throws an error and doesn't contain reason. So no way to resolve problem in app.
I found many posts in forums and websites - many people are very angry due to this bug.

#### How to reproduce

Use Doctrine ORM and wait until some bug in your code cause this Exception. Now, there is no way to resolve it.

#### Expected behavior

The error will contain some info about problem (instead of meaningless message).

**Comment by Ocramius** [comment]
Feel free to suggest improvements for 3.x on https://github.com/doctrine/orm/blob/04036f22446b7df7cca6c57ba16d01c65b8099bf/lib/Doctrine/ORM/Exception/EntityManagerClosed.php#L13

Meanwhile, I can tell you that there is absolutely nothing that can be done with a closed entity manager besides creating a completely new one.

**Comment by zakjakub** [comment]
But there is no way to find the reason, why Entity manager is closed.

**Comment by Ocramius** [comment]
That's what you got when calling `flush()` (previously) and an exception was raised.
