### ISSUE TITLE
em->flush($entity) for cascading associations behaves inconsistently between "inserts" and "updates"

### ISSUE THREAD

**Issue by TiMESPLiNTER** [doctrine/orm#7659]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6.3

#### Summary

The `flush` method for associations behaves inconsistently between "inserts" and "updates" if you provide an entity as an argument.

I have a `one-to-many` relation with `cascade=persist,remove`. While the relations' entity gets inserted together with the main entity when I call...

`$em->flush($mainEntity)` 

...the update case ignores changes for the relations' entity and does only persist the changes in the main entity.

#### Current behavior

Currently only create operations persist cascading relations' entities update operations don't.

#### How to reproduce

Create a relation:

```php
    $metadata->mapOneToMany([
        'fieldName' => 'translations',
        'targetEntity' => Profile::class,
        'mappedBy' => 'profile',
        'cascade' => ['persist', 'remove'],
    ]);
```

Insert (works as expected):
```php 
$translation = new Translation();
$translation->setLanguage('en');

$profile = new Profile();
$profile->setName('Foo');
$profile->addTranslation($translation);

$em->persist($profile);
$em->flush($profile);
```
The translation gets persisted together with the profile:

Update (works **not** as expected):
```php
$profile = $profileRepository->getProfileByName('Foo');
$profile->setName('Bar');
$translation = $profile->getTranslation('en');
$translation->setLanguage('de');

$em->flush($profile);
```
Only the changes for the profile entity get persisted the changes for the translation entity are ignored.

#### Expected behavior

I expect that both cases behave the same. Either both ignore sub entities if I only flush a specific parent entity or both do cascade and also store the relations' entity.

**Comment by SenseException** [comment]
The argument in `flush()` will be dropped and was already removed in master.

The 2.7 branch still has the argument, but I see that it hasn't a deprecation yet. We probably need one there.

**Comment by Ocramius** [comment]
I'm gonna close as `won't fix` this one for now though: `flush($entity)` will not be worked on.
