### ISSUE TITLE
No table name escape in ServiceEntityRepository->createQueryBuilder()

### ISSUE THREAD

**Issue by Oihso** [doctrine/orm#7664]
#### Summary

If you have entity, that named like SQL keyword (`Order` in my case), you can not use `$this->createQueryBuilder('...')->...;` because after building the query you get `SELECT ... FROM order ...` query which always has non-escaped table name. As a result, you cant access table with that name.

#### How to reproduce

1. Make entity named like SQL keyword
2. Build query with `$this->createQueryBuilder('...')->...;`
3. Try to execute it

P.S. Not sure, if this 'bug' relates to this repository, and not to [doctrine/orm](https://github.com/doctrine/orm)

**Comment by Ocramius** [comment]
Closing here: this is documented at https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/limitations-and-known-issues.html#identifier-quoting-and-legacy-databases
