### ISSUE TITLE
Unable to use 'find' for table named instance

### ISSUE THREAD

**Issue by amykhar** [doctrine/orm#7674]
### Bug Report
I have a table named instance.  Table creation and record insertion work properly.  However, a simple find, passing in the id, fails with 

[Syntax Error] line 0, col 7: Error: Expected IdentificationVariable | ScalarExpression | AggregateExpression | FunctionDeclaration | PartialObjectExpression | "(" Subselect ")" | CaseExpression, got 'instance'

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6.3

#### Summary

Table named instance causes syntax error on find;  Traces indicate the problem lies in the parser.

#### Current behavior
Syntax error on find($id);

#### How to reproduce

1. Create a table named instance.
2. Add a few records to it.
3. Call find() to retrieve one of those records.
4. Be sad that it didn't work.

```
$queryBuilder
            ->andWhere('instance.id = :id')
            ->setParameter(':id', $id);
        return $queryBuilder->getQuery()->getOneOrNullResult();
```

#### Expected behavior
Find would return an Instance.

**Comment by Ocramius** [comment]
What is the full DQL query?

**Comment by amykhar** [comment]
`$qb = $this->em->createQueryBuilder()
            ->select('i')
            ->from('Instance', 'i')
            ->where('i.id = :id')
            ->setParameter('id', $id)`

**Comment by Ocramius** [comment]
Yes, I'd need the result of `->getDql()` though

**Comment by amykhar** [comment]
`SELECT i FROM Instance i WHERE i.id = :id`

**Comment by Ocramius** [comment]
Oh, I think this is due to the `INSTANCE` is a DQL keyword.

**Comment by amykhar** [comment]
I couldn't find it in any list of reserved words.  Can you point me to the
list for future reference?  I also tried escaping the table name in the
yml, but no luck.  Is there any work around?

**Comment by Ocramius** [comment]
I think this is just a DQL parser bug. What happens if instead of using `Instance` you use for example `My\Instance`?

**Comment by amykhar** [comment]
Same error.  [Syntax Error] line 0, col 7: Error: Expected
IdentificationVariable | ScalarExpression | AggregateExpression |
FunctionDeclaration | PartialObjectExpression | "(" Subselect ")" |
CaseExpression, got 'instance'

**Comment by amykhar** [comment]
I found the workaround.  Using findOneBy instead of find works.

**Comment by jwage** [comment]
I tested this and when my entity is named `Instance`, I get this exception. If I put the entity in a namespace, I don't get the error.

```
php test.php
PHP Fatal error:  Uncaught Doctrine\ORM\Query\QueryException: SELECT i FROM Instance i WHERE i.id = :id in /data/scratchpads/test-orm-7678/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:43
Stack trace:
#0 /data/scratchpads/test-orm-7678/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(456): Doctrine\ORM\Query\QueryException::dqlError('SELECT i FROM I...')
#1 /data/scratchpads/test-orm-7678/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(314): Doctrine\ORM\Query\Parser->syntaxError('Doctrine\\ORM\\Qu...')
#2 /data/scratchpads/test-orm-7678/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(974): Doctrine\ORM\Query\Parser->match(100)
#3 /data/scratchpads/test-orm-7678/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1732): Doctrine\ORM\Query\Parser->AbstractSchemaName()
#4 /data/scratchpads/test-orm-7678/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1584): Doctrine\ORM\Query\Parser->RangeVariableDeclaration()
#5 /data/scratchpads/test-orm-7678/vendor/doctrine/orm/lib/Doctrine/ORM/Query/P in /data/scratchpads/test-orm-7678/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php on line 54
```

This error mentioned above doesn't seem related:

```
Same error.  [Syntax Error] line 0, col 7: Error: Expected
IdentificationVariable | ScalarExpression | AggregateExpression |
FunctionDeclaration | PartialObjectExpression | "(" Subselect ")" |
CaseExpression, got 'instance'
```

It looks like a DQL syntax error in the query that was executed.

As it seems like you figured out your issue, I am going to go ahead and close this. Thanks!
