### ISSUE TITLE
Object hash in UoW

### ISSUE THREAD

**Issue by sweiguny** [doctrine/orm#7675]
|    Q        |   A
|------------ | -----
| Version     | doctrine/orm v2.6.3

### Question

Hello,

I have some questions about the internals of Doctrine, which are primarily for my understanding.

The `UnitOfWork` has a collection of all entities under management and therefore also a list of their states (`private $entityStates = [];`). [Here is an assignment of a new Entity.](https://github.com/doctrine/orm/blob/ebb53acda96e304a6f91d4a5a2d76378a4e1d210/lib/Doctrine/ORM/UnitOfWork.php#L858) As you can see there, the object hash is taken as key and the value is the state ("managed").

**Isn't somewhere the primary key of the entity checked, too?**
Because, if only the object hash is checked, I can clone my entity which gives me another object hash, pass it to `EntityManager::persist()` and have basically the same entity twice in the `UnitOfWork`.

Or did I miss something?

Thank you in advance for your answer.

**Comment by Ocramius** [comment]
> **Isn't somewhere the primary key of the entity checked, too?**

The block you linked is specifically around `persistNew()`:

https://github.com/doctrine/orm/blob/ebb53acda96e304a6f91d4a5a2d76378a4e1d210/lib/Doctrine/ORM/UnitOfWork.php#L836-L861

`persistNew()` is only called when the entity state is confirmed to be `UnitOfWork::STATE_NEW`:

https://github.com/doctrine/orm/blob/ebb53acda96e304a6f91d4a5a2d76378a4e1d210/lib/Doctrine/ORM/UnitOfWork.php#L1591-L1602

 > I can clone my entity which gives me another object hash, pass it to `EntityManager::persist()` and have basically the same entity twice in the `UnitOfWork`.

Yes, that is very much possible, but it is also true that your domain logic is responsible for assigning a new identifier in the case you clone an existing entity. Entity semantics are a bit different from object semantics: in the context of a single `UnitOfWork`, you should really only have one entity per type+identifier in memory in your system.

**Comment by sweiguny** [comment]
okay, so Doctrine does not do the check, because it works under the premise, that the user of Doctrine has to use his brain, right?

this is completly okay for me, i just wanted to know.

one argument for that is also that Doctrine "gains" at least some performance, because it "saves" this check, right?

**Comment by Ocramius** [comment]
> one argument for that is also that Doctrine "gains" at least some performance, because it "saves" this check, right?

Not sure about this: if you think it needs to be inspected further, please consider sending a test case with your assumptions in a pull request.
