### ISSUE TITLE
Calling computeChangeSets from onUpdate Entity listener

### ISSUE THREAD

**Issue by ecenti** [doctrine/orm#7679]
|    Q        |   A
|------------ | -----
| Version     | ~2.4

### Question

Hello, I've got some question about internals of `UnitOfWork`.

The problem is when I got both Entity lifecycle callback and listener for `onUpdate` event -- if the state of Entity is somehow changed and then `UnitOfWork::computeChangeSets()` is called from the listener, I loose all changes except those made by lifecycle callback.

Is it wrong to call `computeChangeSets()` from Entity listener, and, if not, should not it calculate changesets correctly?

To reproduce this (*probably bug*), I created a [repository](https://github.com/ecenti/scratch-app)

I appreciate any response to my problem!

**Comment by Ocramius** [comment]
> Is it wrong to call `computeChangeSets()` from Entity listener, and, if not, should not it calculate changesets correctly?

Yes: please act in `onFlush` and use `recompute*` methods instead.
