### ISSUE TITLE
Make use of DocBlock var annotation in annotation mappings

### ISSUE THREAD

**Issue by goatfryed** [doctrine/orm#7683]
#### Use type provided by `@var` annotation as fallback, if type of column or targetEntity of relation is not defined

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | yes

#### Summary

While writing my entity annotations today, I suddenly wondered: Why can't we use the DocBlock var Annotations as default value for column type definition and targetEntity of relation mappings? In a lot of cases, they just duplicate each other.

I searched for similiar feature requests, but haven't found one. Are there any notable concerns against using another annotation as a default?

#### Edit
Currently, the default value of Column::type is string, even though it is defined as mandatory in the documentation. So changing the behavior would be a BC Break, I guess.

**Comment by Ocramius** [comment]
@goatfryed it would probably be more interesting to use typed properties from PHP 7.4 in `master`, at this point

**Comment by psfpro** [comment]
And why YAML driver is deprecated? I don't want to write XML

**Comment by Ocramius** [comment]
Here's a write-up on that: https://github.com/doctrine/DoctrineBundle/issues/776#issuecomment-363812362
