### ISSUE TITLE
Doctrine does not hydrates a query correctly!

### ISSUE THREAD

**Issue by engharb** [doctrine/orm#7696]
Current ORM version is: 2.6
### Support Question

I have two entities with declared relationship as ManyToMany or else. But in my DQL query I want to define a JOIN WITH in order to hydrate the resulted objects of two different entities i.e as the following:
Entity_A    Entity_B
a1              b1
a2              b2
a3              b1

my query:
```
$query = $this->createQueryBuilder('prod')
            ->select('a, b')
            ->innerJoin('App:B', 'b', Join::WITH,
                'a.xxx = b.xxx')
.....

            ->execute();
```

The result is :
array [
0 => a1,
1 => b1,
2 => a2,
3 => b2,
4 => a3,
5 => b1
]

But It should be or I want it to be as:
Array => [
     0 => [a1, b1],
     1 => [a2, b2],
     3 => [a3, b1]
]

Why the query does not return a hydrated result correctly in case that there is no declared relationship between different entities?

**Comment by Ocramius** [comment]
As confusing as it might seem, that is the correct hydration for arbitrary joins. Sadly, we cannot change that, as it would be a very subtle BC break.

**Comment by engharb** [comment]
@Ocramius Do you have any workaround?

**Comment by Ocramius** [comment]
You can try hydrating with `SELECT a AS key1, b AS key2 FROM ...`: I don't remember what kind of structure that produces though.
