### ISSUE TITLE
Use  timestamp with time zone when generating schema data

### ISSUE THREAD

**Issue by goetas** [doctrine/orm#7699]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | yes
| BC Break    | probably

#### Summary

PostgreSQL officially discourages the use of `timestamp without time zone`  when storing timestamps (the PHP `Datetime` object). See https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_timestamp_.28without_time_zone.29 that gives some very good reasons for it.

Currently doctrine when generating schema info from the entity classes uses `timestamp without time zone`... 
I'm suggesting to add the timezone info, using `timestamp with time zone` to map the PHP `DatetimeInterface`  based properties when using PostgreSQL (could be a good idea doing the same for the other DB engines that support timezones as the problems probably are the same).

I guess this is something to be considered for 3.0

**Comment by jwage** [comment]
Possible duplicate of https://github.com/doctrine/orm/issues/7245 or related to at least

**Comment by goetas** [comment]
Probably yes, #7245  is more complete
