### ISSUE TITLE
map jsonb to object vice versa

### ISSUE THREAD

**Issue by videni** [doctrine/orm#7712]
Save a plain object using jsonb, when fetch it out, it  is automatically mapped to that object again.   [doctrine-json-odm](https://github.com/dunglas/doctrine-json-odm) is a solution, but it is better to use object table mapping instead of serializer.
 
features required:

1. Define index fo jsonb
2. automatically transform object to jsonb vice versa.

**Comment by Ocramius** [comment]
JSONB is vendor-specific, and we cannot build ORM features for it unless iall other vendors also support it.

Closing as `won't fix`: as much as I'd love to basically tell people "just use PostgreSQL", this is not the project where that can be proposed.
