### ISSUE TITLE
Error when create query for entity named Order

### ISSUE THREAD

**Issue by frimuchkov** [doctrine/orm#7734]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | 2.6.3

#### Current behavior
Get exception:
`
Fatal error: Uncaught Doctrine\ORM\Query\QueryException: SELECT o FROM Order o in /var/www/ops/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:43 Stack trace: #0 /var/www/ops/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(456): Doctrine\ORM\Query\QueryException::dqlError('SELECT o FROM O...') #1 /var/www/ops/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(314): Doctrine\ORM\Query\Parser->syntaxError('Doctrine\\ORM\\Qu...') #2 /var/www/ops/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(974): Doctrine\ORM\Query\Parser->match(100) #3 /var/www/ops/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1732): Doctrine\ORM\Query\Parser->AbstractSchemaName() #4 /var/www/ops/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1584): Doctrine\ORM\Query\Parser->RangeVariableDeclaration() #5 /var/www/ops/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1319): Doctrine\ORM\Query\Parser->IdentificationVariableDeclaration() #6 /var/www/ops/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(878 in /var/www/ops/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php on line 54`

#### How to reproduce

Crete entity with class name Order and execute:
` $entityManager->getRepository('Order')->createQueryBuilder('o')->select('o')->getQuery()->getSQL();`

#### Expected behavior

Correct sql

**Comment by Ocramius** [comment]
Closing here: see https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/limitations-and-known-issues.html#identifier-quoting-and-legacy-databases

**Comment by frimuchkov** [comment]
> Closing here: see https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/limitations-and-known-issues.html#identifier-quoting-and-legacy-databases

No, it's a different problem
There is `@Table(name="orders", indexes={@Index(columns={"title", "note"}, flags={"fulltext"})})`

**Comment by frimuchkov** [comment]
@Ocramius
There is strings in `Lexer.php`:
`                $name = 'Doctrine\ORM\Query\Lexer::T_' . strtoupper($value);
                if (defined($name)) {
                    $type = constant($name);

                    if ($type > 100) {
                        print_r($name.'<br>');
                        return $type;
                    }
                }`

So, for this valid DQL: `SELECT o FROM Order o` method return incorrect type of `Order`

**Comment by Ocramius** [comment]
Ah yep, you will indeed need to namespace your entity
