### ISSUE TITLE
Null in fields value in Cached Entity several times on day on high-load project.

### ISSUE THREAD

**Issue by AlexSmerw** [doctrine/orm#7735]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.6.3

#### Summary
We have a problem with the cache on a high-load project. Several times a day, the entity is retrieved from the cache with the field value = null, and these fields cannot be null
```
/ **
    * @var curator
    *
    * @ManyToOne (targetEntity = "SD \ Domain \ PersistModel \ Curator \ Curator")
    * @JoinColumn (name = "curator_id", referencedColumnName = "id")
    * /
   private $ curator ;
```

#### Current behavior

This situation arises from related entities. When the parent entity gets out of the cache, and the related is already expired.
See [DefaultEntityHydrator function loadCacheEntry](https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Cache/DefaultEntityHydrator.php#L182) 
Then 
[BasicEntityPersister function load](https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php#L745) will return Entity with null fields value.
Because [AbstractEntityPersister](https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Cache/Persister/Entity/AbstractEntityPersister.php#L469)
$entity = $this->persister->loadById($identifier, $entity);
It put $entity = null to function loadById($identifier, $entity) Instead Entity.

#### How to reproduce
Set $assocEntry  = null on [DefaultEntityHydrator line180](https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Cache/DefaultEntityHydrator.php#L180) for child entity

#### Expected behavior
I think this can be corrected by editing the code in function loadById(array $identifier, $entity = null)
[loadById](https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Cache/Persister/Entity/AbstractEntityPersister.php#L447)

Replace $ entity with $ cachedEntity
https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Cache/Persister/Entity/AbstractEntityPersister.php#L458

```
$cachedEntity = $this->persister->loadById($identifier, $entity);
        if ($cachedEntity === null) {
            return null;
         }
```

**Comment by Ocramius** [comment]
We'd need a test case for this: as the issue is presented right now, this isn't really usable by maintainers.

**Comment by AlexSmerw** [comment]
Look. For example. We have 3 classes :
Car 
Engine 
Power  
[Link on code](https://github.com/AlexSmerw/doctrineCacheBugFix/tree/master/Car)

Init data 
```
$engine = new Car\Engine('turbo');
$power = new Car\Power(100, 110, $engine);
$car = new Car\Car('white', $engine);

$entityManger->persist($car);
$entityManger->persist($power);
$entityManger->persist($engine);

$entityManger->flush();
```
When entities have already set to cache, we try to get data from cache
```

$carRepository = $entityManger->getRepository(Car\Car::class);
$car = $carRepository->find(1);
$engine = $car->getEngine();
```
$engine short dump
___isInitialized__ =  **false**
model = null_

```$power = $engine->getPower();``` // In this moment   [$assocRegion->get($assocKey) in Doctrine/ORM/Cache/DefaultEntityHydrator.php](https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Cache/DefaultEntityHydrator.php#L179) it can return **null**, because key 'power_hash' can be expired in hi load project.
It very rare situation, but we have this problem every days.

$engine short dump
___isInitialized__ =  **true**
model = null_

```$model = $engine->getModel(); ``` -  Exception  'Car\Engine::getModel() must be of th  
  e type string, null returned'

**Comment by Ocramius** [comment]
Thanks for the more detailed explanation, but we'd still need an (automated) integration test that verifies the issue. See https://github.com/doctrine/orm/tree/master/tests/Doctrine/Tests/ORM/Functional for examples.

**Comment by lcobucci** [comment]
Handled by #7750
