### ISSUE TITLE
Automate fetchJoinCollection behavior in Doctrine Pagination

### ISSUE THREAD

**Issue by javiereguiluz** [doctrine/orm#7741]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

In the [Doctrine Pagination doc](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/tutorials/pagination.html) you can read:

> This behavior is only necessary if you actually fetch join a to-many collection. You can disable this behavior by setting the $fetchJoinCollection flag to false; in that case only 2 instead of the 3 queries described are executed. We hope to automate the detection for this in the future.

I'm interested in -> *"We hope to automate the detection for this in the future."*.

My questions:

* Is this doc still relevant? Or was this feature already automated?
* If it's not been automated yet, are you still interested in that?
* If you are interested, how can we help make this improvement a reality?

Thanks!

**Comment by bendavies** [comment]
@teohhanhui did this in APIP
https://github.com/api-platform/core/pull/2639

**Comment by teohhanhui** [comment]
I must note that what we've done in API Platform makes many assumptions and does not aim to cover all the edge cases, but only to make a good guess for the typical use cases. It'd be great if it could be done correctly in Doctrine.

**Comment by javiereguiluz** [comment]
Somewhat related to this, we're starting to use Doctrine's Paginator in the "Symfony Demo" app (see https://github.com/symfony/demo/pull/1006/files) and we're facing some issues (see https://github.com/symfony/demo/pull/1006/files#r299857212).

Instead of solving those issues ourselves in "Symfony Demo" (and therefore, force each project to solve these same issues themselves too) I wonder if Doctrine could do something to autodetect/autosolve all this.

I'm pinging @andreas because he told us in Symfony's Slack that he might take a look at this. Thanks a lot!

**Comment by alcaeus** [comment]
Yeah, a quick look at the solution implemented in API Platform tells me I don't want to touch this with a 10 foot pole 😂

As @teohhanhui said, covering the 80% of all cases is **relatively** easy, but it's the edge cases that will mess things up. One thing we need to do is improve the docs: reading through them and not being all that familiar with ORM, it took me a while to understand what's going on. Maybe we could add some examples as to when to use or not use `fetchJoinCollection`.

Last but not least, we should just drop that sentence about hoping to implement this in the future. No further comment on that one

**Comment by javiereguiluz** [comment]
OK, let's close as "won't fix" for the reasons explained above. Thanks!
