### ISSUE TITLE
Playground website

### ISSUE THREAD

**Issue by iluuu1994** [doctrine/orm#7745]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

I think it would be greatly beneficial for the Doctrine team and users if there was a playground website where bugs could be reproduced and cross referenced to the issue. I see several benefits:

1. Incentive to provide simplistic examples, optimally reusable as integration tests
2. Much easier to create said examples than to create a new project, sample entities, database, etc.
3. Instantly verifiable by you guys
4. Instantly verifiable if the bug was fixed by us

Great examples of such websites are:

https://psalm.dev/
https://phpstan.org/

WDYT?

**Comment by Ocramius** [comment]
Feasible with in-memory SQLite, but would need to run in an environment that has no network access. While Psalm/PHPStan do not run code, doctrine does, so the environment needs to be armored.

**Comment by iluuu1994** [comment]
> Feasible with in-memory SQLite

I think that should be sufficient for the majority of issues 👍 

> While Psalm/PHPStan do not run code, doctrine does, so the environment needs to be armored.

That's true. Maybe the guys from [3v4l.org](https://3v4l.org) can help to make it secure.
