### ISSUE TITLE
What with bitwise operators?

### ISSUE THREAD

**Issue by peter-gribanov** [doctrine/orm#7760]
|    Q        |   A
|------------ | -----
| Version     | 2.6.3

### Support Question

I found an old issue #1820 [DDC-1213], but i still do not understand why binary operations are not supported as operator.
Why, instead of the usual ones for all operators, are the functions specific to the Doctrine used ?
Is this due to platform limitations?

```php
$query = $em->createQuery('SELECT e FROM Event e WHERE p.visibility & :visibility = :visibility');
$query->setParameter('visibility', $user->getRights());

return $query->getResult();
```

**Comment by peter-gribanov** [comment]
And one more question. Is it possible to use XOR (`^`) , left shift (`<<`) and right shift (`>>`) operators?

**Comment by Ocramius** [comment]
Heya, this is explained at https://github.com/doctrine/orm/issues/1820#issuecomment-162355933

Please use custom DQL functions - adding operators to the DQL language is a lot of complexity for a very small use-case scenario that doesn't lose much in using explicit functions.

**Comment by Slamdunk** [comment]
@Ocramius I'm trying to implement the `XOR` operator, much like [beberlei/DoctrineExtensions BitXor](https://github.com/beberlei/DoctrineExtensions/blob/master/src/Query/Mysql/BitXor.php) one for a SQL like:
```sql
SELECT *
FROM user
WHERE (
        username LIKE :first_match
    XOR username LIKE :second_match
)
```
and the DQL should look like:

```sql
SELECT u
FROM Entity\User u
WHERE (
    MY_XOR(
        u.username LIKE :first_match,
        u.username LIKE :second_match
    )
)
```
but I'm struggling: it seems that `$parser->ArithmeticPrimary();` doesn't like operators within arguments:
```
Doctrine\ORM\Query\QueryException: [Syntax Error] line 0, col 555:
Error: Expected Doctrine\ORM\Query\Lexer::T_CLOSE_PARENTHESIS, got 'LIKE'
```
Any tip?

**Comment by Ocramius** [comment]
>  it seems that $parser->ArithmeticPrimary(); doesn't like operators within arguments:

You probably want to match on a `->ConditionalExpression()`.

See https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#ebnf

**Comment by jurysosnovsky** [comment]
I added bitwise operators for doctrine https://github.com/jurysosnovsky/doctrine-binary
