### ISSUE TITLE
Psalm support

### ISSUE THREAD

**Issue by zerkms** [doctrine/orm#7762]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Are there any plans to add psalm-specific typing annotations the same way it already was added in `doctrine/collections` (eg https://github.com/doctrine/collections/blob/master/lib/Doctrine/Common/Collections/Collection.php#L29)

**Comment by Ocramius** [comment]
@zerkms overall :+1: to adding these from my end, but there's a huge list of PRs with required fixes that need attention too, so I won't be able to apply them myself.

I just finished covering https://github.com/Ocramius/ProxyManager/pull/467 in a similar way, if anybody needs inspiration to work on this.

**Comment by orklah** [comment]
I think this can be closed now
