### ISSUE TITLE
[3.0 BC] ClassMetadataBuilder removed w/o notice

### ISSUE THREAD

**Issue by rtek** [doctrine/orm#7783]
|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.0.0

#### Summary

The `ClassMetadataBuilder` is no longer on master and is not part of the upgrade list. Is there a new API?

https://github.com/doctrine/orm/blob/master/docs/en/reference/php-mapping.rst

See removal commit: https://github.com/doctrine/orm/commit/2366b43b1eae974cd14d655370efe551e147044e

**Comment by Ocramius** [comment]
Yes, the entire metadata API will need new docs, since it was completely replaced.
