### ISSUE TITLE
flush([$one]) does not flush changes of the $manies (cascade all is set)

### ISSUE THREAD

**Issue by dominikzogg** [doctrine/orm#7788]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6.3

#### Summary

We tried to flush the one side and expected that the changes on the manies side are flushed to.

#### Current behavior

The changes of the manies gets ignored, when the manies already exist in the database.

https://github.com/doctrine/orm/blob/2.6/lib/Doctrine/ORM/UnitOfWork.php#L912

#### How to reproduce

Create a bidirectional one to many relation. Set cascade to all and add orphanRemoval.

```php
<?php 

foreach ($one->getManies() as $many) {
    $many->setValue('value');
    $entityManager->persist($many);
}

$entityManager->flush([$one]);
```

Changes on $one will be flushed, add and remove on manies will be flushed, but not changes.

#### Expected behavior

Changes on $one will be flushed, add and remove on manies will be flushed, changes on manies will be flushed.

**Comment by lcobucci** [comment]
Flushing specific entities has known issues and is kind of a big pain, hence the removal from v3. 


Sorry to frustrate you with this answer but our recommendation is to not rely on that 😕

**Comment by dominikzogg** [comment]
@lcobucci thanks for you fast response. The answer is OK for me.

What we tried:
1. flush($one)
2. flush throws DeadlockException
3. recreate entity manager with a event manager containing only postFlush events (did not worked anyway, cause event manager needs to be same as on connection, which we don't like to change)
4. ask the old unity of work if its a insert, update or delete, and to persist and remove
5. flush again

So you give me another good reason to stop trying todo dirty hacks.

**Comment by SenseException** [comment]
Being able to flush specific entities like `flush($one)` won't be supported starting with 3.0. You would depend on a different solution if an update to 3.0 happens.

**Comment by lcobucci** [comment]
@dominikzogg just `flush()` should, in theory, work. Based on your snippet I can't really find a reason why it doesn't. Would you be willing to shoot us a PR with a failing functional test case?

**Comment by dominikzogg** [comment]
@lcobucci we're stopped trying to create this hack as mentioned in comment https://github.com/doctrine/orm/issues/7788#issuecomment-517831855 . I suggest to close the issue.
