### ISSUE TITLE
Ability to disable FOREIGN KEY CONSTRAINT when using Doctrine generate migration

### ISSUE THREAD

**Issue by TangMonk** [doctrine/orm#7795]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

Guaranteed constraints require additional computing resources. The application server is easier to scale horizontally than the database server, so the constraints should be placed in the business logic.

I often change/add some field in Entity and using `bin/console make:migration` to generate migrations, that's convenience just like in Rails or Django. But I do not need Foreign Key Constraint when I using Doctrine Relationships(ManyToOne, OneToMany...). 

I have to delete lines contained Foreign Key Constraint in generated migrations. But When I doing some changes with Entity, and run `bin/console make:migration`, It will add Foreign Key Constraint again, it is annoying.

In django model ForeignKey you can set `db_constraint=False`, so migration would not generate Foreign Key constraint

**Comment by Ocramius** [comment]
If you don't want foreign keys, you can use a custom DB platform that disables foreign key support.

Besides that, migrations are to be checked one by one anyway, before being committed.

**Comment by slince** [comment]
@Ocramius  

> If you don't want foreign keys, you can use a custom DB platform that disables foreign key support.

this way is no longer working in the lastest version.

**Comment by Ocramius** [comment]
Time to learn about respecting foreign keys 😁

Disabling FKs during a migration can still be done on some platforms (notably MySQL).
