### ISSUE TITLE
Entity Manager insert exist record

### ISSUE THREAD

**Issue by Shahrudinov** [doctrine/orm#7798]
### Bug Report
php 7.2
symfony 3.4.11
doctrine 2.6.1

#### Summary
Cannot save data after $entityManager->flush. Have exception with message cannot insert entity with name 111 because entity with name 111 already exist. If remove $entityManager->clear or $entity1->getName()  it work fine. 

#### How to reproduce
$entity1->getName();
$entityManager->clear();

foreach($entity1->getItems() as $item) {  // item cascade={"persist"} to entity1
     $item->update($someData);
}

$entityManager->flush();
   

#### Expected behavior
save all data

**Comment by Ocramius** [comment]
What are `$em->commit()` and `$em->beginTransaction()`?

In fact, what is `$em` and what is your entity looking like?

**Comment by Shahrudinov** [comment]
sorry i made the report more understandable

**Comment by Ocramius** [comment]
Yeah, I'd still need:

 * the exact exception trace (to see what fails)
 * to know what your entity (`$entity1` and `$item`) look like.

This seems like you are replacing a reference to an entity somewhere.

**Comment by Ocramius** [comment]
Closing here: we need reproducible tests to help you out, see https://github.com/doctrine/doctrine2/tree/master/tests/Doctrine/Tests/ORM/Functional/Ticket for examples.

**Comment by Ocramius** [comment]
Please open a new PR showing the failure, once reproduced :+1:
