### ISSUE TITLE
why return int(1) instead of an object??

### ISSUE THREAD

**Issue by followyounger** [doctrine/orm#7801]
public function findByRightId($state, $userRightId, $userId)
    {
        return  $this->createQueryBuilder('u')
            ->andWhere('u.state = :state')
            ->andWhere('u.id = :id')
            ->andWhere('u.userId = :userId')
            ->andWhere('u.estate = :estate')
            ->setParameter('state', $state)
            ->setParameter('id', $userRightId)
            ->setParameter('userId', $userId)
            ->setParameter('estate', EstateEnum::VALID)
            ->getQuery()
            ->getOneOrNullResult();
    }

in prod ,it return int(1);

in test, it return an object.

**Comment by Ocramius** [comment]
> in test, it return an object.

You'd need to debug it yourself to provide a failing test case for this repo.

Closing here, since we can't help further, unoess we know what `createQueryBuilder` looks like in your test environment.
