### ISSUE TITLE
[Question] Is there anything like "shadow properties" in Doctrine?

### ISSUE THREAD

**Issue by CViniciusSDias** [doctrine/orm#7802]
|    Q        |   A
|------------ | -----
| Version     | 2.6.3

### Support Question

Am I able to map a column so the schema tool can create it on schema, but not define it in my Entity class? Something like Shadow Properties in Entity Famework (.NET).
This way we wouldn't have to create attributes that aggregate no value in our classes (like `last_updated`, for instance).

**Comment by Ocramius** [comment]
That's generally not supported: you will need to use custom written DB migrations, and skip mapping these columns.

You can use event listeners in DBAL to append columns to tables when the schema ia being created.
