### ISSUE TITLE
 Pagination not working when SimpleArithmetic is used in order by

### ISSUE THREAD

**Issue by Seb33300** [doctrine/orm#7805]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | >= 2.6

#### Summary

When using `Paginator`on a query using a `SimpleArithmetic` expression in the `ORDER BY`, I am encountering a MySQL error:

```sql 
SELECT a FROM Doctrine\Tests\Models\CMS\CmsArticle a ORDER BY a.topic + 0 ASC
```

Result in:

> PDOException: SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'a0_.topic' which is not in SELECT list; this is incompatible with DISTINCT

This is because the `Paginator` handles only `PathExpression` to prevent this.

Here is the PR to fix this: https://github.com/doctrine/orm/pull/7803

**Comment by lcobucci** [comment]
As explained in https://github.com/doctrine/orm/pull/7803#pullrequestreview-295948417 we should rather use `HIDDEN` fields to be able to have arithmetic operations in `ORDER BY`. So the query should rather be:

```sql
SELECT a, a.topic + 0 AS HIDDEN my_sum FROM Doctrine\Tests\Models\CMS\CmsArticle a ORDER BY my_sum ASC
```

Closing as invalid here as well.
