### ISSUE TITLE
Support Type::convertToPHPValueSQL in ResultSetMappingBuilder

### ISSUE THREAD

**Issue by Elemecca** [doctrine/orm#7809]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

As of #198 entity persistence supports DBAL's `Type::convertToPHPValueSQL` method, which can be used to wrap columns in an SQL expression in the select clause of the generated query. However `ResultSetMappingBuilder::generateSelectClause` was not updated, so when using native queries with `ResultSetMappingBuilder` the `convertToPHPValueSQL` method is not applied to the generated select clause. I think it should be.

This looks like a pretty simple thing to implement and I'm happy to submit a PR. I think this is a simple enough non-breaking change that it could target the 2.6 branch, but before I start work I wanted to make sure that the change is acceptable and which branch I need to target.

**Comment by lcobucci** [comment]
@Elemecca we're trying to not add new features in v2.x series to be able to focus in v3. 

I'd suggest you send a PR to `master` (v3) and we can discuss the possibility of backporting it there. Don't forget to create tests too :smile:

**Comment by kimhemsoe** [comment]
Fixed by https://github.com/doctrine/orm/pull/9326
