### ISSUE TITLE
Bad PHPDocBlock AbstractQuery::getSingleScalarResult()

### ISSUE THREAD

**Issue by danielspk** [doctrine/orm#7811]
Hi, the DocBlock of the getSingleScalarResult() method of the AbstractQuery class is incomplete.

In addition to NonUniqueResultException it can also return NoResultException.

This causes phpstan to generate an alert about null returns that can never really occur since the expected behavior is an exception of the NoResultException type.

Greetings.

**Comment by sad270** [comment]
It's fixed on master branch :
https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/AbstractQuery.php#L781
But it is not release yet.

**Comment by SenseException** [comment]
@danielspk If is okay for you that is was fixed on `master`, please close this issue.
