### ISSUE TITLE
ExpressionBuilder contains doesn't work for type INT 

### ISSUE THREAD

**Issue by Stijn98s** [doctrine/orm#7816]
### Bug Report

I want to filter entities with a Criteria. When using the contains from the ExpressionBuilder on VARCHAR fields it works correctly. When using this on INT fields i get nothing.

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6.3

When using the contains on VARCHAR i get correct entities back. 

#### Current behavior

If i use `contains('name', 'test')` from a table like

|    Name       |   Age
|------------ | ------
| testie    | 11
| testa     | 12
| jhon     | 12

I correctly get 

|    Name       |   Age
|------------ | ------
| testie    | 11
| testa     | 12

But when i use `contains('age', 1)` I get

|    Name       |   Age
|------------ | ------

#### How to reproduce

```
$criteria = Criteria::create()->where(Criteria::expr()->contains('age', 1));
$em->getRepository(User::class)->matching($criteria)
```

#### Expected behavior

I expect i get the following

|    Name       |   Age
|------------ | ------
| testie    | 11
| testa     | 12
| jhon     | 12

**Comment by lcobucci** [comment]
@Stijn98s that's expected.

`ExpressionBuilder#contains()` is converted to `age LIKE '%1%'`, which is invalid for numeric columns (it should even throw an exception on stricter platforms like PGSQL).

**Comment by lcobucci** [comment]
Will close this as `invalid` as per my explanation. Please reopen if needed.
