### ISSUE TITLE
Exception when inserting a joined subclass

### ISSUE THREAD

**Issue by andrews05** [doctrine/orm#7824]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | don't know
| Version     | 3.0-dev

#### Summary

When persisting a new entity of a joined subclass, an exception will be thrown if the subclass has defined any properties that are not columns.

#### Current behavior

The following exception will be thrown:
`Call to undefined method Doctrine\ORM\Mapping\TransientMetadata::getColumnName()  in Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php on line 468`

#### How to reproduce

```PHP
/**
 * @ORM\Entity
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorMap({"child" = "Child"})
 */
abstract class Main {
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     */
    protected $id;
}

/**
 * @ORM\Entity
 */
class Child extends Main {
    private $someProperty; // Not a column
}

$child = new Child();
$em->persist($child);
$em->flush();
```

#### Expected behavior

Successful insert with no exception.

**Comment by SenseException** [comment]
Thank you for reporting this issue. Can you please create a PR with a failing test? The described behavior differs from the 2.x versions and afaik isn't supposed to break.

**Comment by andrews05** [comment]
@SenseException I've submitted a PR with a test case and possible fix.
