### ISSUE TITLE
How to use Query Builder only?

### ISSUE THREAD

**Issue by ztj1993** [doctrine/orm#7826]
|    Q        |   A
|------------ | -----
| Version     | 2.6.3

### Support Question

Assuming that I have an RPC communication (internal use), I want to transfer information such as where, order, group to the back end according to the model. Can QueryBuilder be implemented?

I just want to use the query builder.

**Comment by Ocramius** [comment]
Check the `Criteria` API: https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/working-with-associations.html#filtering-collections

You may also want to look at the specification pattern, and at the "query bus" used in CQRS/ES frameworks in the PHP ecosystem.
