### ISSUE TITLE
Unused local variable 'reflFieldValue'

### ISSUE THREAD

**Issue by peter-gribanov** [doctrine/orm#7834]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6.3

#### Summary

Unused local variable `$reflFieldValue` in `ObjectHydrator` at [this](https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php#L379) line.

![image](https://user-images.githubusercontent.com/1954436/65671808-99920580-e050-11e9-96be-4fbaf047b5cf.png)

**Comment by SenseException** [comment]
Have you checked if tests fail when you remove this occurrence of `$reflFieldValue`?

**Comment by peter-gribanov** [comment]
@SenseException removing this variable does not affect tests. See #7840
