### ISSUE TITLE
Subquery broken after upgade from 2.6.3 to 2.6.4

### ISSUE THREAD

**Issue by jimiero** [doctrine/orm#7839]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | x.y.z

#### Summary

After upgrading to 2.6.4, I get this error:

**Notice: Array to string conversion**

#### Previous behavior

Before applying the update it worked just fine.

#### Current behavior

Now receiving error: Notice: Array to string conversion

#### How to reproduce
This is the code which was working before:

```
return $this->getEntityManager()
          ->createQuery(
              'SELECT et
              FROM AppBundle:ArticleType et
              WHERE et.id IN (:ids)'
          )
          ->setParameter('ids', $this->getEntityManager()->getConnection()->fetchAll(
              "SELECT DISTINCT article_type_id FROM articles WHERE active =1 and end_date >= '".date('Y-m-d H:i:s')."'"), Connection::PARAM_INT_ARRAY)
          ->getResult();

```

with 2.6.4 it returns that error, if I downgrade to 2.6.3 it's just fine.

Is this a bug or the code has to be updated?

**Comment by Ocramius** [comment]
You seem to be binding `int[][]` rather than `int[]`

**Comment by jimiero** [comment]
@Ocramius you mean the code is doing it wrong or is just a bug?

**Comment by Ocramius** [comment]
It looks like a bug in yout code, not the ORM. This code was probably never working, but the ORM was silently converting things for you.

**Comment by jimiero** [comment]
@Ocramius any suggestion what to modify to have it working?

**Comment by Ocramius** [comment]
You need to `array_column()` on the result of your DBAL query.

Closing here meanwhile.
