### ISSUE TITLE
SchemaTool generates extra diff for platforms without FK support

### ISSUE THREAD

**Issue by vpArth** [doctrine/orm#7841]
### Bug Report

SchemaTool generates extra diff for platforms without FK support(ex: SqlitePlatform)

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | all

#### Summary

SchemaTool::getUpdateSchemaSql is never empty, because MetaData contains foreign keys adding, but SqlitePlatform has not support of them

#### How to reproduce

```php
/** @ORM\Entity */
class A {
    /** @ORM\Id @ORM\Column(type="integer") @ORM\GeneratedValue */
    public $id;
    /** @ORM\OneToMany(targetEntity=B::class, mappedBy="parent") */
    public $children;
}
/** @ORM\Entity */
class B {
    /** @ORM\Id @ORM\Column(type="integer") @ORM\GeneratedValue */
    public $id;
    /** @ORM\ManyToOne(targetEntity=A::class) */
    public $parent;
}
// ...
    $class = $em->getClassMetadata(B::class);
    $schemaTool->updateSchema([$class]);
    $diff = $schemaTool->getUpdateSchemaSql([$class]);
```

#### Current behavior
```php
count($diff) > 0;
```

#### Expected behavior
```php
count($diff) === 0;
```

**Comment by lcobucci** [comment]
Handled by #7842
