### ISSUE TITLE
EXTRA_LAZY fetch documentation improvement

### ISSUE THREAD

**Issue by DonCallisto** [doctrine/orm#7852]
|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | yes
| BC Break    | no

Starting from https://github.com/doctrine/orm/issues/6560, I think we should update https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/tutorials/extra-lazy-associations.html in order to point out this situation.
As it is a combination of fetching mode and `orphanRemoval` I'm also not sure if `orphanRemoval` documentation should point that out.
I'm willing to help in case of positive responses.

WDYT?

**Comment by lcobucci** [comment]
@DonCallisto your help is much appreciated. We already had https://github.com/doctrine/orm/issues/7765 to track this, so let's collaborate over there :+1:

**Comment by lcobucci** [comment]
I'll close this one to avoid confusion :smile:
