### ISSUE TITLE
Invalid version in Doctrine\ORM\Version::VERSION

### ISSUE THREAD

**Issue by guillaumesmo** [doctrine/orm#7858]
Not sure what the implications are nor if this is really considered a "bug"

The value of \Doctrine\ORM\Version::VERSION is 2.6.4-DEV in the version tagged "2.6.4"
I noticed in 2.6.3 it was 2.6.3

**Comment by lcobucci** [comment]
That's indeed incorrect, thanks for letting us know. I've missed that step while releasing it.

We'll fix it for 2.6.5 but can't do much for 2.6.4 😕

**Comment by lcobucci** [comment]
Fixed by d71dd5d94f186be63c15b55ebef0e14627e11fdd
