### ISSUE TITLE
Doctrine trying to insert instead of updating

### ISSUE THREAD

**Issue by averichev** [doctrine/orm#7870]
Doctrine trying to insert instead of updating
Why is this happening? How to solve the problem?

|    Q        |   A
|------------ | -----
| Version     |  v2.6.4
```
$connection = $this->manager->getConnection();
$builder = $connection->createQueryBuilder()
            ->select('u')
            ->from('users', 'u')
            ->where('u.enabled = TRUE');
$statement = $builder->execute();
$statement->setFetchMode(FetchMode::CUSTOM_OBJECT, User::class);
while ($row = $statement->fetch()) {
    $row->setWorkPhone('123456');
    $this->manager->persist($row);
    $this->manager->flush();
}
```

**Comment by Ocramius** [comment]
This is correct: custom objects (from your fetch mode) aren't put in the `UnitOfWork`, and therefore are considered in `UnitOfWork::STATE_NEW`

**Comment by averichev** [comment]
@Ocramius how i can put it in the `UnitOfWork`?

**Comment by Ocramius** [comment]
I'd rather ask: why do you need a custom object? Can you elaborate on that?

**Comment by averichev** [comment]
we want to work on a large number of entities, in order to save memory we want to use the cursor (fetch). How can this be done differently?

**Comment by greg0ire** [comment]
From [the docs](https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/batch-processing.html#dql-update):

>  An ORM tool is not primarily well-suited for mass inserts, updates or deletions. Every RDBMS has its own, most effective way of dealing with such operations and if the options outlined below are not sufficient for your purposes we recommend you use the tools for your particular RDBMS for these bulk operations

If reading [the paragraph about bulk updates](https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/batch-processing.html#dql-update) does not help you with the performance issues, consider using the DBAL/SQL.
