### ISSUE TITLE
Symfony 5 console compatibility

### ISSUE THREAD

**Issue by dmaicher** [doctrine/orm#7879]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6

#### Summary

Some commands inside this repository are not compatible with Symfony 5 since it will require an integer exit code for all `execute` methods.

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Command/Command.php#L153

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Command/Command.php#L258

Affected commands:

- https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Tools/Console/Command/GenerateProxiesCommand.php#L44
- https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Tools/Console/Command/RunDqlCommand.php#L48
- https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Tools/Console/Command/ClearCache/CollectionRegionCommand.php#L68
- https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Tools/Console/Command/ClearCache/EntityRegionCommand.php#L67
- https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Tools/Console/Command/ClearCache/QueryRegionCommand.php#L66

Related: https://github.com/doctrine/dbal/pull/3706

**Comment by Seb33300** [comment]
Already fixed on 2.7

https://github.com/doctrine/orm/pull/7876

**Comment by evertharmeling** [comment]
And will be in 2.6 :)

#7899

**Comment by derrabus** [comment]
Wen have a stable ORM release supporting Symfony 5 now. Can we close this issue? #SymfonyHackday
