### ISSUE TITLE
EntityManagerInterface is missing getRepository definition

### ISSUE THREAD

**Issue by AngelsDustz** [doctrine/orm#7888]
Hello, we have some strict type checking on our PHP code and PHPStan noticed that I wrongly assigned a variable.

Upon further investigation I noticed that `EntityManagerInterface->getRepository` has a different specified return type than `EntityManager->getRepository`. 

The non-interface has the following return annotation: `ObjectRepository|EntityRepository` (https://www.doctrine-project.org/api/orm/latest/Doctrine/ORM/EntityManager.html#method_getRepository)

But the interface does not have this function defined and defaults to the inherited `ObjectManager->getRepository` resulting in a return type of `ObjectRepository`.

**Comment by Ocramius** [comment]
> But the interface does not have this function defined and defaults to the inherited `ObjectManager->getRepository` resulting in a return type of `ObjectRepository`.

This is correct and expected
