### ISSUE TITLE
getOneOrNullResult should not throw an exception when having more than one result

### ISSUE THREAD

**Issue by crtl** [doctrine/orm#7916]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | yes
| BC Break    | ?

#### Summary

When calling `AbstractQuery::getOneOrNullResult` while having more than one result, results in an exception being thrown:
```
In AbstractQuery.php line 780: More than one result was found for query although one row or none was expected.
```

Either the method name or the exception is wrong.
Why should an exception be thrown when I get more than one result?

**Comment by Ocramius** [comment]
This is by design: a query that is supposed to retrieve one or zero results produced more results, and it should indeed throw (unexpected).
