### ISSUE TITLE
No foreign key in sqlite

### ISSUE THREAD

**Issue by fmathieu1** [doctrine/orm#7930]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | Yes
| Version     | >=2.6.5

#### Summary

Since I upgraded ``doctrine/orm`` to ``2.6.5`` from ``2.6.3`` I no longer have foreign keys on my SQLite.
I tried version ``2.6.4`` and it works as expected.

#### Current behavior

I can no longer use ``onDelete="CASCADE"`` and such

#### How to reproduce

Given my Category entity, referencing itself as parent 

```php
class Category 
{
    /**
     * @var Category|null
     *
     * @ORM\ManyToOne(targetEntity="Category")
     * @ORM\JoinColumns({
     *     @ORM\JoinColumn(name="parent_id", referencedColumnName="id", nullable=true, onDelete="CASCADE")
     * })
     */
    private $parent;

}
```

#### Expected behavior

i can use ``onDelete="CASCADE"``  to have children removed when a parent is removed

**Comment by spideyfusion** [comment]
We are running into the same issue on one of our projects where we use the SQLite platform in our test environment because it's easier to bootstrap than e.g. MySQL.

The issue appears to be caused by this change: https://github.com/doctrine/orm/pull/7842

**Comment by lcobucci** [comment]
Handled by #7937 to be released soon :+1:
