### ISSUE TITLE
Official docs is not available

### ISSUE THREAD

**Issue by hanovruslan** [doctrine/orm#7942]
### Official docs is not available

|    Q        |   A
|------------ | ------
| BC Break    | yes?
| Version     | 2.7

#### Summary

https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/index.html

```
Page not found
````

**Comment by lcobucci** [comment]
Thanks for letting us know, we're looking into the problem :+1:

**Comment by SenseException** [comment]
The docs are available again and we can close this issue. Thank you for reporting @hanovruslan.
