### ISSUE TITLE
cannot name an entity "Group" : MySQL error because `group` is not escaped

### ISSUE THREAD

**Issue by kaamui** [doctrine/orm#7951]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Symfony Version     | 4.3.1

#### Summary

All's in the title.

#### Current behavior

![image](https://user-images.githubusercontent.com/11720903/70533202-dc944d00-1b58-11ea-94e7-e49f6469a391.png)

#### How to reproduce

Create an entity named Group. 
Try to use findAll() with its associated repository

#### Expected behavior

Doctrine should escape table names.

**Comment by Ocramius** [comment]
https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/basic-mapping.html#quoting-reserved-words

**Comment by kaamui** [comment]
Oops, sorry, and thanks for your reactivity

**Comment by kaamui** [comment]
Just to know, when it is written that, "Doctrine does not quote identifiers automatically, because it leads to more problems than it would solve", what kind of issue did you encounter when you tried to quote identifiers automatically ?
