### ISSUE TITLE
 The Doctrine\Common\Persistence\Mapping\Driver\AnnotationDriver class is deprecated since doctrine/persistence 1.3 and will be removed in 2.0. Use \Doctrine\Persistence\Mapping\Driver\AnnotationDriver instead.

### ISSUE THREAD

**Issue by kasali** [doctrine/orm#7964]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | x.y.z

#### Expected behavior

I work in symfony and accross this issue!How to remove that?
Thanks!

**Comment by mhujer** [comment]
You can find more info in https://github.com/doctrine/orm/pull/7953
