### ISSUE TITLE
Please fix dependency to doctrine/dbal. Impossible to install doctrine/orm.

### ISSUE THREAD

**Issue by Musiksammler** [doctrine/orm#7968]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.0.x-dev

#### Summary

Currently it's absolutely impossible to install doctrine/orm 3.0.x-dev because the doctrine/dbal snapshot cannot be found.

#### Current behavior

Installation stops.

#### How to reproduce

Put "doctrine/orm": "3.0.x-dev" in a composer.json and run "composer install".

#### Expected behavior

doctrine/orm gets installed.

This is pretty annoying at the moment because it's not possible to do a composer install on fresh projects which should use doctrine orm!

**Comment by lcobucci** [comment]
This is being handled in #7938. It's important to mention that v3.0 is still under development and it's not suitable for production usage.

Will close this since things are already in progress.
