### ISSUE TITLE
Add insertOrIgnore method 

### ISSUE THREAD

**Issue by pana1990** [doctrine/orm#7985]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Laravel has the insertOrIgnore method in his querybuilder (https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/Query/Builder.php#L2656), it would be great if doctrine also included it

What do you think about it?

**Comment by beberlei** [comment]
Do you mean that in context of DQL, as in `$em->createQuery('INSERT OR IGNORE ...');` or as part of an entity flush with an entity that is not managed, but uses an id that alrady exists:

```php
$entity = new Entity();
$entity->id = 'abcdefg';

$entityManager->persist($entity);
$entityManager->flush(); // ignore and dont throw exception when id 'abcdefg' already exists.
```

**Comment by pana1990** [comment]
this one (sorry for my delay)
>  or as part of an entity flush with an entity that is not managed, but uses an id that alrady exists:
