### ISSUE TITLE
Use ORM/DBAL Query builder in Persisters

### ISSUE THREAD

**Issue by hason** [doctrine/orm#8005]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | maybe

#### Summary

The sql queries in https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php are created as string. If I want to modify any sql, it would be better to use DBAL query builder instead of plain string. Even better would be to use ORM Query builder to support SQL walkers.

**Comment by beberlei** [comment]
This is done as a performance optimization, and there is intentionally no way provided to modify the SQL.
