### ISSUE TITLE
findAll doesn't return all the records

### ISSUE THREAD

**Issue by secit-pl** [doctrine/orm#8019]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.7.0

I have strange problem. In one of my projects where I'm connecting with SQL Server findAll doesn't return all the records.

I have 4002 records in table.

count($repository->findAll()); // returns 3931

count($this->createQueryBuilder('duration')
            ->getEntityManager()
            ->getConnection()
            ->executeQuery('SELECT * FROM [TEST_DB].[dbo].[Test Journey Duration]')
            ->fetchAll()); // returns 4002

count($this->createQueryBuilder('duration')
            ->getEntityManager()
            ->createQuery('SELECT jd FROM App:Journey\Duration jd')
            ->getResult()); // returns 3931

The table is very simple, has no relations and contains only 5 columns: 3 x int, 2 x string

The stranger thing is that when I'm querying directly for the record which is not included in findAll using DQL
```dql
SELECT jd FROM App:Journey\Duration jd WHERE jd.id = 12915
```
the record is returned with all data. The $repository->find(12915) also finds the entity.

**Comment by SenseException** [comment]
How does the SQL query look like when you call `$repository->findAll()`?

**Comment by beberlei** [comment]
@secit-pl did you maybe define the ID field on something that is not actually unique?

**Comment by beberlei** [comment]
No feedback here, closing for now.
