### ISSUE TITLE
Name spaces not supported when creating a Schema instance from a given set of metadata classes

### ISSUE THREAD

**Issue by abdel-geniusespro** [doctrine/orm#8038]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.7.1

#### Current behavior
Name spaces not supported during schema creation.

#### How to reproduce

1.  Create an entity with `@Table(schema="mySchema", name="myTable")`
2. Launch the command `doctrine:schema:update --force`
3. you'll have an SQL error `the schema mySchema doesn't exists`
4. To understand exactly what happen, lunch the command `doctrine:schema:update --dump-sql`, you'll see that an SQL instruction is missing `create schema mySchema;`

#### Expected behavior
Support name spaces during schema creation.

**Comment by beberlei** [comment]
That would be a bigger change in DBAL schema abstraction. Similar to MySQL where you need to create the database, you need to create all schema you want to use outside of Doctrine DBAL/ORM schema usage.

It is unlikely that we are going to be changing this as the complexity is too large for the gain.

**Comment by beberlei** [comment]
@abdel-geniusespro ok, i didn't see that we do have namespace support in DBAL now, when i last worked with the code it didn't exist. So maybe we can add it in SchemaTool.

**Comment by abdel-geniusespro** [comment]
Hello @beberlei  , thanks for your reply, I solved the problem locally like this https://github.com/doctrine/orm/pull/8046
