### ISSUE TITLE
find() doesn't Hydrate object with Single Table Inheritance (SINGLE_TABLE) child object

### ISSUE THREAD

**Issue by yosvield** [doctrine/orm#8042]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | 2.7.1

#### Summary
When the object is searched, the child object fields are in null

#### How to reproduce
i have relationship
/**
 * @ORM\Table(name="comun.person")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="type",type="bigint")
 * @ORM\DiscriminatorMap({"1" = "PersonN", "2" = "PersonJ"})
 */
abstract class Person
{..}

children class
/**
 * @ORM\Table(name="comun.person")
 */
class PersonN extends Person
{...}

When the object is searched, the children class fields are in null
$person=$this->getDoctrine()
            ->getRepository(Person::class)
            ->find(22737);

Expected behavior
find child object

**Comment by yosvield** [comment]
I already solved the problem, in the mapping the data type of the discriminatorColumn had it as bigint and in the SimpleObjectHydrator.php class when compared with the discriminatorValue the data type is different. ` if (isset($cacheKeyInfo['discriminatorValues']) && ! in_array($discrColumnValue, $cacheKeyInfo['discriminatorValues'], true)) {`

Fix
> 
/**
* @Orm\Table(name="comun.person")
* @Orm\InheritanceType("SINGLE_TABLE")
* @Orm\DiscriminatorColumn(name="type",type="string")
* @Orm\DiscriminatorMap({"1" = "PersonN", "2" = "PersonJ"})
*/
abstract class Person
{..}

**Comment by beberlei** [comment]
@yosvield the problem is really that bigints must be treated as strings, so you can keep the mapping, but your code must be:

```
$person = $this->getDoctrine()
            ->getRepository(Person::class)
            ->find("22737");
```

That can be a bit confusing at times

**Comment by Russellmd** [comment]
@beberlei is it mandatory to have @DiscriminatorColumn as string type? I found similar issue today, after upgrade (Symfony + Doctrine). 

In my case I use Class Table Inheritance ( InheritanceType("JOINED") ), DiscriminatorColumn of type integer. The issue is that  my object's fields from joined table are not initialized. Only if I change type for DiscriminatorColumn to string it works as expected.

**Comment by beberlei** [comment]
@Russellmd i don't know to be honest
