### ISSUE TITLE
Convert PHPUnit @expectedException into method call

### ISSUE THREAD

**Issue by beberlei** [doctrine/orm#8069]
In #8050 we found usage of a deprecated PHPUnit functionality. We should move all `@expectedException` and `@expectedExceptionMessage` inline into the code to their respective method calls.

Is there a Rector script for this?

**Comment by greg0ire** [comment]
Looks like it: https://github.com/rectorphp/rector/search?q=expectedException&unscoped_q=expectedException

**Comment by beberlei** [comment]
@greg0ire have a take at it if you want :)

**Comment by greg0ire** [comment]
I'm on it!

**Comment by beberlei** [comment]
Fixed by #8070
