### ISSUE TITLE
Custom entity persister?

### ISSUE THREAD

**Issue by gjdanis** [doctrine/orm#8076]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

Right now it's not possible to declare a custom persister for an entity. The specific use case I'm asking about is for MS SQL Server where one of my tables has a trigger that inserts into another another table. For this entity I want to use `OUTPUT` in my `INSERT` statements to get the correct identity value.

It seems like we should be able to inject this somewhere in the UnitOfWork or perhaps provide it as metadata on the entity: https://github.com/doctrine/orm/blob/99b7d1e9d4bfa6efb86f0a77b1e5522ec8e9bf9a/lib/Doctrine/ORM/UnitOfWork.php#L2562

@morozov tagging you for visibility.

**Comment by beberlei** [comment]
This is by design, building a persister is really difficult and we want to avoid introducing this extension point.
