### ISSUE TITLE
Does getDQLPart/getDQLParts will be deprecated/removed ?

### ISSUE THREAD

**Issue by VincentLanglet** [doctrine/orm#8077]
### Support Question

I saw here
https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/QueryBuilder.php#L1331
https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/QueryBuilder.php#L1343
the following comment `@todo Rename ... (or remove)`

Personally I used them in some specific situation, for example if I want to add a more specific orderBy.
- getQDLPart('orderBy')
- resetDQLPart('order')
- add my OrderBy
- re-add the previous OrderBy

Is there a reason to want to withdraw theses methods ?
If not, can I remove the `(or remove)` comment ?

**Comment by greg0ire** [comment]
For future reference, these comments were introduced in https://github.com/doctrine/orm/commit/8d52967fcd8a5d956fa0b7327fe1b89a690a6c79

**Comment by VincentLanglet** [comment]
Whoah, didn't see this !

I propose to remove the todo: https://github.com/doctrine/orm/pull/8078
