### ISSUE TITLE
Entity extending embeddable: Duplicate definition of column 'colName' on entity 'Foo' in a field or discriminator column mapping.  

### ISSUE THREAD

**Issue by marhub** [doctrine/orm#8080]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.7.2

#### Summary

code below stopped working after update from 2.7.0 to 2.7.2.
Downgrading fixes issue.

<pre>/**
 * @ORM\Embeddable()
 */
class Money
{
    /**
     * @ORM\Column(type = "integer")
     */
    protected $value = 0;
}

/**
 * @ORM\Entity
 */
class Price extends Money
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $priceId;
}</pre>

#### Previous behavior

That code was working in 2.7.0

#### Current behavior

Schema validation fails with 

>   Duplicate definition of column 'value' on entity 'Price' in a field or discriminator column mapping.

**Comment by SenseException** [comment]
Why do you extend the [embeddable](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/tutorials/embeddables.html#separating-concerns-using-embeddables) class in your example?

**Comment by malarzm** [comment]
@marhub I'm sorry to say, but an Entity extending Embeddable is not correct mapping. We will improve the schema validation to let users know about it. I believe the correct approach in your case is `Price` having a `Money` field:

```
/**
 * @ORM\Entity
 */
class Price
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $priceId;
    
    /**
     * @ORM\Embedded(class=Money::class)
     */
    private $money;
}
```

The other (and less feasible in my opinion) approach would be to have `Money` mapped as a `@ORM\MappedSuperclass` and have two separate classes: `MoneyEmbedded extends Money` and `Price extends Money` - that mapping would be correct from ORM's point of view.

**Comment by marhub** [comment]
OK, but there is no information about Embeds not extending Entities in documentation, is it ?
So seems like this "bug fix" will be BC break for many people like me. For now we have to stick to doctrine 2.7.0 :(

**Comment by beberlei** [comment]
@marhub we have reverted the commits in 2.7.1 and 2.7.2 related to embeddables, however we will start throwing Schema Validator errors for this use-case and remove it in the future. So you can prepare yourself to fix the mapping. Entities *cannot* extend Embeddables. Instead you can have a MappedSuperclass and extend it from both the Entity and the Embeddable.
