### ISSUE TITLE
Initialized ArrayCollection is null

### ISSUE THREAD

**Issue by FabianKoestring** [doctrine/orm#8082]
|    Q        |   A
|------------ | -----
| Version     | 2.7.2

### Support Question

Hey there,

iam facing following crazy behavior. I have 2 Entities. When i try to access an attribute from the one entity i will get `null` but this attribute is defined and initialized as an `ArrayCollection`. I expected a filled or empty `ArrayCollection` but not `null`. What may be the problem?

### First Entity
```php
...
/**
 * @ORM\ManyToOne(targetEntity="Category", inversedBy="profiles")
 * @ORM\JoinColumn(name="KAT_ID", referencedColumnName="KAT_ID")
 * @var Category
 */
private $category;
...
```

### Second Entity
```php
...
/**
 * @ORM\OneToMany(targetEntity="Profile", mappedBy="category")
 * @var ArrayCollection
 */
private $profiles;

public function __construct()
{
    $this->profiles = new ArrayCollection();
}
...
```

### Test
```php
// Warning: get_class() expects parameter 1 to be object, null given
var_dump(get_class($category->getProfiles()));
```

**Comment by greg0ire** [comment]
Do you instantiate `$category` yourself or do you get it from Doctrine? Do you know how to validate your mapping and have you tried doing so?

**Comment by FabianKoestring** [comment]
Sry. Gonna close this. It happend because of a missing join in a native query with resultset Mapping which selects the Same object. 

My bad!
