### ISSUE TITLE
Embeddable value object is loaded as NULL in 2.7.2

### ISSUE THREAD

**Issue by vicdelfant** [doctrine/orm#8089]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.7.2

#### Summary

We extensively use custom types as value types, such as an `InvoiceCode` in an `Invoice` entity (`Invoice::$code`). In our case, the `InvoiceCode` is an embeddable. For some reason, these properties are now left as a `null` value upon loading such an entity from the database.

## Previous behavior

In `doctrine/orm:2.7.1`, `Invoice::$code` is initialized properly.

## Current behavior

In `doctrine/orm:2.7.2`, `Invoice::$code` is initialized as `null`. This makes me think that this may be related to #8031. The [diff between 2.7.1 and 2.7.2](https://github.com/doctrine/orm/compare/v2.7.1...v2.7.2) does show some changes that involve embeddables, too.

## How to reproduce
Upgrade to `2.7.2` and use the following entity and embeddable. The entity and embeddable are trimmed for readability but you get the gist:

#### Entity
```php
class Invoice
{
    /**
     * @ORM\Embedded(class="FQCN\Foo\Bar\InvoiceCode")
     *
     * @var InvoiceCode
     */
    private $code;
}
```

#### Embedded
```php
/**
 * @ORM\Embeddable
 */
class InvoiceCode extends AbstractYearSequenceValue
{
    
}

/**
 * @ORM\Embeddable
 * @ORM\MappedSuperclass
 */
abstract class AbstractYearSequenceValue
{
    /**
     * @ORM\Column(type="integer", name="number", length=6)
     *
     * @var int
     */
    protected $number;

    /**
     * @ORM\Column(type="smallint", name="year", length=4)
     *
     * @var int
     */
    protected $year;
}
```

Failing test is coming up (will try to squeeze it in today).

**Comment by vicdelfant** [comment]
Right, failing test has been added in #8090. I noticed that the `@MappedSuperclass` annotation on the `AbstractYearSequenceValue` seems to be the trigger. Without it, things work like they should in `2.7.2`. As soon as I add it, the test fails in `2.7.2`.

This may actually be an error on my end; I added the MappedSuperclass because of [this comment](https://github.com/doctrine/orm/issues/8031#issuecomment-590075097) but I simply could have misunderstood the recommendation.

**Comment by beberlei** [comment]
@vicdelfant just to make sure, did you update doctrine/reflection and doctrine/persistence to the latest versions too?

**Comment by vicdelfant** [comment]
Not specifically since they're pulled in by `symfony/orm-pack`, but here is the version info just to be sure:

### Failing (ORM 2.7.2)
```
$ composer info doctrine/orm
name     : doctrine/orm
versions : * v2.7.2

$ composer info doctrine/reflection
name     : doctrine/reflection
versions : * 1.2.1

composer info doctrine/persistence
name     : doctrine/persistence
versions : * 1.3.7
```

### Working (ORM 2.7.1)
```
$ composer info doctrine/orm
name     : doctrine/orm
versions : * v2.7.1

$ composer info doctrine/reflection
name     : doctrine/reflection
versions : * 1.2.1

$ composer info doctrine/persistence
name     : doctrine/persistence
versions : * 1.3.7
```

**Comment by Qonstrukt** [comment]
It seems embeddables with inheritance are broken in more ways since 2.7.2.
I can't even query for properties in the base embeddable class anymore. 

In the context of this issue:
I get an `Invoice has no field or association named code.number` Semantical Error. While properties that I add to `InvoiceCode` itself are still queryable.

**Comment by beberlei** [comment]
We will revert all the embeddable changes for the next mini release
