### ISSUE TITLE
String columns are allowing integer bindings

### ISSUE THREAD

**Issue by ggeorgiev-sfly** [doctrine/orm#8092]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.7.0

#### Summary

When ORM mapping is defined like this:

```
    /**
     * @var string
     *
     * @ORM\Column(name="moment_uid", type="string", length=255, nullable=false)
     */
    private $momentUid;
```

One expects that value that is send to Database will be converted to string. However when an integer is passed in the DQL as parameter to this column, it's not converted to string, but is bound as integer to the PDO instance (in my case - MySQL with PDO).

I have an index on that column that cannot be executed correctly cause of the incorrect type given to the DB.

```
Errors & Warnings:
Warning
Cannot use ref access on index 'moment_key' due to type or collation conversion on field 'moment_uid'
Warning
Cannot use range access on index 'moment_key' due to type or collation conversion on field 'moment_uid'
```

#### Current behavior

Given field `stringField` is defined as integer in `Entity` as above example.
When you make a query like:

`SELECT a FROM Entity a WHERE a.stringField = ?1`

And bind the parameter like:

`$query->setParameter(1, 12345);`

It will bind this parameter as PDO::PARAM_INT

#### How to reproduce

See above

#### Expected behavior

I expect the ORM to detect that this is a string type field and convert it accordingly, then bind it as the correct PDO type when executing the query.

**Comment by lgeorgiev** [comment]
I think this will help.

    * @param string|integer $key   The parameter position or name.
     * @param mixed          $value The parameter value.
     * @param string|null    $type  PDO::PARAM_* or \Doctrine\DBAL\Types\Type::* constant
     *
     * @return QueryBuilder This QueryBuilder instance.
     */
    public function setParameter($key, $value, $type = null)
    {
        $existingParameter = $this->getParameter($key);
        if ($existingParameter !== null) {
            $existingParameter->setValue($value, $type);
            return $this;
        }
        $this->parameters->add(new Query\Parameter($key, $value, $type));
        return $this;
    }

**Comment by ggeorgiev-sfly** [comment]
> I think this will help - $query->setParameter(1, 12345, \PDO::PARAM_STR);
> 
> ```
>  * @param string|integer $key   The parameter position or name.
>  * @param mixed          $value The parameter value.
>  * @param string|null    $type  PDO::PARAM_* or \Doctrine\DBAL\Types\Type::* constant
>  *
>  * @return QueryBuilder This QueryBuilder instance.
>  */
> public function setParameter($key, $value, $type = null)
> {
>     $existingParameter = $this->getParameter($key);
>     if ($existingParameter !== null) {
>         $existingParameter->setValue($value, $type);
>         return $this;
>     }
>     $this->parameters->add(new Query\Parameter($key, $value, $type));
>     return $this;
> }
> ```

This is manually specifying the type. Yes I had to workaround it like that but this required a lot of changes on my side. I had to manually iterate all the entities metadata, get the type of the field and then based on that set the type of each parameter. This should be done automatically form the ORM. We already have all the mappings there. ORM should not bind integers to string column automatically (probably allow it with explicit parameter type set as the above example).

**Comment by fmasa** [comment]
I don't think this is bug, binding parameters to query has nothing to do with columns. You may bind parameter as argument of function or on many different places - you may also use parameters on more than one place in query, so this magic conversion would get complicated quickly.

Also this is consistent with way parameters are bound in other DB abstraction layers, such as PDO.

**Comment by ggeorgiev-sfly** [comment]
> I don't think this is bug, binding parameters to query has nothing to do with columns. You may bind parameter as argument of function or on many different places - you may also use parameters on more than one place in query, so this magic conversion would get complicated quickly.
> 
> Also this is consistent with way parameters are bound in other DB abstraction layers, such as PDO.

If we're speaking for DBAL layer (which is an abstraction more similar to PDO, not the ORM) - then yea, we shouldn't have that automatic. But when we go into ORM land, then I think we can be smarter about this. Cause ORM knows the type of each column (PDO and DBAL do not). ORM can see that we're trying to insert incorrect type into a column and fix that automatically. And I think it should do so.

Regarding using it multiple times in the query - I think it will be a bad query to use same parameter type in different type contexts - for example same type for integer column and for string one.

But yea with usages on multiple places in the query we will have an issue determining which column should be the source of the correct type. That can be discussed further I think.

**Comment by fmasa** [comment]
I just really disagree with this approach, you should fix the origin of your parameter, so that it correctly returns `string` or explicitly set parameter type as was suggested above by @lgeorgiev. Or you can simply cast it to string using `(string)`

This would be huge WTF (just like automatic type conversion in PHP itself), because correct type cannot be known at the time that DQL is parsed (as I mentioned before, there can be i.e. parameters used as argument DQL function, which would not be converted)

Consider following scenario:

This would convert parameter to string
```DQL
SELECT u FROM User u WHERE u.stringField = :param
```

and this would not:
```DQL
SELECT FUNCTION_WITH_STRING_ARG(:param) FROM User u
```

**Comment by ggeorgiev-sfly** [comment]
As most of the people disagree with this approach, I'm closing this as not a bug. It has to be manually specified it seems.
