### ISSUE TITLE
PHPStan warning

### ISSUE THREAD

**Issue by kirya-dev** [doctrine/orm#8096]
### Bug Report

|    Q         |   A
|------------ | ------
| Version  | 2.7.1

#### Summary
When im run phpstan analyser with 6 level i get error:
*Parameter #1 $x of method Doctrine\ORM\Query\Expr::andX() expects Doctrine\ORM\Query\Expr\Comparison|Doctrine\ORM\Query\Expr\Func|Doctrine\ORM\Query\Expr\Orx|string|null, Doctrine\ORM\Query\Expr\Andx given.*

#### Current behavior

https://github.com/doctrine/orm/blob/8c259ea5cb632dbb57001b2262048ae7fa52b102/lib/Doctrine/ORM/Query/Expr.php#L31

#### How to reproduce

Run ` vendor/bin/phpstan analyse -c phpstan.neon  -l 6`

#### Expected behavior

No warnings

Just replace annotation on mixed?

**Comment by greg0ire** [comment]
> Just replace annotation on mixed?

The list of allowed classes is shown here: https://github.com/doctrine/orm/blob/8c259ea5cb632dbb57001b2262048ae7fa52b102/lib/Doctrine/ORM/Query/Expr/Andx.php#L16-L21

So it would just be a matter of adding `Andx` here. Please send a PR against 2.7

**Comment by kirya-dev** [comment]
There https://github.com/doctrine/orm/pull/8098

**Comment by kirya-dev** [comment]
We can replace just on \Stringable (polyfill php8)?

**Comment by greg0ire** [comment]
What do you want to replace with `\Stringable` and why? We don't cast to string, do we?

**Comment by kirya-dev** [comment]
Want use this interface because all Expr has __toString()

**Comment by kirya-dev** [comment]
Whey just build DQL expression

**Comment by greg0ire** [comment]
I see, but we don't actually want to allow any `\Stringable`, do we?

**Comment by kirya-dev** [comment]
Using **\Stringable** able create own DQL classes

**Comment by greg0ire** [comment]
It's called `$allowedClasses` so I guess you can't use any class.

**Comment by kirya-dev** [comment]
PR here: https://github.com/doctrine/orm/pull/8227
