### ISSUE TITLE
API Reference Documentation Missing

### ISSUE THREAD

**Issue by kdorsey** [doctrine/orm#8104]
|    Q        |   A
|------------ | -----
| Version     | 2.7.2

### Support Question

Hello, recently I was able to reference API documentation here:

https://www.doctrine-project.org/api/orm/latest/Doctrine/ORM/EntityRepository.html

That URL is now a 404, did the API documentation move?

Thank you.

**Comment by SenseException** [comment]
Hi @kdorsey. Next to Slack I also wanted to answer here that the API docs were removed completely.

https://twitter.com/doctrineproject/status/1116080889996431362

**Comment by zzador** [comment]
When will the API doc be back online? API reference is the bare minimum of documentation for a library or a framework so Doctrine is very much unusable without a good API reference.

**Comment by derrabus** [comment]
There are no plans to restore the API documentation, as far as I know.

**Comment by zzador** [comment]
So doctrine is dead?

**Comment by derrabus** [comment]
No.
