### ISSUE TITLE
Add descending index support

### ISSUE THREAD

**Issue by fmonts** [doctrine/orm#8128]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Currently, there is no way to create a descending index (with the DESC attribute).
This feature is present in MySQL, MSSQL, PostgreSQL, and probably in the other platforms as well. 
(In MySQL older than 8.0 and MariaDB it's accepted but ignored)

It should be allowed a way to create ASC/DESC indexes, for example with:

    @ORM\Index(name="my_idx", columns={"col"}, options={"DESC"}),

Or

    @ORM\Index(name="my_idx", columns={"col DESC"},

**Comment by fmonts** [comment]
Workaround: you can manually edit the table or add "DESC" in your migration file and luckily the schema generation tool doesn't revert it to ASC when you run it again

**Comment by beberlei** [comment]
We cant support everything in SchemaTool, your workaround is the way to go.

**Comment by 24HOURSMEDIA** [comment]
I disagree with 'We cant support everything in SchemaTool', the descending index is a standard mysql 8, aurora, etc feature
and we absolutely need it on very large tables. 

So then the schema created by doctrine is not complete without migrations.

**Comment by derrabus** [comment]
> I disagree with 'We cant support everything in SchemaTool'

You're disagreeing with a fact here. 🤷🏻 

> the descending index is a standard mysql 8, aurora, etc feature

You're right, there's broad support among database vendors for the `ASC`/`DESC` keywords in `CREATE INDEX`.

> we absolutely need it on very large tables

If you want to work on a PR, please feel encouraged to do so. First of all, [the DBAL library](https://github.com/doctrine/dbal/) needs to be able to create and introspect this kind of indexes. If you need help with that, feel free to open an issue or draft PR there.

**Comment by 24HOURSMEDIA** [comment]
Interesting thought to help improve doctrine in this respect.
However my job for this case is primarily devops engineer and keeping our databases affordable and stable.

I doubt my client wants to spend resources on maintaining 3rd party libraries.
I might pick it up if I have spare time some time.

Then I'd be enlisted as a doctrine contributor ? :)

**Comment by devbranch-vitaliy** [comment]
Completely agree with @24HOURSMEDIA, @beberlei closed the ticket without a valid reason. 
Since we have the Index attribute/annotation, it must handle the possible option that the DB supports.

It's ridiculous, `where` oprion is supported, but a simple ASC/DESC is not 🤡 

My opinion is that the issue must be reopened.

**Comment by EdouardCourty** [comment]
Hi, I strongly agree with @devbranch-vitaliy, every index feature should be supported.
Please reopen this issue!

**Comment by colesnic89** [comment]
> Workaround: you can manually edit the table or add "DESC" in your migration query and luckily the schema generation tool doesn't revert it to ASC when you run it again

It drop previous index and create new one.

It is hard to do like this?

`#[ORM\Index(fields: ['ownerNumber', 'updatedAt' => 'DESC', 'id' => 'DESC'])]`

**Comment by colesnic89** [comment]
> ### Feature Request
> Q	A
> New Feature	yes
> RFC	no
> BC Break	no
> #### Summary
> Currently, there is no way to create a descending index (with the DESC attribute). This feature is present in MySQL, MSSQL, PostgreSQL, and probably in the other platforms as well. (In MySQL older than 8.0 and MariaDB it's accepted but ignored)
> 
> It should be allowed a way to create ASC/DESC indexes, for example with:
> 
> ```
> @ORM\Index(name="my_idx", columns={"col"}, options={"DESC"}),
> ```
> 
> Or
> 
> ```
> @ORM\Index(name="my_idx", columns={"col DESC"},
> ```

or like this

`#[ORM\Index(fields: ['ownerNumber', 'updatedAt' => 'DESC', 'id' => 'DESC'])]`
