### ISSUE TITLE
CLI tool documentation shows complicated way of creating a HelperSet

### ISSUE THREAD

**Issue by gbirke** [doctrine/orm#8129]
Hi,

The CLI setup section at https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/tools.html still shows how to manually create a HelperSet, while the introductory documentation at https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/configuration.html#setting-up-the-commandline-tool shows that you can just call `ConsoleRunner::createHelperSet($entityManager)`

I'd either remove all the detailed setup or put the short call to `ConsoleRunner::createHelperSet($entityManager);` first.

**Comment by SenseException** [comment]
Yes, the occurrances of the direct usage of `HelperSet` is from a time before 2.4. This is of course outdated by now. In #8002 we removed the references of an ORM version starting with the in the 2.8 branch and keep the `ConsoleRunner` in favour of the `HelperSet`.

As your links point it out, there's still work to do. I suggest to adapt the documentation for the usage of `ConsoleRunner` in https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/tools.html. Do you like to create a PR for that?

**Comment by gbirke** [comment]
I'd be happy to provide a documentation patch. For version 2.8 or 2.7?

**Comment by SenseException** [comment]
I'd say 2.8.

**Comment by beberlei** [comment]
Fixed in #8130
