### ISSUE TITLE
Deprecation notices from doctrine/inflector 1.4

### ISSUE THREAD

**Issue by W0rma** [doctrine/orm#8137]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.7/2.8.x

#### Summary

The old inflector API is deprecated since `doctrine/inflector` 1.4.

The new API is available in inflector 1.4. The new API should be used for 2.7/2.8 and master. See https://github.com/doctrine/common/issues/889

#### Current behavior

The following deprecation is triggered by https://github.com/doctrine/orm/blob/2.7/lib/Doctrine/ORM/EntityRepository.php#L305

    The "Doctrine\Common\Inflector\Inflector::classify" method is deprecated and will be dropped in doctrine/inflector 2.0. Please update to the new Inflector 
API.

#### How to reproduce

Just install this package together with `doctrine/inflector` 1.4.

#### Expected behavior

No deprecation should be triggered

**Comment by dkmuir** [comment]
Deprecations are still being thrown in 2.7.

**Comment by BurningDog** [comment]
I'm also seeing deprecations in 2.7. The PR which fixes this - https://github.com/doctrine/orm/pull/8147 - says

> This cannot go into 2.7, because it would raise PHP dependency from 7.1 to 7.2.

So we have to upgrade to 2.8.

**Comment by dkmuir** [comment]
> I'm also seeing deprecations in 2.7. The PR which fixes this - #8147 - says
> 
> > This cannot go into 2.7, because it would raise PHP dependency from 7.1 to 7.2.
> 
> So we have to upgrade to 2.8.

Fair enough. However, I would have thought deprecation warnings should only come into place once 2.8 is stable? Otherwise we're just getting warnings about something we can't actually do anything about.

**Comment by BurningDog** [comment]
Yes, one would think so! The Symfony 5 upgrade docs say to first fix all deprecation errors before upgrading, and this deprecation error is unfixable based on the currently used version of Doctrine. It seems quite messy to me, and I get annoying deprecation warnings every time I run unit tests - which I can do nothing about (and no, I'm not going to configure php to hide deprecation warnings; that's beside the point).

What I don't understand is, the 2.8 branch uses _exactly_ the same Inflector API call! Compare:

2.7: https://github.com/doctrine/orm/blob/2.7/lib/Doctrine/ORM/EntityRepository.php#L305
2.8 (master): https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/EntityRepository.php#L259

**Comment by sbacelic** [comment]
@BurningDog 2.8 is in another branch https://github.com/doctrine/orm/blob/2.8.x/lib/Doctrine/ORM/EntityRepository.php#L317

**Comment by GPHemsley** [comment]
Is there any word on when 2.8.0 will see a release to fix this? The milestone seems to still have a lot of open issues.

**Comment by beberlei** [comment]
Around PHP 8 release in a month
