### ISSUE TITLE
All of a sudden "Serialization of 'Closure' is not allowed" with RedisCache

### ISSUE THREAD

**Issue by Musiksammler** [doctrine/orm#8139]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | ?
| Version     | 3.0.x / dev-master

#### Summary

After a normal composer update today the following error occurs now when using RedisCache as cache handler: Serialization of 'Closure' is not allowed

Nothing else was changed in the application.

#### How to reproduce

Configure entity manager to use redis cache as cache handler.

**Comment by beberlei** [comment]
This looks like a problem with Redis and not with Doctrine Cache. Please attach the full stack trace otherwise we cannot find the cause of this.

**Comment by lcobucci** [comment]
Just wanted to mention that v3.x-dev isn't stable at all and shouldn't be used yet for production systems. You can see that many many tests fail and we're not yet running the second level cache suite.

**Comment by Musiksammler** [comment]
The stacktrace:

Exception: Serialization of 'Closure' is not allowed in file /var/www/html/web/vendor/doctrine/cache/lib/Doctrine/Common/Cache/RedisCache.php on line 123
Stack trace:
  1. Exception->() /var/www/html/web/vendor/doctrine/cache/lib/Doctrine/Common/Cache/RedisCache.php:123
  2. Redis->set() /var/www/html/web/vendor/doctrine/cache/lib/Doctrine/Common/Cache/RedisCache.php:123
  3. Doctrine\Common\Cache\RedisCache->doSave() /var/www/html/web/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php:115
  4. Doctrine\Common\Cache\CacheProvider->save() /var/www/html/web/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:265
  5. Doctrine\ORM\Mapping\ClassMetadataFactory->getMetadataFor() /var/www/html/web/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:286
  6. Doctrine\ORM\EntityManager->getClassMetadata() /var/www/html/web/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2174
  7. Doctrine\ORM\UnitOfWork->createEntity() /var/www/html/web/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php:240
  8. Doctrine\ORM\Internal\Hydration\ObjectHydrator->getEntity() /var/www/html/web/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php:461
  9. Doctrine\ORM\Internal\Hydration\ObjectHydrator->hydrateRowData() /var/www/html/web/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php:136
 10. Doctrine\ORM\Internal\Hydration\ObjectHydrator->hydrateAllData() /var/www/html/web/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php:137
 11. Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll() /var/www/html/web/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:929
 12. Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache() /var/www/html/web/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:874
 13. Doctrine\ORM\AbstractQuery->execute() /var/www/html/web/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:719
 14. Doctrine\ORM\AbstractQuery->getOneOrNullResult() /var/www/html/web/src/PackratsUser/User/Repository/Doctrine/UserRepository.php:38
 15. PackratsUser\User\Repository\Doctrine\UserRepository->getByCredentials() /var/www/html/web/src/PackratsSecurity/Session/Middleware/UserSessionMiddleware.php:103
 16. PackratsSecurity\Session\Middleware\UserSessionMiddleware->process() /var/www/html/web/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php:47
 17. Mezzio\Middleware\LazyLoadingMiddleware->process() /var/www/html/web/vendor/laminas/laminas-stratigility/src/Next.php:61
 18. Laminas\Stratigility\Next->handle() /var/www/html/web/vendor/mezzio/mezzio-flash/src/FlashMessageMiddleware.php:68
 19. Mezzio\Flash\FlashMessageMiddleware->process() /var/www/html/web/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php:47
 20. Mezzio\Middleware\LazyLoadingMiddleware->process() /var/www/html/web/vendor/laminas/laminas-stratigility/src/Next.php:61
 21. Laminas\Stratigility\Next->handle() /var/www/html/web/src/PackratsApp/Environment/Middleware/EnvironmentMiddleware.php:26
 22. PackratsApp\Environment\Middleware\EnvironmentMiddleware->process() /var/www/html/web/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php:47
 23. Mezzio\Middleware\LazyLoadingMiddleware->process() /var/www/html/web/vendor/laminas/laminas-stratigility/src/Next.php:61
 24. Laminas\Stratigility\Next->handle() /var/www/html/web/vendor/mezzio/mezzio-helpers/src/UrlHelperMiddleware.php:46
 25. Mezzio\Helper\UrlHelperMiddleware->process() /var/www/html/web/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php:47
 26. Mezzio\Middleware\LazyLoadingMiddleware->process() /var/www/html/web/vendor/laminas/laminas-stratigility/src/Next.php:61
 27. Laminas\Stratigility\Next->handle() /var/www/html/web/vendor/mezzio/mezzio-router/src/Middleware/MethodNotAllowedMiddleware.php:52
 28. Mezzio\Router\Middleware\MethodNotAllowedMiddleware->process() /var/www/html/web/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php:47
 29. Mezzio\Middleware\LazyLoadingMiddleware->process() /var/www/html/web/vendor/laminas/laminas-stratigility/src/Next.php:61
 30. Laminas\Stratigility\Next->handle() /var/www/html/web/vendor/mezzio/mezzio-router/src/Middleware/ImplicitOptionsMiddleware.php:71
 31. Mezzio\Router\Middleware\ImplicitOptionsMiddleware->process() /var/www/html/web/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php:47
 32. Mezzio\Middleware\LazyLoadingMiddleware->process() /var/www/html/web/vendor/laminas/laminas-stratigility/src/Next.php:61
 33. Laminas\Stratigility\Next->handle() /var/www/html/web/vendor/mezzio/mezzio-router/src/Middleware/ImplicitHeadMiddleware.php:85
 34. Mezzio\Router\Middleware\ImplicitHeadMiddleware->process() /var/www/html/web/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php:47
 35. Mezzio\Middleware\LazyLoadingMiddleware->process() /var/www/html/web/vendor/laminas/laminas-stratigility/src/Next.php:61
 36. Laminas\Stratigility\Next->handle() /var/www/html/web/vendor/mezzio/mezzio-router/src/Middleware/RouteMiddleware.php:55
 37. Mezzio\Router\Middleware\RouteMiddleware->process() /var/www/html/web/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php:47
 38. Mezzio\Middleware\LazyLoadingMiddleware->process() /var/www/html/web/vendor/laminas/laminas-stratigility/src/Next.php:61
 39. Laminas\Stratigility\Next->handle() /var/www/html/web/vendor/mezzio/mezzio-session/src/SessionMiddleware.php:35
 40. Mezzio\Session\SessionMiddleware->process() /var/www/html/web/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php:47
 41. Mezzio\Middleware\LazyLoadingMiddleware->process() /var/www/html/web/vendor/laminas/laminas-stratigility/src/Next.php:61
 42. Laminas\Stratigility\Next->handle() /var/www/html/web/vendor/mezzio/mezzio-helpers/src/ServerUrlMiddleware.php:38
 43. Mezzio\Helper\ServerUrlMiddleware->process() /var/www/html/web/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php:47
 44. Mezzio\Middleware\LazyLoadingMiddleware->process() /var/www/html/web/vendor/laminas/laminas-stratigility/src/Next.php:61
 45. Laminas\Stratigility\Next->handle() /var/www/html/web/src/PackratsError/Middleware/ErrorLoggerMiddleware.php:49
 46. PackratsError\Middleware\ErrorLoggerMiddleware->process() /var/www/html/web/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php:47
 47. Mezzio\Middleware\LazyLoadingMiddleware->process() /var/www/html/web/vendor/laminas/laminas-stratigility/src/Next.php:61
 48. Laminas\Stratigility\Next->handle() /var/www/html/web/src/PackratsError/Middleware/FallbackHandler.php:24
 49. PackratsError\Middleware\FallbackHandler->process() /var/www/html/web/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php:47
 50. Mezzio\Middleware\LazyLoadingMiddleware->process() /var/www/html/web/vendor/laminas/laminas-stratigility/src/Next.php:61
 51. Laminas\Stratigility\Next->handle() /var/www/html/web/src/PackratsSecurity/Middleware/HttpsMiddleware.php:38
 52. PackratsSecurity\Middleware\HttpsMiddleware->process() /var/www/html/web/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php:47
 53. Mezzio\Middleware\LazyLoadingMiddleware->process() /var/www/html/web/vendor/laminas/laminas-stratigility/src/Next.php:61
 54. Laminas\Stratigility\Next->handle() /var/www/html/web/src/PackratsApp/Middleware/InitMiddleware.php:44
 55. PackratsApp\Middleware\InitMiddleware->process() /var/www/html/web/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php:47
 56. Mezzio\Middleware\LazyLoadingMiddleware->process() /var/www/html/web/vendor/laminas/laminas-stratigility/src/Next.php:61
 57. Laminas\Stratigility\Next->handle() /var/www/html/web/src/PackratsApp/Middleware/OutputCompressMiddleware.php:44
 58. PackratsApp\Middleware\OutputCompressMiddleware->process() /var/www/html/web/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php:47
 59. Mezzio\Middleware\LazyLoadingMiddleware->process() /var/www/html/web/vendor/laminas/laminas-stratigility/src/Next.php:61
 60. Laminas\Stratigility\Next->handle() /var/www/html/web/vendor/laminas/laminas-stratigility/src/Middleware/ErrorHandler.php:144
 61. Laminas\Stratigility\Middleware\ErrorHandler->process() /var/www/html/web/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php:47
 62. Mezzio\Middleware\LazyLoadingMiddleware->process() /var/www/html/web/vendor/laminas/laminas-stratigility/src/Next.php:61
 63. Laminas\Stratigility\Next->handle() /var/www/html/web/src/PackratsError/Middleware/SentryMiddleware.php:50
 64. PackratsError\Middleware\SentryMiddleware->process() /var/www/html/web/vendor/mezzio/mezzio/src/Middleware/LazyLoadingMiddleware.php:47
 65. Mezzio\Middleware\LazyLoadingMiddleware->process() /var/www/html/web/vendor/laminas/laminas-stratigility/src/Next.php:61
 66. Laminas\Stratigility\Next->handle() /var/www/html/web/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php:84
 67. Laminas\Stratigility\MiddlewarePipe->process() /var/www/html/web/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php:73
 68. Laminas\Stratigility\MiddlewarePipe->handle() /var/www/html/web/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php:96
 69. Laminas\HttpHandlerRunner\RequestHandlerRunner->run() /var/www/html/web/vendor/mezzio/mezzio/src/Application.php:82
 70. Mezzio\Application->run() /var/www/html/web/public_html/index.php:44
 71. {closure}() /var/www/html/web/public_html/index.php:53

**Comment by Musiksammler** [comment]
It seems this problem is occuring in all other cache handlers. I tried the PhpFileCache as replacement and this one throws the same error. So it's not a redis problem.

**Comment by Musiksammler** [comment]
As far as I could see this must have something to do with associations (OneToOne, ManyToOne etc.). If I remove/comment-out all associations in the entities this error goes away.

**Comment by beberlei** [comment]
What packages specifically changed in your upgrade?

**Comment by Musiksammler** [comment]
The only change was in my composer.json.

Before: "doctrine/dbal": "dev-master#0ef7d47bc5055e45c5dd3c57d2121b5807ae0917 as 3.x-dev"
After: "doctrine/dbal": "dev-missed-commits"

For the ORM it was always "3.0.x-dev"

**Comment by beberlei** [comment]
We dont provide support for ORM 3 and DBAL master yet, its expected to break heavily, please dont use it
