### ISSUE TITLE
Too few parameters: the query defines n parameters but you only bound n-n

### ISSUE THREAD

**Issue by faso-dev** [doctrine/orm#8161]
Sorry if this is not the right place to expose the problem.

When we use the queryBuilder and we call setParameter first then setParameters in second, it overwrites the data defined with the setParameter, from my point of view I think it's inconsistent, because normally it should merge them or add them to the parameter table if they do not exist.
The above example reproduces the error:
```php 
    $builder = $this->queryBuilder()
            ->select('p', 'category', 'codePromo')
            ->leftJoin('p.category', 'category')
            ->leftJoin('p.codePromo', 'codePromo')
            ->leftJoin('p.images', 'images')
        ;
        if ( null !== $category){
            if (is_array($category)){
                $builder
                    ->andWhere('p.category IN (:categories)')
                    ->setParameter('categories', $category);
            }elseif ($category instanceof Category){
                $builder->andWhere('p.category = :category')
                    ->setParameter('category', $category);
            }
        }
      //The olds parameters values are lost after setParameters
      if ($search->getMinPrice() && $search->getMaxPrice()){
            $builder->andWhere('p.price BETWEEN :min AND :max')
                    ->setParameters([
                        'min' => $search->getMinPrice(),
                        'max' => $search->getMaxPrice(),
                    ]);
        }
      if ($search->getSearch()){
            $builder->andWhere('p.title LIKE :search')
                ->setParameter('search', '%'.$search->getSearch().'%');
        }
       return $builder->getQuery()->getResult();
```

**Comment by Xesau** [comment]
The API documentation specifically states that this is intended behaviour. I think in your case it's best to simply rewrite your code

```php
            $builder->andWhere('p.price BETWEEN :min AND :max')
                ->setParameter('min', $search->getMinPrice())
                ->setParameter('max', $search->getMaxPrice());
```

**Comment by faso-dev** [comment]
> The API documentation specifically states that this is intended behaviour. I think in your case it's best to simply rewrite your code
> 
> ```
>             $builder->andWhere('p.price BETWEEN :min AND :max')
>                 ->setParameter('min', $search->getMinPrice())
>                 ->setParameter('max', $search->getMaxPrice());
> ```

Yes I noticed. This is the solution that I finally opted for
