### ISSUE TITLE
Replace documentation example of "Blacklist" join query

### ISSUE THREAD

**Issue by albe** [doctrine/orm#8173]
https://github.com/doctrine/orm/blob/master/docs/en/reference/dql-doctrine-query-language.rst#arbitrary-join

shows an example of a join query with a "Blacklist" table. This could easily be changed to a more sensible example. I would suggest "Banlist" as alternative example.

**Comment by lsmith77** [comment]
FYI Symfony has a similar PR where the term "blocklist" is suggested https://github.com/symfony/symfony-docs/pull/13769
