### ISSUE TITLE
Allow to  disable association eager and lazy loading

### ISSUE THREAD

**Issue by videni** [doctrine/orm#8183]
Unless I explicitly specify the associations I need to query, I'd like to disable any kind of association loading, for example,  

User entity has two `roles`, 'groups' associations, 

```
$qb = $this->createQueryBuilder('o');
$qb->leftJoin('o.roles', 'r)
->addSelect('r)
->
->where('id', 2)
->getSingleResult();

````

 Since the `groups` association is not explicitly queried, I hope it remain empty.

**Comment by beberlei** [comment]
@videni thats exatly the way it works, it puts an empty Persistentcollection in `groups` that can be triggered later, but doesn't have to. We are not going to make this more configurable, you can already make sure lazy/eager is triggered or not.

**Comment by beberlei** [comment]
@videni Can you xplain the use case why you want to change it?

**Comment by videni** [comment]
@beberlei , Sorry for the late reply,  a lazy load association acts like a RPC,  a client may not know it will issue another SQL. I would rather fill association first manually, explicitly before using it. I really dislike lazy loading, seperate SQL executed  without notice.
