### ISSUE TITLE
Associated entities are persisted when no direct persist is called or cascade is not configured

### ISSUE THREAD

**Issue by phillipsnick** [doctrine/orm#8193]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | 2.7.3

#### Summary

If associated entities fetched using lazy loading are modified, they will be persisted along with the parent entity even when no persist has been called on the lazy loaded entity or any cascade configuration has been set.

#### Current behavior

Taking the example where a User can have many Events

- Fetch a single User 
- Lazy load all Events
- Modify the User
- Modify the Event (noting that Doctrine will in some cases pick up modifications as discovered under https://github.com/doctrine/orm/issues/5594)
- Persist ONLY the User
- Flush
- The Event will have been persisted to the database too

Query log

```
'"START TRANSACTION"' Params:
'UPDATE users SET email = ? WHERE userId = ?' Params: 'updated@test.com', 1
'UPDATE events SET amount = ? WHERE eventId = ?' Params: 20.0, 1
'"COMMIT"' Params:
'SELECT t0.eventId AS eventId_1, t0.amount AS amount_2, t0.userId AS userId_3 FROM events t0 LIMIT 1' Params:
```

#### How to reproduce

Please see pull request here: https://github.com/doctrine/orm/pull/8194

Run test with

```bash
vendor/bin/phpunit --filter GH8193
```

#### Expected behavior

- Fetch a single User 
- Lazy load all Events
- Modify the User
- Modify the Event 
- Persist ONLY the User
- Flush
- Event should not have been updated

Expected query log

```
'"START TRANSACTION"' Params:
'UPDATE users SET email = ? WHERE userId = ?' Params: 'updated@test.com', 1
'"COMMIT"' Params:
'SELECT t0.eventId AS eventId_1, t0.amount AS amount_2, t0.userId AS userId_3 FROM events t0 LIMIT 1' Params:
```

**Comment by beberlei** [comment]
Expected behavior, see PR comment
