### ISSUE TITLE
Symfony 5.1 has mayor issues, too many

### ISSUE THREAD

**Issue by raquilesc** [doctrine/orm#8207]
|    Q        |   A
|------------ | -----
| Version     | 5.1

### Support Question

doctrine/common                     2.13.3 3.0.2 PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection support, persistence in...
doctrine/doctrine-migrations-bundle 2.1.2  3.0.1 Symfony DoctrineMigrationsBundle
doctrine/inflector                  1.4.3  2.0.3 PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms of words.
doctrine/migrations                 2.2.1  3.0.1 PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for versioning your database schema and easily deploying ...
doctrine/persistence                1.3.7  2.0.0 The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.

script cache:clear returned with error code 1
!!  
!!  In ArrayNode.php line 320:
!!                                                                                 
!!    Unrecognized option "migrations_paths" under "doctrine_migrations". Availab  
!!    le options are "all_or_nothing", "column_length", "column_name", "custom_te  
!!    mplate", "dir_name", "executed_at_column_name", "name", "namespace", "organ  
!!    ize_migrations", "table_name".                                               
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd

I can't get Symfony 5 to run, too many issues with dependencies that are outdated or not working properly. 
I feel that I need to downgrade back to 4.5 until all these bugs are work on.

**Comment by beberlei** [comment]
The issue here is your upgrade from migrations v2 to v3. That changed a lot

**Comment by raquilesc** [comment]
I'm haven't migrated to one version to another, this is straight Symphony 5.1, a new project and it crashes with a bunch of dependencies issues of compatibility.

**Comment by beberlei** [comment]
Its a symfony, not a doctrine bug then.
