### ISSUE TITLE
Add QueryBuilder::setFetchMode

### ISSUE THREAD

**Issue by kirya-dev** [doctrine/orm#8219]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

Im would like to add new configure query builder method.
Im has following code:
``` PHP
    protected function configureQueryBuilder(QueryBuilder $qb, string $alias): void
    {
        $qb->getQuery()->setFetchMode(User::class, 'user', ClassMetadataInfo::FETCH_EAGER);
    }
```
Me need set fetch mode, but is impossible because getQuery creates new Query. There useless `setFetchMode` on new Query

`getQuery` must set `fetchMode` also `lifetime`, `cacheMode`, `cacheable` etc..
https://github.com/doctrine/orm/blob/2a98a98cd36e5eb54ad5ff8ca26fc3a30d5a82ff/lib/Doctrine/ORM/QueryBuilder.php#L344-L369

**Comment by beberlei** [comment]
This would be convenient, but also annoying to maintain and update for each new thing, i believe you should do this on your end.
