### ISSUE TITLE
EntityRepository::findOneBy() should throw NonUniqueResultException

### ISSUE THREAD

**Issue by KouloukLeGrand** [doctrine/orm#8225]
I have just read that a Query throws a NonUniqueResultException if Query::getOneOrNullResult() or Query::getSingleResult() is called and finds more than one matching result.

Do you think it is feasible? And if not, why?

**Comment by beberlei** [comment]
That is the way we want the API to work, multiple results can lead to the risk of the wrong one being picked without developer noticing.
