### ISSUE TITLE
Error: The annotation does not exist

### ISSUE THREAD

**Issue by ad-test** [doctrine/orm#8232]
I created a project, where the entities have annotations from both `Doctrine\ORM\Mapping` and `MyLib\Annotation`, like this:

```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use MyLib\Annotation as MA;

/**
 * @ORM\Entity
 * @ORM\Table(name="users")
 */
class User
{

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     * @MA\Example
     */
    public $id;

    /**
     * @ORM\Column(type="string")
     */
    public $name;

}
```

Unfortunately I get this error, if I try to run `orm:schema-tool:update`:

```
In AnnotationException.php line 54:

  [Semantical Error] The annotation "@MyLib\Annotation\Example" in property App\Entity\User::$id does not exist,
   or could not be auto-loaded.
```

I created a minimal reproducible example project, it can be found here: https://github.com/ad-test/doctrine-annotation-bug

**Comment by SenseException** [comment]
https://www.doctrine-project.org/projects/doctrine-annotations/en/1.10/annotations.html

If this is not an annotation relevant for Doctrine ORM and needs to be ignored, you'll have to tell Doctrine Annotations to ignore it. Otherwise it needs to be registered.
