### ISSUE TITLE
Is it still  necessary to wrap the __clone implementation in an if check?

### ISSUE THREAD

**Issue by sirdiego** [doctrine/orm#8247]
The [documentation](https://github.com/doctrine/orm/blob/2.7/docs/en/cookbook/implementing-wakeup-or-clone.rst) says that __clone (and __wakeup) are not save to implement without an id check. But the Instantiator has an [isSafeToClone](https://github.com/doctrine/instantiator/blob/1.3.x/src/Doctrine/Instantiator/Instantiator.php#L197) method that checks if there is an __clone method implemented. So is it still necessary to wrap the __clone into the id check?

Thanks!

**Comment by beberlei** [comment]
@sirdiego No, its not necessary anymore, that was before `ReflectionClass::newInstanceWithoutConstructor` was added in PHP 5.4 or 5.5
