### ISSUE TITLE
PHPBench: use of DBAL storage extension

### ISSUE THREAD

**Issue by dantleech** [doctrine/orm#8249]
Hey

I was going to remove the DBAL extension from PHPBench for 1.0:

- it's not fully implemented.
- it's complicated.

I notice that the ORM is using it:

- Does it provide any value to this project over the default XML storage driver? (i'd imagine the file size is smaller with sqlite f.e.)
- If so, is it worth splitting to a separate repo?

**Comment by Ocramius** [comment]
> Does it provide any value to this project over the default XML storage driver? (i'd imagine the file size is smaller with sqlite f.e.)

No, not really: XML works just fine for this sort of project.

 > If so, is it worth splitting to a separate repo?

If people need it, they will open issues, and then the pre-1.0 code can be recovered and split off.

**Comment by dantleech** [comment]
Great, then I'll just remove it for now.
