### ISSUE TITLE
Simple reverse engineered table keeps creating the same migrations 

### ISSUE THREAD

**Issue by devnix** [doctrine/orm#8261]
### Bug Report

A simple model keeps generating the same migrations over and over.

|    Q        |   A
|------------ | ------
| BC Break    | No (?)
| DBAL Version     | 2.10.3
| MariaDB Version     | 10.1.26

#### Summary

I've run the `doctrine:mapping:import` command on a Symfony project to generate models from an existing database. After that, I've run a diff to check that everything was OK. I have quite a lot of queries generated due to missing defaults in the annotations, but this migration is bugging me.

I've mapped to a model the following table:
```sql

CREATE TABLE `configuration` (
  `key_name` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `value` longtext COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `configuration`
  ADD PRIMARY KEY (`key_name`),
  ADD UNIQUE KEY `key_value` (`key_name`);```

Which generated the following model:
```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Configuration
 *
 * @ORM\Table(name="configuration", uniqueConstraints={@ORM\UniqueConstraint(name="key_value", columns={"key_name"})})
 * @ORM\Entity
 */
class Configuration
{
    /**
     * @var string
     *
     * @ORM\Column(name="key_name", type="string", length=60, nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $keyName;

    /**
     * @var string
     *
     * @ORM\Column(name="value", type="text", length=0, nullable=false)
     */
    private $value;


}
```

After that, running a migration diff gives me this SQL to migrate up
```sql
ALTER TABLE configuration CHANGE key_name key_name VARCHAR(60) NOT NULL
```

and this one to migrate down:
```sql
ALTER TABLE configuration CHANGE key_name key_name VARCHAR(60) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`'
```

#### Current behaviour

After running the migration up and generating another diff, an identical migration is generated.

#### How to reproduce

- Create the table
```sql

CREATE TABLE `configuration` (
  `key_name` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `value` longtext COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `configuration`
  ADD PRIMARY KEY (`key_name`),
  ADD UNIQUE KEY `key_value` (`key_name`);
```
- Generate the entity with the `bin/console doctrine:mapping:import` command
- Create a migration diff
- Run the diff
- Create another migration diff

#### Expected behaviour

It makes no sense that after running a migration, an identical migration is generated. The diff should be empty.

**Comment by devnix** [comment]
If you have Docker, Docker Compose and Symfony CLI installed the database parameters would automatically be joined, if not you have to tweak the connection parameters.

>It looks like an ORM issue. The migration is generated because the configuration.key_name column in the generated schema has autoincrement set to true but it's a string field which cannot be autoincremented. When it comes to comparison, the deployed schema never matches the desired state.

I cannot imagine how it can be possible, as I never set the `autoincrement` in that table! Is it something wrong with my table or with the MySQL mapping?
![image](https://user-images.githubusercontent.com/1777519/92358255-88b79400-f0e9-11ea-8896-7203363e46d1.png)

**Comment by devnix** [comment]
Also, if I remove the table keeping the model and I generate a migration to let Doctrine to create the table from scratch, it behaves the same way.

First migration:
```sql
CREATE TABLE configuration (key_name VARCHAR(60) NOT NULL, value LONGTEXT NOT NULL, UNIQUE INDEX key_value (key_name), PRIMARY KEY(key_name)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
```

After running and generating a second migration, the problem persists, so I guess Doctrine is assuming a primary key is autonumeric in MySQL/MariaDB?
```sql
ALTER TABLE configuration CHANGE key_name key_name VARCHAR(60) NOT NULL
```

**Comment by devnix** [comment]
So, seems like removing the `GeneratedValue` attribute, it works fine:

Old model:
```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * AbsConfiguration
 *
 * @ORM\Table(name="abs_configuration", uniqueConstraints={@ORM\UniqueConstraint(name="key_value", columns={"key_name"})})
 * @ORM\Entity
 */
class AbsConfiguration
{
    /**
     * @var string
     *
     * @ORM\Column(name="key_name", type="string", length=60, nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $keyName;

    /**
     * @var string
     *
     * @ORM\Column(name="value", type="text", length=0, nullable=false)
     */
    private $value;
}
```

New model:

```php 
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * AbsConfiguration
 *
 * @ORM\Table(name="abs_configuration", uniqueConstraints={@ORM\UniqueConstraint(name="key_value", columns={"key_name"})})
 * @ORM\Entity
 */
class AbsConfiguration
{
    /**
     * @var string
     *
     * @ORM\Column(name="key_name", type="string", length=60, nullable=false)
     * @ORM\Id
     */
    private $keyName;

    /**
     * @var string
     *
     * @ORM\Column(name="value", type="text", length=0, nullable=false)
     */
    private $value;
}
```

So the problem may not be on the migration but on the importation

**Comment by beberlei** [comment]
@devnix yes, you need to remove this annotation ` * @ORM\GeneratedValue(strategy="IDENTITY")`

**Comment by beberlei** [comment]
We don't expect the mapping import to work perfectly, it can only ever be a first step and might require further work. The reason is that database schema possibilities allow for much more features than Doctrine Schema abstraction supports. We don't want to close this gap, as such I am closing this issue.
