### ISSUE TITLE
`./bin/console doctrine:schema:create --dump-sql` generates invalid SQL

### ISSUE THREAD

**Issue by cmahnke** [doctrine/orm#8263]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.10.3

#### Summary

Running `./bin/console doctrine:schema:create --dump-sql` creates invalid SQL, the results are prepended with the following line `The following SQL statements will be executed:`

It's probably better to insert a comment sign before this line or omit it at all, since the user probably knows what to expect when running with `--dump-sql:` Not some redundant message, but proper SQL.

I'm using DoctrineBundle 2.1.2

Taken from [DoctrineBundle doctrine/dbal#1208] (https://github.com/doctrine/DoctrineBundle/issues/1208)

#### Current behaviour

Some status message is uncommented part of the SQL

#### How to reproduce

`./bin/console doctrine:schema:create --dump-sql`

#### Expected behaviour

Valid SQL, that can be used by `mysql` for example.

**Comment by greg0ire** [comment]
Here is the line where this comes from: https://github.com/doctrine/orm/blob/717ef9106c99abf10ef6dca8091e32ea3fb77a46/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/CreateCommand.php#L69

About your issue, is there an issue because you want to pipe the output to something that can parse SQL?

**Comment by cmahnke** [comment]
You're right, I've tried to used it in a multi staged  Docker build. Currently I've just added a `sed` before writing the results...
Except from the line it's reusable by `mysql` - is you r concern, that the SQL dialect can't be specified?
In general it's always better to design for machine readability - it usually allow other to implement things that the original developer didn't even think about...

**Comment by greg0ire** [comment]
My only concern is that it's not what this was meant for, but after a closer look, the option description does say "Instead of trying to apply generated SQLs into EntityManager Storage Connection, output them."

I think if you want to contribute this move to `stderr`, it will be accepted, and you can add tests to make sure no one breaks this in the future.

**Comment by glaszig** [comment]
given the description of the `--dump-sql` flag and the semantics of "dump" and "sql" this comment should not event be there in any case. it's completely useless. i constantly use the command and need to go into my generated file and remove the file and leading spaces.

    
      --dump-sql        Instead of trying to apply generated SQLs into EntityManager Storage Connection, output them.

this issue has been dangling around forever now.

related #7186.

**Comment by greg0ire** [comment]
@glaszig fix it then, what are you waiting for? This bug does not affect _me_.
