### ISSUE TITLE
Add New Attribute Metadata Driver

### ISSUE THREAD

**Issue by beberlei** [doctrine/orm#8265]
For Doctrine ORM 2.8 we should add a metadata driver using Attributes, based off the AnnotationDriver with some adjustment to account for the missing nested support.

Idea:
- Re-use `Doctrine\ORM\Mapping\*` annotation classes and add `#[Attribute]` as needed.
- Flatten `@JoinTable` by introducing new `InverseJoinColumn` attribute
- Flatten `@Table` by allowing `Index` and `UniqueConstraint` on the entity/class level.
- Drop support for named queries and named native queries in Attribute based mapping driver due to their nesting complexity.
- No support for association overrides in Attribute based mapping driver.

**Comment by beberlei** [comment]
Problem with this approach is that without a constructor using parameters, IDEs will probably not autocomplete the named properties of attributes. This requires us to duplicate all attribute classes unless we find some clever magic, or adjust the Annotation DocParser case with `has_constructor` must be changed or broken in some way.

**Comment by lcobucci** [comment]
Dropping named queries is a BC-break though

**Comment by beberlei** [comment]
@lcobucci not for a new metadata driver

**Comment by lcobucci** [comment]
Fair enough 👍

**Comment by beberlei** [comment]
Currently Annotation `DocParser` does `new $annotation($values);` if a constructor is detected. This is based on the `Annotation` base class that existis in the library. We should have another use-case where it checks for constructor but not extending `Doctrine\Common\Annotations\Nnnotation` and in that case replicate named arguments behavior: ``@Column(name="foo")`` maps to a constructor ``__construct($name)``.

This is required so we can move all annotation classes to use a constructor in ORM 2.8.

**Comment by beberlei** [comment]
The problem without this change is that we could not use `ReflectionAttribute::newInstance` then and also would probably confuse IDE autocomplete for attributes as they look for constructor arguments to suggest.

**Comment by BenMorel** [comment]
Looking forward to the attribute-based annotation driver! :+1:

> No support for association overrides in Attribute based mapping driver.

What's the issue with multiple `#[AssociationOverride()]` on the entity directly? (I've never understood the need for `@AssociationOverrides` in the first place, maybe a limitation in Doctrine Annotations?)

**Comment by beberlei** [comment]
This is merged with #8266
