### ISSUE TITLE
[Feature] Optimizing column alignment

### ISSUE THREAD

**Issue by flaushi** [doctrine/orm#8272]
Dear community,

I just stumbled over this article https://www.2ndquadrant.com/en/blog/on-rocks-and-sand/ where the benefits of an optimized column alignment are discussed.

I never thought about this before "because doctrine does all this for me". But is this true? When creating the sql statements to create the schema, is the column order optimized?

The rule of thumb to take large columns first looks like doctrine could implement this easily...?

**Comment by beberlei** [comment]
@flaushi This is outside of Doctrine's scope. We do not recommend to use the SchemaTool directly on production / deployment anyways, you are free to optimize the generated DDL SQL statements in a way that reduces the required table space by aligning columns better.

**Comment by flaushi** [comment]
@beberlei Ok, it was just an idea. 

> We do not recommend to use the SchemaTool directly on production
I guess thousands of users did not expect that.

**Comment by beberlei** [comment]
There is a big fat warning about it in the documentation as the first sentence about explaining SchemaTool: https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/tools.html#database-schema-generation
