### ISSUE TITLE
Add psalm template support for EntityManager, EntityRepository

### ISSUE THREAD

**Issue by beberlei** [doctrine/orm#8283]
See the Doctrine Psalm Plugin and move over the `@psalm-` docblocks for Doctrine 2.8:

* https://github.com/weirdan/doctrine-psalm-plugin/blob/master/stubs/EntityManager.phpstub
* https://github.com/weirdan/doctrine-psalm-plugin/blob/master/stubs/EntityManagerInterface.phpstub
* https://github.com/weirdan/doctrine-psalm-plugin/blob/master/stubs/EntityRepository.phpstub

**Comment by Nek-** [comment]
This issue can be closed.
