### ISSUE TITLE
Does an ID always need to be mapped to a property?

### ISSUE THREAD

**Issue by gjdanis** [doctrine/orm#8307]
Is mapping an ID to a property required? For example if I have:

```php

/**
 * @Entity
 * @Table(name="tblUser")
 */
class User
{
    /**
     * @Id
     * @Column(name="ID", type="integer")
     * @Column(name="ID", type="integer", nullable=false)
     * @GeneratedValue
     */
    private ?int $id;

    ...

```

And I never expose this field, do I need to have it mapped as a property. Is it possible to not map this field to a property?

**Comment by beberlei** [comment]
No, its required to have the property.
