### ISSUE TITLE
The docs suggest to use internal Autoloader::register()

### ISSUE THREAD

**Issue by BenMorel** [doctrine/orm#8313]
The [docs on autoloading proxies](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/advanced-configuration.html#autoloading-proxies) suggest to use:

```php
<?php
use Doctrine\Common\Proxy\Autoloader;

$proxyDir = "/path/to/proxies";
$proxyNamespace = "MyProxies";

Autoloader::register($proxyDir, $proxyNamespace);
```

Even though the `Autoloader` class is `@internal`:

```
namespace Doctrine\Common\Proxy;

/**
 * @internal
 */
class Autoloader
{
```

Is this a documentation issue in the ORM? Is there an alternative to using this internal class?
Or shouldn't the class be internal at all?

**Comment by stof** [comment]
I don't think the class should be internal. It is meant to be used this way
