### ISSUE TITLE
Requires package-versions-deprecated incompatible with Composer v2

### ISSUE THREAD

**Issue by kdambekalns** [doctrine/orm#8320]
With Composer v2 being released, this is becoming an issue:

```
$ composer why ocramius/package-versions
The "ocramius/package-versions" plugin was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
composer/package-versions-deprecated  1.11.99  replaces  ocramius/package-versions (1.11.99)
ocramius/package-versions             2.2.0    replaces  composer/package-versions-deprecated (*)

$ composer why composer/package-versions-deprecated
The "ocramius/package-versions" plugin was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
composer/package-versions-deprecated  1.11.99  replaces  ocramius/package-versions (1.11.99)
doctrine/orm                          2.7.4    requires  composer/package-versions-deprecated (^1.8)
```

Instead, `ocramius/package-versions` should be used.

**Comment by TimWerdin** [comment]
I think neither `ocramius/package-versions` nor `composer/package-versions-deprecated` should be used.
I doubt that it is necessary to install such a dependency - that currently creates a lot of issues - just to display the version of your own package on cli.
It was possible before in version 2.7.0 with just a simple constant.

**Comment by greg0ire** [comment]
>  It was possible before in version 2.7.0 with just a simple constant.

But we had to maintain that constant, right?

@kdambekalns care to make a PR?

**Comment by kdambekalns** [comment]
Looked into it:

- `doctrine/orm` 2.7 supports PHP ^7.1
- `ocramius/package-versions` 1.4 is the last that supports PHP 7.1
- a switch (back) to `ocramius/package-versions` is thus impossible for `doctrine/orm` v2.7 (and even up to 3.x as per version constraints of the involved packages)

Now… `composer/package-versions-deprecated` claims to support`composer-plugin-api` ^1.1.0 and ^2.0, so I wonder why that does not get picked up here…

**Comment by kdambekalns** [comment]
Let's see what https://github.com/composer/package-versions-deprecated/issues/15 leads us to–maybe it isn't a bug in `doctrine/orm` after all…

**Comment by TimWerdin** [comment]
> > It was possible before in version 2.7.0 with just a simple constant.
> 
> But we had to maintain that constant, right?
> 
> @kdambekalns care to make a PR?

I don't see an issue with maintaining a constant. This can even be automatically maintained by a CI script.
I would prefer this over adding an unnecessary dependency to a package that causes trouble for just one line of code

**Comment by kdambekalns** [comment]
As pointed out to me my problem was caused by a globally installed `ocramius/package-versions` and running `composer global update` solved it.

Sorry for the noise.
