### ISSUE TITLE
Plans for PHP 8 - promoted properties and attributes

### ISSUE THREAD

**Issue by ondrejmirtes** [doctrine/orm#8326]
Hi 👋 

What are your plans for PHP 8, especially promoted properties and attributes?

1) Are there going to be mapping attributes so we could use `#[ORM\Column]` instead of `/** @var ORM\Column */`?
2) Is Doctrine ORM going to supported mapping of promoted properties?
3) Will promoted properties be able to be mapped using both `@var` and attributes?

See relevant Twitter poll I made: https://twitter.com/OndrejMirtes/status/1322924057428373504

Thank you!

**Comment by beberlei** [comment]
Yes to all three qeustions, see #8266
