### ISSUE TITLE
PreFlush event is triggered on every flush even if already flushed

### ISSUE THREAD

**Issue by Seb33300** [doctrine/orm#8337]
I am encountering an issue where doctrine events are triggered every time the flush method is called, even if the entity was persisted only once.

I am using doctrine 2.7.4 with Symfony 4.4.

Example:
``` php

// $entity is an entity with a PreFlush event attached

$entityManager->persist($entity);
$entityManager->flush(); // the PreFlush event is triggered on $entity
$entityManager->flush(); // the PreFlush event is triggered a second time on $entity even if $entity was not persisted a second time before.
```

Is it normal that the second flush trigger the event a second time?

I thought it should be triggered only if we persist the entity a second time:
``` php

// $entity is an entity with a PreFlush event attached

$entityManager->persist($entity);
$entityManager->flush(); // the PreFlush event is triggered on $entity
$entityManager->flush(); // should not trigger the event
$entityManager->persist($entity);
$entityManager->flush(); // should trigger the event a second time
```

Thank you

**Comment by flaushi** [comment]
The preFlush event only has PreFlushEventArgs, which in turn do not have any entity, only the EntityManager is passed with them. So I think you mixed something up.

**Comment by lcobucci** [comment]
Closing as invalid based on the discussion in #8343
