### ISSUE TITLE
How to bind object params to raw sql

### ISSUE THREAD

**Issue by zmitic** [doctrine/orm#8355]
Consider this simplified example:

```php
$count = $em->createQuery('SELECT COUNT(o.id) FROM Contract o WHERE o.user = :user')
    ->setParameter('user', $user)  // $user is an object
    ->getQuery()->getSingleScalarResult();
```

This is very similar how pagination tools work, including one in Doctrine. The problem is that this will count **all** matches in table, thus making it pretty slow after few million rows.

And honestly; no one need something like ``you have 1.200.000 results`` at the cost of speed. But having something like ``there is more than 1.000 matches, please add more filters`` is something usable.

So I tried to limit COUNT and this worked:

```sql
SELECT COUNT(*) 
FROM (
    SELECT id FROM contract WHERE user_id="15"  LIMIT 1000
    ) AS id ;
```

but we can't put [subquery in FROM](https://github.com/doctrine/orm/issues/3542).

---

Now here is the question; once I extract SQL from $qb and wrap it like in example, how do I bind object params and arrays to NativeQuery?

I tried everything for hours, probably running in circles now... SO didn't help and it is important to reduce load time.

---

The example is oversimplified, it is actually full of conditions based on filters user selected. But it is important to bind params like in ``$qb->setParameter('user', $user)``.

**Comment by vstelmakh** [comment]
I was stuck at exactly the same problem. I wasn't able to find a proper way to get parameters from query builder and bind to generated SQL. But with using [Custom walkers](https://www.doctrine-project.org/projects/doctrine-orm/en/2.8/cookbook/dql-custom-walkers.html) you could create a workaround to count rows from sub query.
Here is an example worked for me:

1. First create SQL walker to modify query SQL output, to wrap it as a sub query of FROM:
```php
<?php

use Doctrine\ORM\Query\AST\SelectStatement;
use Doctrine\ORM\Query\SqlWalker;

class QueryRowCountSqlWalker extends SqlWalker
{
    public const ALIAS = 'count';

    public function walkSelectStatement(SelectStatement $AST): string
    {
        $sql = parent::walkSelectStatement($AST);
        $sql = sprintf('SELECT count(*) AS %s FROM (%s) tmp', self::ALIAS, $sql);
        return $sql;
    }
}
```

2. Than add result mapping to aware of count result:
```php
<?php

use Doctrine\ORM\Query\AST\SelectStatement;
use Doctrine\ORM\Query\TreeWalkerAdapter;

class QueryRowCountTreeWalker extends TreeWalkerAdapter
{
    public function walkSelectStatement(SelectStatement $AST): void
    {
        $parserResult = $this->_getParserResult();
        $resultSetMap = $parserResult->getResultSetMapping();
        $resultSetMap->addScalarResult(
            QueryRowCountSqlWalker::ALIAS,
            QueryRowCountSqlWalker::ALIAS,
            'integer'
        );
    }
}
```

3. Finally apply both walkers to query and get result:
```php
<?php

/** @var Doctrine\ORM\QueryBuilder $queryBuilder */
$queryBuilder->select('entity')->from(Entity::class, 'entity');

$query = $queryBuilder->getQuery();
$query->setHint(Query::HINT_CUSTOM_TREE_WALKERS, [QueryRowCountTreeWalker::class]);
$query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, QueryRowCountSqlWalker::class);

$count = $query->getSingleScalarResult();
````

It took me awhile to find this out. Hope, it will save someone's time.
