### ISSUE TITLE
Stringable objects are treated like "mapped" in 2.8.0

### ISSUE THREAD

**Issue by garak** [doctrine/orm#8366]
After upgrading to 2.8.0, I'm getting a lot of exceptions when I use stringable objects.
For example, using something like:

```php
/** @var \Doctrine\ORM\EntityManagerInterface $manager */
$manager
    ->createQueryBuilder()
    ->from(MyEntity::class, 'e')
    ->select('e')
    ->where('e.foo = :foo')
    ->setParameter('foo', $anObjectConvertableToString)
    ->setMaxResults(1)
    ->getQuery()
    ->getOneOrNullResult()
;
```

is working in doctrine/orm 2.7, while in 2.8 raises an exception:

> The class 'Namespace\AnObjectConvertableToString' was not found in the chain configured namespaces [...]

**Comment by beberlei** [comment]
@garak does `$anObjectConvertableToSTring` implement traversable? This 2.8 PR https://github.com/doctrine/orm/pull/8162 is changing related code you are talking about.

**Comment by garak** [comment]
No: it's just an object with a `__toString()` method.

**Comment by stof** [comment]
Looks like the catch on https://github.com/doctrine/orm/blob/418587bc25c107f16b53ae67a6ef8589408aff6c/lib/Doctrine/ORM/AbstractQuery.php#L450-L454 does not work properly anymore

**Comment by alex-dev** [comment]
Doctrine\ORM\Mapping\MappingException as ORMMappingException is caught, Doctrine\Persistence\Mapping\MappingException is throw in 2.8.
