### ISSUE TITLE
Break in 2.8: The class 'DateTime' was not found in the chain configured namespaces

### ISSUE THREAD

**Issue by kerbert101** [doctrine/orm#8367]
When I upgrade to 2.8 from 2.7.4 I get the error above. I think maybe it has something to do with the fact that I type hint with DateTimeInterface instead of DateTime. Maybe someone can take a look at it.

**Comment by guillaume-ro-fr** [comment]
I have the same problem in an entity repository, fixed if a specify the parameter type : 

```
use Doctrine\DBAL\Types\Types;

...

->setParameters(
                new ArrayCollection(
                    [
                        new Parameter('dummy_parameter', $dummy->getDateTime(), Types::DATETIME_MUTABLE),
                   ]
                )
            )
```

Doctrine cannot detect the DateTime type

**Comment by beberlei** [comment]
Duplicate of https://github.com/doctrine/orm/issues/8366
