### ISSUE TITLE
Deprecated notify change tracking policy

### ISSUE THREAD

**Issue by beberlei** [doctrine/orm#8383]
As apparent in #6380 and #6564 the notify change tracking policy has issues and no performance gains over deferred explicit. It should be deprecated during 2.* in some form and removed in 3.

**Comment by Arkemlar** [comment]
Then, how do we force doctrine to update fields like json that holding nested objects? Specifically I'm talking about [this case](https://github.com/dunglas/doctrine-json-odm?tab=readme-ov-file#limitations-when-updating-nested-properties), which is suggesting to use clone, but that's kind of ugly.
Would be nice to be able to stay in deferred policy but explicitly set property as updated when needed. At the moment this would require dirty UOW hacks from the client-side code :(
