### ISSUE TITLE
Issue with toIterable() and selecting multiple entities

### ISSUE THREAD

**Issue by Cartman34** [doctrine/orm#8413]
My code was previously working and since the last update, all the application is down due to toIterable() returning only the last entity when selecting multiple entities.

At line 179 in AbstractHydrator, Doctrine is doing yield end($result); causing the issue, the call to end() function should not be used.
$result is a simple array containing all retrieved entities, calling end() is just returning the last one.

https://github.com/doctrine/orm/blob/378944dd27c1953440c1797fc02ff4620ca956ea/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php#L179

I tested and the solution is really simple: Just remove the end() call, only yield $result;

This may be related to #8410

**Comment by SenseException** [comment]
Can you please show your code example and add the current result as also your expected result?

**Comment by Cartman34** [comment]
Ok, so this is a summary version of my code:
```
$userItems = $queryBuilder
	->select('event', 'event_user')
	->leftJoin(EventUser::class, 'event_user', Join::WITH, 'event = event_user.event AND event_user.user = :user')
	->getQuery()->toIterable();
foreach($userItems as $userItem) {
	// Got: No $userItem[1], $userItem[0] contains event_user
	// Expected : $userItem[0] contain event and $userItem[1] event_user
}
```
