### ISSUE TITLE
Returning null pls help

### ISSUE THREAD

**Issue by sbn111** [doctrine/orm#8416]
Function returning null in php 7 pls help to fix this.

public function newInstance()
    {  
         if ($this->_prototype === null) {
			// MODIF FR du 22/06/2014
			// $this->_prototype = unserialize(sprintf('O:%d:"%s":0:{}', strlen($this->name), $this->name));
          
			if (PHP_VERSION_ID === 50429 || PHP_VERSION_ID === 50513 || PHP_VERSION_ID === 50537) {
				$this->_prototype = $this->reflClass->newInstanceWithoutConstructor();
			} else {
                
                if(!($this->_prototype = @unserialize(sprintf('O:%d:"%s":0:{}', strlen($this->name), $this->name)))){
                    $this->_prototype = $this->reflClass->newInstanceWithoutConstructor();   
                }
                $this->_prototype = @unserialize(sprintf('O:%d:"%s":0:{}', strlen($this->name), $this->name));
			}
			// FIN MODIF FR du 22/06/2014
        }  
        return clone $this->_prototype; 
         
    }

**Comment by ostrolucky** [comment]
Sorry, we cannot do anything with such description
