### ISSUE TITLE
Running unit tests results in PHPUnit deprecation notice

### ISSUE THREAD

**Issue by mchekin** [doctrine/orm#8441]
- Branch: 2.8.x
- PHP 8.0.1 
- PHPUnit 9.5.1

Running unit tests results in deprecation notices:

> assertFileNotExists() is deprecated and will be removed in PHPUnit 10. Ref
actor your code to use assertFileDoesNotExist() instead.

![Screenshot 2021-01-26 224527](https://user-images.githubusercontent.com/2437233/105909764-4a832880-6028-11eb-84ed-12a1ad708a45.png)

**Comment by ostrolucky** [comment]
Thanks for noticing, but we don't need to have issue for that opened. They are just warnings and there isn't any good quick way to solve these.

**Comment by mchekin** [comment]
@ostrolucky 
Why not switching `assertFileDoesNotExist` ? 
I would gladly create a pull request for that.

**Comment by ostrolucky** [comment]
Because we need phpunit 8 so we can test with php 7.2
