### ISSUE TITLE
Deprecate YamlDriver, use Xml, Annotations, Attributes instead

### ISSUE THREAD

**Issue by beberlei** [doctrine/orm#8465]
The YAML Driver is deprecated and all users are encouraged to migrate to XML Driver instead for configuration that aims at separating code from mapping in different files.

YAML has no internal validation mechanism like XML has with XSD files and as such there is no validation in IDEs and only partial validation during the runtime of YAML driver. Especially typos in keys cannot be detected, so its possible to configure something that has no effect, because the config key does not actually exist.

You can migrate all your YAML to XML mappings by using the `orm:convert:mapping` command (for the Doctrine 2 CLI), `doctrine:mapping:convert` for the Symfony CLI, or directly using programmatic APIs:

```php
$metadata = $entityManager->getClassMetadataFactory()->getAllMetadata();
$factory = new ClassMetadataExporter();
$exporter = $factory->getExporter('xml', $destinationDirectory);
$exporter->setMetadata($metadata);
$exporter->export();
```
Please note that metadata exporter are also deprecated and removed in ORM 3 and they might not cover all available mappings 100%.

**Comment by SerafimArts** [comment]
> YAML has no internal validation mechanism like XML has with XSD files and as such there is no validation in IDE

I understand that it is already late and the decision (about deprecation) has already been made... but.

Json Schema? All yaml files are validated (and auto-completed in the IDE) based on the Json Schema.

We get approximately the following situation (reasons: advantages and disadvantages):

**XSD**
- Formats: `*.xml`
- ✔️/❌ - PHP builtin support (expects `ext-xml`/`ext-dom` additional extension).
- ✔️/❌ - Partial IDE autocompletion.
- ✔️ - IDE validation.

**Json Schema**
- Formats: `*.yaml`, `*.toml`, `*.json`, `*.json5`, static `*.php`, probably `*.neon` (did not check for autocomplete support) and other...
- ❌ - External composer package required.
- ✔️ - IDE autocompletion (Including a description of each field, what it is used for and how it can be applied).
- ✔️ - IDE validation.

imho, a unified schema validation format will allow the implementation of arbitrary metadata drivers (except XML and annotations/attributes).

P.S. For example, this is what autocomplete and validation looks like in the IDE if you select a `composer.json` scheme for the yaml file.

![image](https://github.com/doctrine/orm/assets/2461257/330b3874-b9c1-4c57-bcf9-3daa1897c8fd)
